import assert from 'node:assert/strict';
import { BrowserLocalInferenceAdapter, WLLAMA_COMPAT_CONFIG, WLLAMA_ASSET_CONFIG, needsWllamaCompat } from './browserLocalInferenceAdapter';
import { LocalInferenceRuntimeError, verifiedModelReferenceBrand, type VerifiedLocalModelReference } from './localInferenceContracts';
let loaded = false; let disposed = false; const calls: string[] = []; let loadOptions: Record<string, unknown> | null = null;
const fakeEngine = { setCompat(compat: unknown) { assert.deepEqual(compat, WLLAMA_COMPAT_CONFIG); calls.push('setCompat'); }, isModelLoaded() { return loaded; }, async loadModel(blobs: Blob[], options?: Record<string, unknown>) { assert.equal(blobs.length, 1); assert.equal(blobs[0].size, 4); loadOptions = options ?? null; assert.equal(loadOptions?.n_gpu_layers, undefined); loaded = true; calls.push('loadModel'); }, async createChatCompletion(options: Record<string, unknown>) { calls.push(options.stream === true ? 'stream' : 'generate'); if (options.stream === true) return (async function* () { yield { choices: [{ delta: { content: 'engine-output' }, finish_reason: 'stop' }] }; })(); return { choices: [{ message: { content: 'engine-output' }, finish_reason: 'stop' }], usage: { prompt_tokens: 3, completion_tokens: 1, total_tokens: 4 } }; }, async exit() { loaded = false; disposed = true; calls.push('exit'); } };
const okFetch: typeof fetch = async () => new Response('', { status: 200 });
const model: VerifiedLocalModelReference = { model: { id: 'test', name: 'test', version: '1', type: 'TEXT', format: 'GGUF', sizeBytes: 4, sha256: 'x', architectureRequirements: { supportedArchitectures: [] }, memoryRequirements: { requiredRamBytes: 1 }, storageRequirements: { requiredFreeStorageBytes: 1 }, platformRequirements: { requiredPlatform: 'any' }, downloadSource: null, availability: 'AVAILABLE', status: 'INSTALLED' }, [verifiedModelReferenceBrand]: true, async readVerifiedModel() { return new Blob([new Uint8Array([1, 2, 3, 4])]); } };
async function run(): Promise<void> {
  assert.equal(WLLAMA_ASSET_CONFIG.default.endsWith('/wllama/wllama.wasm'), true); assert.equal(WLLAMA_COMPAT_CONFIG.wasm.endsWith('/wllama-compat/wllama.wasm'), true); assert.equal(WLLAMA_COMPAT_CONFIG.worker.endsWith('/wllama-compat/wllama.js'), true);
  const noJspi = { Suspending: undefined } as unknown as typeof WebAssembly; assert.equal(needsWllamaCompat(noJspi), true); const jspiButNoMemory64 = { Suspending: function () {} } as unknown as typeof WebAssembly; assert.equal(needsWllamaCompat(jspiButNoMemory64), true);
  const adapter = new BrowserLocalInferenceAdapter(() => fakeEngine as never, okFetch, true); await adapter.initialize(); await adapter.loadModel(model); assert.equal(loadOptions?.n_ctx, 1024); assert.equal(loadOptions?.n_batch, 256); assert.equal(typeof loadOptions?.n_threads, 'number'); const response = await adapter.generate({ messages: [{ id: '1', conversationId: 'c', role: 'user', content: 'hello' }] }, new AbortController().signal); assert.equal(response.text, 'engine-output'); const events: string[] = []; for await (const event of adapter.stream({ messages: [{ id: '1', conversationId: 'c', role: 'user', content: 'hello' }] }, new AbortController().signal)) events.push(event.type === 'TOKEN' ? event.text : event.type); assert.deepEqual(events, ['engine-output', 'COMPLETE']); await adapter.dispose(); assert.equal(disposed, true);
  const compatWasmFailure = new BrowserLocalInferenceAdapter(() => fakeEngine as never, async (input) => input.toString().includes('wllama-compat/wllama.wasm') ? Promise.reject(new TypeError('Failed to fetch')) : new Response('', { status: 200 }), true); await assert.rejects(() => compatWasmFailure.initialize(), (error: unknown) => { const e = error as LocalInferenceRuntimeError; return e.code === 'WLLAMA_COMPAT_WASM_FETCH_FAILED' && e.diagnostic?.resource === 'wllama.wasm' && e.diagnostic?.status === undefined; });
  const workerFailure = new BrowserLocalInferenceAdapter(() => fakeEngine as never, async (input) => input.toString().includes('wllama-compat/wllama.js') ? Promise.reject(new TypeError('Failed to fetch')) : new Response('', { status: 200 }), true); await assert.rejects(() => workerFailure.initialize(), (error: unknown) => { const e = error as LocalInferenceRuntimeError; return e.code === 'WLLAMA_WORKER_ASSET_FAILED' && e.diagnostic?.resource === 'wllama.js'; });
  console.log('browserLocalInferenceAdapter.test.ts: PASS');
}
run().catch((error) => { console.error(error); throw error; });
