import assert from 'node:assert/strict';
import { WebModelDownloader } from '../model/webModelDownloader';
import { LocalInferenceRuntimeError } from './localInferenceContracts';
import { sanitizeDiagnosticUrl, formatDiagnosticForClipboard, type LocalAiDiagnostic } from './localAiDiagnostics';
const model = { id: 'qwen-test', name: 'Qwen test', version: 'v1', type: 'TEXT' as const, format: 'GGUF' as const, sizeBytes: 4, sha256: null, architectureRequirements: { supportedArchitectures: [] }, memoryRequirements: { requiredRamBytes: 1 }, storageRequirements: { requiredFreeStorageBytes: 1 }, platformRequirements: { requiredPlatform: 'any' as const }, downloadSource: { kind: 'external' as const, uri: 'https://example.invalid/model.gguf?token=secret&sig=private' }, availability: 'AVAILABLE' as const, status: 'NOT_INSTALLED' as const };
async function expectFailure(fetchImpl: typeof fetch, check: (error: LocalInferenceRuntimeError) => void) { const original = globalThis.fetch; globalThis.fetch = fetchImpl; try { await assert.rejects(() => new WebModelDownloader().download(model), (error: unknown) => { if (!(error instanceof LocalInferenceRuntimeError)) return false; check(error); return true; }); } finally { globalThis.fetch = original; } }
async function run(): Promise<void> {
  await expectFailure(async () => { throw new TypeError('Failed to fetch'); }, (error) => { assert.equal(error.code, 'MODEL_DOWNLOAD_FETCH_FAILED'); assert.equal(error.diagnostic?.status, undefined); assert.equal(error.diagnostic?.errorName, 'TypeError'); assert.equal(error.diagnostic?.url, 'https://example.invalid/model.gguf'); assert.equal(error.diagnostic?.responseRedirected, undefined); });
  for (const status of [404, 403, 500]) await expectFailure(async () => new Response('failure', { status }), (error) => { assert.equal(error.code, 'MODEL_DOWNLOAD_HTTP_FAILED'); assert.equal(error.diagnostic?.status, status); assert.equal(error.diagnostic?.responseOk, false); });
  const bodyError = { ok: true, status: 200, statusText: 'OK', type: 'basic', redirected: false, url: 'https://example.invalid/model.gguf', headers: new Headers({ 'content-length': '4' }), body: { getReader() { return { read: async () => { throw new Error('stream broke'); }, releaseLock() {} }; } } } as unknown as Response;
  await expectFailure(async () => bodyError, (error) => { assert.equal(error.code, 'MODEL_DOWNLOAD_RESPONSE_READ_FAILED'); assert.equal(error.diagnostic?.status, 200); assert.equal(error.diagnostic?.responseOk, true); assert.equal(error.diagnostic?.responseBodyAvailable, true); assert.equal(error.diagnostic?.downloadedBytes, 0); });
  assert.equal(sanitizeDiagnosticUrl('https://example.com/a?token=secret&api_key=hidden#fragment'), 'https://example.com/a');
  const diagnostic: LocalAiDiagnostic = { stage: 'WLLAMA_COMPAT_WASM', code: 'WLLAMA_COMPAT_WASM_FETCH_FAILED', message: 'fetch failed', resource: 'wllama.wasm', url: 'https://example.com/wllama.wasm', timestamp: new Date().toISOString() }; const copied = formatDiagnosticForClipboard(diagnostic); assert.match(copied, /WLLAMA_COMPAT_WASM/); assert.doesNotMatch(copied, /token|api_key|authorization/i);
  console.log('localAiDiagnostics.test.ts: PASS');
}
run().catch((error) => { console.error(error); throw error; });
