import type { AiProviderStatusReasonCode, AiRoutingMode } from './providers/contracts';
export type AiPremiumMode = AiRoutingMode;
export type AiPremiumRouteState = 'online' | 'offline' | 'unavailable';
export interface AiPremiumStatusInput { requestedMode: AiPremiumMode; provider: 'gemini' | 'local' | null; routeMode: 'online' | 'offline' | null; reasonCode?: AiProviderStatusReasonCode; reason?: string; localAvailable: boolean; }
export interface AiPremiumStatusView { modeLabel: 'AUTO' | 'ONLINE' | 'OFFLINE'; providerLabel: 'Gemini' | 'Local AI' | '—'; routeLabel: 'Online' | 'Offline' | 'Unavailable'; detail: string; processingLabel: 'Processed online' | 'Processed locally' | 'Not sent online' | null; localLabel: string; modelLabel: string; visionLabel: string; }
function diagnosticDetail(code: AiProviderStatusReasonCode | undefined, reason: string | undefined): string { if (reason) return reason; switch (code) { case 'MODEL_DOWNLOADING': return 'Downloading local AI model…'; case 'MODEL_VERIFYING': return 'Verifying local AI model…'; case 'RUNTIME_INITIALIZING': return 'Initializing local WASM runtime…'; case 'MODEL_LOADING': return 'Loading verified local model into the runtime…'; case 'MODEL_LOAD_FAILED': return 'Local model could not be loaded by the browser runtime.'; case 'MODEL_INVALID': return 'Local model verification failed; it was not executed.'; case 'MODEL_INCOMPATIBLE': return 'This browser/device does not meet the local model requirements.'; case 'INSUFFICIENT_RESOURCES': return 'This browser/device does not have enough resources for local AI.'; case 'INFERENCE_FAILED': return 'Local AI inference failed.'; case 'RUNTIME_UNAVAILABLE': case 'LOCAL_RUNTIME_UNAVAILABLE': case 'OFFLINE_TEXT_AI_UNAVAILABLE': return 'The browser local inference runtime is unavailable.'; default: return 'Local AI is not ready.'; } }
export function buildAiPremiumStatus(input: AiPremiumStatusInput): AiPremiumStatusView {
  const modeLabel = input.requestedMode.toUpperCase() as AiPremiumStatusView['modeLabel']; const providerLabel = input.provider === 'gemini' ? 'Gemini' : input.provider === 'local' ? 'Local AI' : '—'; const routeLabel = input.routeMode === 'online' ? 'Online' : input.routeMode === 'offline' ? 'Offline' : 'Unavailable'; const localUnavailable = !input.localAvailable; let detail = diagnosticDetail(input.reasonCode, input.reason);
  if (input.requestedMode === 'auto' && input.provider === 'gemini' && localUnavailable) detail = 'Online AI selected automatically · Local AI unavailable'; else if (input.requestedMode === 'online') detail = 'Online AI · Gemini'; else if (input.requestedMode === 'offline' && input.provider === 'local') detail = 'Offline AI · local processing';
  const processingLabel = input.routeMode === 'online' ? 'Processed online' : input.routeMode === 'offline' ? 'Processed locally' : input.requestedMode === 'offline' ? 'Not sent online' : null;
  const localLabel = localUnavailable ? `Offline AI · Unavailable · ${diagnosticDetail(input.reasonCode, input.reason)}` : 'Offline AI · Available';
  const modelLabel = input.reasonCode === 'MODEL_NOT_INSTALLED' ? 'Local Model · Not installed' : input.reasonCode === 'MODEL_INVALID' ? 'Local Model · Invalid' : input.reasonCode === 'MODEL_DOWNLOADING' ? 'Local Model · Downloading' : input.reasonCode === 'MODEL_VERIFYING' ? 'Local Model · Verifying' : input.reasonCode === 'MODEL_LOADING' ? 'Local Model · Loading' : localUnavailable ? 'Local Model · Not ready' : 'Local Model · Ready';
  const visionLabel = input.reasonCode === 'VISION_NOT_SUPPORTED' ? 'Offline Vision · Not supported' : input.reasonCode === 'VISION_RUNTIME_UNAVAILABLE' ? 'Offline Vision · Unavailable' : localUnavailable ? 'Offline Vision · Not ready' : 'Offline Vision · Available';
  return { modeLabel, providerLabel, routeLabel, detail, processingLabel, localLabel, modelLabel, visionLabel };
}
export function friendlyAiError(error: unknown, requestedMode: AiPremiumMode): string { const code = error && typeof error === 'object' && 'code' in error ? String((error as { code?: unknown }).code) : ''; if (code === 'MODEL_NOT_INSTALLED') return 'The local AI model is not installed on this runtime.'; if (code === 'MODEL_INVALID') return 'The local AI model could not be verified, so it was not used.'; if (code === 'MODEL_LOAD_FAILED') return 'The verified local model could not be loaded by the browser runtime.'; if (code === 'RUNTIME_INITIALIZING') return 'The browser local AI runtime is still initializing.'; if (code === 'INSUFFICIENT_RESOURCES') return 'This browser/device does not have enough resources for local AI.'; if (code === 'MODEL_INCOMPATIBLE') return 'This browser/device is incompatible with the local AI model.'; if (code === 'INFERENCE_FAILED') return 'Local AI inference failed.'; if (requestedMode === 'offline' || code === 'OFFLINE_TEXT_AI_UNAVAILABLE' || code === 'LOCAL_RUNTIME_UNAVAILABLE' || code === 'RUNTIME_UNAVAILABLE') return 'Offline AI is unavailable on this runtime. Your request was not sent online.'; if (code === 'VISION_RUNTIME_UNAVAILABLE' || code === 'VISION_NOT_SUPPORTED') return 'Offline Vision is unavailable on this runtime. The image was not processed locally.'; if (error instanceof Error && error.message) return error.message; return 'Work Social AI could not complete that request.'; }
