import { useEffect, useMemo, useState } from 'react';
import { calculateContractorActualRate, calculateContractorCommission, calculateContractorTotal, formatContractorMoney, roundContractorMoney, type ContractorCommissionMode, type ContractorCommissionType } from '../logic/contractorEntryCalculations';

type Entry = { id:string; item_name:string; size:string; pieces:number; rate_per_piece:number; commission_type:'percentage'|'per_piece'|null; commission_value:number|null; commission_mode:'included'|'separate'|null; commission_per_piece:number; actual_rate_per_piece:number; total:number; occurred_at:string; special_note?:string|null };
interface Props { entry: Entry|null; saving:boolean; onClose:()=>void; onSave:(id:string,input:Partial<Entry>)=>Promise<{error:unknown}|{error:null}>; }
const input={width:'100%',minHeight:42,boxSizing:'border-box' as const,padding:'0 11px',border:'1px solid rgba(71,85,105,.18)',borderRadius:12,background:'linear-gradient(180deg,#fff,#f3f8fa)',color:'#172033',font:'inherit',fontSize:13,fontWeight:750,outline:'none',boxShadow:'inset 0 2px 0 #fff,inset 0 -2px 4px rgba(15,23,42,.06),0 4px 9px rgba(15,23,42,.06)'};
export function ContractorEntryEditModal({entry,saving,onClose,onSave}:Props){
 const [item,setItem]=useState('');const [size,setSize]=useState('');const [pieces,setPieces]=useState('');const [rate,setRate]=useState('');const [type,setType]=useState<ContractorCommissionType>('percentage');const [commission,setCommission]=useState('');const [mode,setMode]=useState<ContractorCommissionMode|null>(null);const [note,setNote]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(!entry)return;setItem(entry.item_name);setSize(entry.size);setPieces(String(entry.pieces));setRate(String(entry.rate_per_piece));setType(entry.commission_type??'percentage');setCommission(entry.commission_value==null?'':String(entry.commission_value));setMode(entry.commission_mode);setNote(entry.special_note??'');setError('')},[entry]);
 const p=Number(pieces),r=Number(rate),cv=commission===''?null:Number(commission);const cpp=useMemo(()=>calculateContractorCommission(r,commission===''?null:type,cv),[r,type,cv,commission]);const actual=useMemo(()=>calculateContractorActualRate(r,cpp,mode),[r,cpp,mode]);const total=useMemo(()=>calculateContractorTotal(p,actual),[p,actual]);
 if(!entry)return null;
 const save=async()=>{if(!item.trim()||!size.trim())return setError('Item Name and Size are required.');if(!Number.isFinite(p)||p<=0)return setError('Pieces must be greater than 0.');if(!Number.isFinite(r)||r<0)return setError('Rate must be 0 or greater.');if(commission!==''&&(!Number.isFinite(cv!)||cv!<0))return setError('Enter a valid commission.');if(type==='percentage'&&cv!==null&&cv>100)return setError('Percentage commission must be 0–100%.');if(commission!==''&&!mode)return setError('Choose Included or Extra.');if(mode==='included'&&cpp>r)return setError('Included commission cannot be greater than rate.');if(actual<0)return setError('Actual rate cannot be negative.');await onSave(entry.id,{item_name:item.trim(),size:size.trim(),pieces:p,rate_per_piece:r,commission_type:commission===''?null:type,commission_value:commission===''?null:cv,commission_mode:commission===''?null:mode,commission_per_piece:roundContractorMoney(cpp),actual_rate_per_piece:roundContractorMoney(actual),total:roundContractorMoney(total),special_note:note.trim()||null})};
 return <div className="cex-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)onClose()}}><section className="cex-modal" role="dialog" aria-modal="true"><div className="cex-top"><div><div className="cex-kicker">Contractor Work Record</div><h2>Edit Entry</h2><p>Update this real work record without changing its ownership.</p></div><button className="cex-close" type="button" onClick={onClose} disabled={saving}>×</button></div><div className="cex-grid"><label>Item Name<input value={item} onChange={e=>setItem(e.target.value)} style={input}/></label><label>Size<input value={size} onChange={e=>setSize(e.target.value)} style={input}/></label><div className="cex-two"><label>Pieces<input inputMode="decimal" value={pieces} onChange={e=>setPieces(e.target.value)} style={input}/></label><label>Rate / Piece<input inputMode="decimal" value={rate} onChange={e=>setRate(e.target.value)} style={input}/></label></div><div className="cex-commission"><div className="cex-section-title">Commission</div><div className="cex-two"><button type="button" className={type==='percentage'?'cex-opt selected':'cex-opt'} onClick={()=>setType('percentage')}>Percentage</button><button type="button" className={type==='per_piece'?'cex-opt selected':'cex-opt'} onClick={()=>setType('per_piece')}>PKR / Piece</button></div><input inputMode="decimal" value={commission} onChange={e=>setCommission(e.target.value)} placeholder={type==='percentage'?'25':'3'} style={{...input,marginTop:7}}/><div className="cex-section-title" style={{marginTop:9}}>Application</div><div className="cex-two"><button type="button" className={mode==='included'?'cex-opt selected':'cex-opt'} onClick={()=>setMode('included')}>Included / Minus</button><button type="button" className={mode==='separate'?'cex-opt selected':'cex-opt'} onClick={()=>setMode('separate')}>Extra / Add</button></div><button type="button" className="cex-skip" onClick={()=>{setCommission('');setMode(null)}}>No Commission</button></div><label>Special Note<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} style={{...input,padding:'10px 11px',resize:'vertical'}}/></label>{error&&<div className="cex-error">{error}</div>}<div className="cex-preview"><div><small>Actual / Piece</small><strong>PKR {formatContractorMoney(Number.isFinite(actual)?actual:0)}</strong></div><div><small>Total</small><strong>PKR {formatContractorMoney(Number.isFinite(total)?total:0)}</strong></div></div><button className="cex-save" type="button" onClick={()=>void save()} disabled={saving}>{saving?'Saving…':'Save Changes'}</button></div></section></div>;
}
