import { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabase/client';

type Props={profileId:string;teamNumber:string};
type Member={profile_id:string;display_name:string|null;username:string|null;avatar_url:string|null;status:'member'|'pending'};
const initials=(n:string)=>n.trim()?n.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase():'W';
export function ContractorTeamMembersPanel({profileId,teamNumber}:Props){
 const [open,setOpen]=useState(false),[members,setMembers]=useState<Member[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const {data:t,error:te}=await supabase.from('contractor_teams').select('id').eq('team_number',Number(teamNumber)).eq('leader_profile_id',profileId).maybeSingle<{id:number}>();if(te||!t){setError(te?.message??'Team not found.');setLoading(false);return}const [m,i]=await Promise.all([supabase.from('contractor_team_members').select('profile_id,joined_at').eq('team_id',t.id).order('joined_at',{ascending:false}),supabase.from('contractor_team_invitations').select('worker_profile_id,created_at').eq('team_id',t.id).eq('status','pending').order('created_at',{ascending:false})]);if(m.error||i.error){setError(m.error?.message??i.error?.message??'Members could not be loaded.');setLoading(false);return}const ids=[...new Set([...(m.data??[]).map(x=>x.profile_id),...(i.data??[]).map(x=>x.worker_profile_id)])];if(!ids.length){setMembers([]);setLoading(false);return}const {data:p,error:pe}=await supabase.from('profiles').select('id,display_name,username,avatar_url').in('id',ids);if(pe){setError(pe.message);setLoading(false);return}const map=new Map((p??[]).map((x:any)=>[x.id,x]));const active=new Set((m.data??[]).map(x=>x.profile_id));setMembers([...(m.data??[]).map(x=>({...map.get(x.profile_id),profile_id:x.profile_id,status:'member' as const})),...(i.data??[]).filter(x=>!active.has(x.worker_profile_id)).map(x=>({...map.get(x.worker_profile_id),profile_id:x.worker_profile_id,status:'pending' as const}))].filter(x=>map.has(x.profile_id)));setLoading(false)};
 useEffect(()=>{let b:HTMLButtonElement|null=null;const click=(e:Event)=>{e.preventDefault();e.stopImmediatePropagation();setOpen(true);void load()};const attach=()=>{const bs=[...document.querySelectorAll<HTMLButtonElement>('.contractor-team-page .ctd-action')];const n=bs.at(-1)??null;if(!n||n===b)return;if(b)b.removeEventListener('click',click,true);b=n;b.addEventListener('click',click,true)};attach();const o=new MutationObserver(attach);o.observe(document.body,{childList:true,subtree:true});return()=>{o.disconnect();if(b)b.removeEventListener('click',click,true)}},[]);
 useEffect(()=>{if(!open)return;const f=(e:KeyboardEvent)=>e.key==='Escape'&&setOpen(false);document.addEventListener('keydown',f);return()=>document.removeEventListener('keydown',f)},[open]);
 return open?<div className="ctm-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><style>{`.ctm-backdrop{position:fixed;inset:0;z-index:1250;display:grid;place-items:start center;padding:66px 12px 18px;background:rgba(7,20,30,.42);backdrop-filter:blur(12px)}.ctm-panel{width:min(430px,100%);max-height:calc(100dvh - 84px);overflow:auto;padding:16px;border:1px solid rgba(255,255,255,.95);border-radius:25px;background:linear-gradient(145deg,#fff,#ecfdf5,#eff6ff);box-shadow:0 35px 90px rgba(15,23,42,.3),inset 0 1px 0 #fff}.ctm-head{display:flex;justify-content:space-between;align-items:center}.ctm-kicker{font-size:8px;letter-spacing:.15em;font-weight:950;color:#047857}.ctm-title{margin:5px 0 0;font-size:22px;font-weight:950;color:#172033}.ctm-close{width:34px;height:34px;border:1px solid #e2e8f0;border-radius:10px;background:#fff;font-size:17px}.ctm-list{display:grid;gap:8px;margin-top:14px}.ctm-row{display:grid;grid-template-columns:40px minmax(0,1fr) auto;align-items:center;gap:9px;padding:9px;border-radius:14px;background:linear-gradient(145deg,#fff,#f8fafc);border:1px solid #fff;box-shadow:0 8px 18px rgba(15,23,42,.065),inset 0 1px 0 #fff}.ctm-avatar{width:40px;height:40px;border-radius:12px;overflow:hidden;display:grid;place-items:center;background:linear-gradient(145deg,#d1fae5,#dbeafe);color:#047857;font-size:12px;font-weight:950}.ctm-avatar img{width:100%;height:100%;object-fit:cover}.ctm-name{font-size:10px;font-weight:950;color:#172033}.ctm-user{font-size:8px;color:#64748b;margin-top:2px}.ctm-status{padding:5px 7px;border-radius:999px;font-size:7px;font-weight:950}.ctm-member{background:#dcfce7;color:#15803d}.ctm-pending{background:#fef3c7;color:#a16207}.ctm-empty{margin-top:13px;padding:13px;border-radius:13px;text-align:center;font-size:9px;color:#64748b;background:rgba(255,255,255,.72);border:1px dashed #cbd5e1}.ctm-error{color:#b91c1c;background:#fef2f2}`}</style><section className="ctm-panel" role="dialog" aria-modal="true"><div className="ctm-head"><div><div className="ctm-kicker">TEAM MEMBERS · {teamNumber}</div><h2 className="ctm-title">My Team Members</h2></div><button type="button" className="ctm-close" onClick={()=>setOpen(false)}>×</button></div>{loading?<div className="ctm-empty">Loading real team members…</div>:error?<div className="ctm-empty ctm-error">{error}</div>:members.length?<div className="ctm-list">{members.map(m=><div className="ctm-row" key={`${m.status}-${m.profile_id}`}><div className="ctm-avatar">{m.avatar_url?<img src={m.avatar_url} alt=""/>:initials(m.display_name||'')}</div><div><div className="ctm-name">{m.display_name||'Unnamed worker'}</div>{m.username&&<div className="ctm-user">@{m.username}</div>}</div><span className={`ctm-status ${m.status==='member'?'ctm-member':'ctm-pending'}`}>{m.status==='member'?'🟢 Member':'Pending'}</span></div>)}</div>:<div className="ctm-empty">No team members or pending invitations yet.</div>}</section></div>:null;
}
