import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabase';
import { useAuth } from '../../../app/AuthContext';
import { useNavigate } from 'react-router-dom';
import { ContractorNewEntryModal } from './ContractorNewEntryModal';
import { ContractorEntryEditModal } from './ContractorEntryEditModal';
import { calculateContractorActualRate, calculateContractorCommission, calculateContractorTotal, formatContractorMoney, roundContractorMoney, type ContractorCommissionMode, type ContractorCommissionType } from '../logic/contractorEntryCalculations';

type Entry={id:string;item_name:string;size:string;pieces:number;rate_per_piece:number;commission_type:'percentage'|'per_piece'|null;commission_value:number|null;commission_mode:'included'|'separate'|null;commission_per_piece:number;actual_rate_per_piece:number;total:number;occurred_at:string;special_note?:string|null};
type DetailType='daily'|'weekly'|'monthly'|'grand';

type ContractorEntryInput={item_name:string;size:string;pieces:number;rate_per_piece:number;commission_type:'percentage'|'per_piece'|null;commission_value:number|null;commission_mode:'included'|'separate'|null;commission_per_piece:number;actual_rate_per_piece:number;total:number;special_note:string|null;occurred_at?:string};

function dateKey(d:Date){return d.toISOString().slice(0,10)}
function startOfWeek(d:Date){const x=new Date(d);const day=x.getDay();const diff=day===0?-6:1-day;x.setDate(x.getDate()+diff);x.setHours(0,0,0,0);return x}
function endOfDay(d:Date){const x=new Date(d);x.setHours(23,59,59,999);return x}
function startOfMonth(d:Date){const x=new Date(d);x.setDate(1);x.setHours(0,0,0,0);return x}
function endOfMonth(d:Date){const x=startOfMonth(d);x.setMonth(x.getMonth()+1);x.setMilliseconds(-1);return x}

function EntryRow({entry,onMenu}:{entry:Entry;onMenu?:(entry:Entry)=>void}){return <div className="cd-entry"><div className="cd-entry-top"><div><div className="cd-entry-name">{entry.item_name}</div><div className="cd-entry-meta">{new Date(entry.occurred_at).toLocaleString('en-PK',{dateStyle:'medium',timeStyle:'short'})} · {entry.size} · {formatContractorMoney(entry.pieces)} pcs</div></div><div className="cd-row-actions"><strong className="cd-entry-total">PKR {formatContractorMoney(entry.total)}</strong>{onMenu&&<button className="cd-more" type="button" aria-label="Entry actions" onClick={()=>onMenu(entry)}>⋯</button>}</div></div><span className="cd-badge">Actual PKR {formatContractorMoney(entry.actual_rate_per_piece)} / piece</span>{entry.commission_type&&entry.commission_value!==null&&<span className="cd-badge" style={{marginLeft:6}}>Commission {entry.commission_type==='percentage'?`${formatContractorMoney(entry.commission_value)}%`: `PKR ${formatContractorMoney(entry.commission_value)}`} · {entry.commission_mode==='included'?'Minus':'Add'}</span>}</div>}

export function ContractorPersonalDashboard(){
 const {user}=useAuth(); const navigate=useNavigate(); const profileId=user?.id??'';
 const [entries,setEntries]=useState<Entry[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [newOpen,setNewOpen]=useState(false); const [editEntry,setEditEntry]=useState<Entry|null>(null); const [deleteEntry,setDeleteEntry]=useState<Entry|null>(null); const [saving,setSaving]=useState(false); const [viewEntry,setViewEntry]=useState<Entry|null>(null); const [detail,setDetail]=useState<{type:DetailType;period:{label:string;start:Date;end:Date;total:number;commission:number};entries:Entry[]}|null>(null); const [detailLoading,setDetailLoading]=useState(false); const [visibleCount,setVisibleCount]=useState(5); const [periodCursors,setPeriodCursors]=useState<Record<DetailType,number>>({daily:0,weekly:0,monthly:0,grand:0});
 const today=new Date(); today.setHours(0,0,0,0); const todayKey=dateKey(today);
 const displayName=(user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email?.split('@')[0]||'Contractor') as string;
 const totals=useMemo(()=>{const now=new Date();const dayS=new Date(now);dayS.setHours(0,0,0,0);const dayE=endOfDay(now);const weekS=startOfWeek(now);const weekE=new Date(weekS);weekE.setDate(weekE.getDate()+6);const monthS=startOfMonth(now);const monthE=endOfMonth(now);return {dayS,dayE,weekS,weekE,monthS,monthE}},[]);
 async function load(){if(!profileId)return;setLoading(true);setError('');const [{data:rows,error:rowsError},{data:sum,error:sumError}]=await Promise.all([supabase.from('contractor_work_entries').select('id,item_name,size,pieces,rate_per_piece,commission_type,commission_value,commission_mode,commission_per_piece,actual_rate_per_piece,total,occurred_at,special_note').eq('profile_id',profileId).order('occurred_at',{ascending:false}).limit(60),supabase.rpc('get_contractor_work_totals',{p_day_start:totals.dayS.toISOString(),p_day_end:totals.dayE.toISOString(),p_week_start:totals.weekS.toISOString(),p_week_end:totals.weekE.toISOString(),p_month_start:totals.monthS.toISOString(),p_month_end:totals.monthE.toISOString()})]);if(rowsError||sumError){setError(rowsError?.message||sumError?.message||'Unable to load contractor work.');}setEntries((rows??[]) as Entry[]);setLoading(false)}
 useEffect(()=>{void load()},[profileId]);
 const cards=[{type:'daily' as DetailType,label:'Today',value:0,icon:'◷'},{type:'weekly' as DetailType,label:'Weekly',value:0,icon:'▦'},{type:'monthly' as DetailType,label:'Monthly',value:0,icon:'◫'},{type:'grand' as DetailType,label:'Grand Total',value:entries.reduce((a,e)=>a+Number(e.total||0),0),icon:'◆'}];
 async function openDetail(type:DetailType,offset:number){if(!profileId)return;setDetailLoading(true);setVisibleCount(5);const now=new Date();let start:Date,end:Date,label:string;if(type==='daily'){start=new Date(now);start.setDate(start.getDate()+offset);start.setHours(0,0,0,0);end=endOfDay(start);label=start.toLocaleDateString('en-PK',{dateStyle:'full'});}else if(type==='weekly'){start=startOfWeek(now);start.setDate(start.getDate()+offset*7);end=new Date(start);end.setDate(end.getDate()+6);end=endOfDay(end);label=`${start.toLocaleDateString('en-PK',{dateStyle:'medium'})} — ${end.toLocaleDateString('en-PK',{dateStyle:'medium'})}`;}else if(type==='monthly'){start=startOfMonth(now);start.setMonth(start.getMonth()+offset);end=endOfMonth(start);label=start.toLocaleDateString('en-PK',{month:'long',year:'numeric'});}else{start=new Date(0);end=endOfDay(now);label='All recorded personal work';}const {data,error:loadError}=await supabase.from('contractor_work_entries').select('id,item_name,size,pieces,rate_per_piece,commission_type,commission_value,commission_mode,commission_per_piece,actual_rate_per_piece,total,occurred_at,special_note').eq('profile_id',profileId).gte('occurred_at',start.toISOString()).lte('occurred_at',end.toISOString()).order('occurred_at',{ascending:false}).limit(1000);if(loadError)setError(loadError.message);const list=(data??[]) as Entry[];const total=list.reduce((a,e)=>a+Number(e.total||0),0);const commission=list.reduce((a,e)=>a+Number(e.commission_per_piece||0)*Number(e.pieces||0),0);setDetail({type,period:{label,start,end,total,commission},entries:list});setDetailLoading(false)}
 function moveDetail(direction:number){if(!detail)return;const next=detail.type==='grand'?0:periodCursors[detail.type]+direction;if(detail.type==='daily'&&next>0)return;setPeriodCursors(p=>({...p,[detail.type]:next}));void openDetail(detail.type,next)}
 async function saveEntry(input:ContractorEntryInput){if(!profileId)return {error:new Error('Not authenticated')};setSaving(true);const {error:saveError}=await supabase.from('contractor_work_entries').insert({...input,profile_id:profileId});if(!saveError)setNewOpen(false);else setError(saveError.message);await load();setSaving(false);return {error:saveError}}
 async function saveEditedEntry(id:string,input:Partial<Entry>){if(!profileId)return {error:new Error('Not authenticated')};setSaving(true);const {error:saveError}=await supabase.from('contractor_work_entries').update(input).eq('id',id).eq('profile_id',profileId);if(saveError)setError(saveError.message);else setEditEntry(null);await load();setSaving(false);return {error:saveError}}
 async function confirmDelete(){if(!deleteEntry||!profileId)return;setSaving(true);const {error:deleteError}=await supabase.from('contractor_work_entries').delete().eq('id',deleteEntry.id).eq('profile_id',profileId);if(deleteError)setError(deleteError.message);else setDeleteEntry(null);await load();setSaving(false)}
 return <main className="contractor-dashboard"><section className="cd-hero"><div className="cd-kicker">Contractor Personal Dashboard</div><h1 className="cd-title">Welcome{displayName?`, ${displayName}`:''}</h1><p className="cd-sub">Your personal work overview — compact, real, and commission-aware.</p><div className="cd-actions"><button className="cd-btn" type="button" onClick={()=>navigate('/work/contractor?view=settings')}>Settings</button><button className="cd-btn cd-btn-primary" type="button" onClick={()=>setNewOpen(true)}>＋ New Entry</button></div></section>
 <ContractorEntryEditModal entry={editEntry} saving={saving} onClose={()=>setEditEntry(null)} onSave={saveEditedEntry}/>
 {newOpen&&<ContractorNewEntryModal open={newOpen} saving={saving} onClose={()=>setNewOpen(false)} onSave={saveEntry}/>}</main>;
}