import type { AiAttachment, AiGenerationOptions, AiMessage, AiProvider, AiProviderStatus, AiRoute, AiRoutingMode, AiResponse } from './contracts';
import { AiRoutingError } from './contracts';
import { validateVisionImages } from '../vision/imageValidator';
import { offlineAiTrace } from '../runtime/localAiDiagnostics';
const ROUTING_MODE_STORAGE_KEY = 'work-social-ai-routing-mode';
function readPersistedRoutingMode(): AiRoutingMode { if (typeof window === 'undefined') return 'auto'; try { const stored = window.localStorage.getItem(ROUTING_MODE_STORAGE_KEY); if (stored === 'auto' || stored === 'online' || stored === 'offline') return stored; } catch {} return 'auto'; }
let defaultRoutingMode: AiRoutingMode = readPersistedRoutingMode();
export function setDefaultAiRoutingMode(mode: AiRoutingMode): void { defaultRoutingMode = mode; if (typeof window === 'undefined') return; try { window.localStorage.setItem(ROUTING_MODE_STORAGE_KEY, mode); } catch {} }
export function getDefaultAiRoutingMode(): AiRoutingMode { return defaultRoutingMode; }
export class AiRouter {
 constructor(private readonly gemini: AiProvider, private readonly local: AiProvider) {}
 async route(mode: AiRoutingMode = defaultRoutingMode, attachments: AiAttachment[] = []): Promise<AiRoute> { await validateImagesBeforeRouting(attachments); offlineAiTrace('OFFLINE_MODE_CONFIRMED', { requestedMode: mode }); if (mode === 'online') return { provider: 'gemini', mode: 'online', reasonCode: 'ONLINE_EXPLICIT', reason: 'Online mode explicitly selects Gemini.' }; const localStatus = await this.getLocalRoutingStatus(attachments); offlineAiTrace('LOCAL_PROVIDER_SELECTED', { requestedMode: mode, localState: localStatus.state, localReasonCode: localStatus.reasonCode ?? null }); if (mode === 'offline') { if (localStatus.state !== 'ready') throw new AiRoutingError(localStatus.reasonCode ?? 'LOCAL_RUNTIME_UNAVAILABLE', 'offline', 'local', localStatus.reason ?? 'Local AI is unavailable in offline mode.'); return { provider: 'local', mode: 'offline', reasonCode: 'OFFLINE_EXPLICIT', reason: 'Offline mode explicitly selects the verified local provider.' }; } if (localStatus.state === 'ready') return { provider: 'local', mode: 'offline', reasonCode: 'AUTO_LOCAL_SELECTED', reason: 'Local AI is executable and all model, integrity, device, resource, and attachment requirements are satisfied.' }; return { provider: 'gemini', mode: 'online', reasonCode: 'AUTO_ONLINE_SELECTED', reason: localStatus.reason ?? 'Local AI is not currently eligible; Gemini is selected explicitly by AUTO policy.' }; }
 getProvider(preference: 'gemini' | 'local' = 'gemini'): AiProvider { return preference === 'local' ? this.local : this.gemini; }
 async getLocalStatus(attachments: AiAttachment[] = []): Promise<AiProviderStatus> { return this.getLocalRoutingStatus(attachments); }
 async sendMessage(messages: AiMessage[], attachments: AiAttachment[] = [], options?: AiGenerationOptions & { mode?: AiRoutingMode; provider?: 'gemini' | 'local' }): Promise<AiResponse> { const { mode, provider, ...generationOptions } = options ?? {}; const routingMode: AiRoutingMode = mode ?? (provider === 'local' ? 'offline' : provider === 'gemini' ? 'online' : defaultRoutingMode); const requestStartedAtMs = nowMs(); offlineAiTrace('OFFLINE_REQUEST_RECEIVED', { requestedMode: routingMode, providerHint: provider ?? null, startedAtMs: requestStartedAtMs }); const route = await this.route(routingMode, attachments); const selectedProvider = route.provider === 'local' ? this.local : this.gemini; if (routingMode === 'offline' && selectedProvider !== this.local) throw new AiRoutingError('LOCAL_RUNTIME_UNAVAILABLE', 'offline', 'local', 'Offline mode resolved to a non-local provider.'); offlineAiTrace('LOCAL_PROVIDER_SELECTED', { requestedMode: routingMode, selectedProvider: route.provider, routeMode: route.mode, reasonCode: route.reasonCode, requestToRouteMs: nowMs() - requestStartedAtMs }); const response = await selectedProvider.sendMessage(messages, attachments, { ...generationOptions, diagnosticRequestStartedAtMs: requestStartedAtMs }); if (routingMode === 'offline' && (response.provider !== 'local' || response.mode !== 'offline')) throw new AiRoutingError('OFFLINE_ROUTE_VIOLATION', 'offline', 'local', `Offline provider returned invalid provenance: provider=${response.provider}, mode=${response.mode}`); return response; }
 private async getLocalRoutingStatus(attachments: AiAttachment[]): Promise<AiProviderStatus> { const localWithRouting = this.local as AiProvider & { getRoutingStatus?: (attachments?: AiAttachment[]) => Promise<AiProviderStatus> }; if (typeof localWithRouting.getRoutingStatus !== 'function') return { state: 'unavailable', provider: 'local', mode: 'offline', reason: 'The local provider does not expose a verified routing-readiness check.', reasonCode: 'LOCAL_RUNTIME_UNAVAILABLE' }; return localWithRouting.getRoutingStatus(attachments); }
}
async function validateImagesBeforeRouting(attachments: AiAttachment[]): Promise<void> { const images = attachments.filter((attachment) => attachment.kind === 'image'); if (images.length > 0) await validateVisionImages(images); }
function nowMs(): number { return typeof performance !== 'undefined' && typeof performance.now === 'function' ? Math.round(performance.now()) : Date.now(); }
export type { AiRoutingMode, AiRoute, AiRoutingReasonCode } from './contracts';
