import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabase/client';
import { loadExpenseOverview } from '../data/expenseManagerOverview';
import { loadExpenseReports } from '../data/expenseManagerReports';
import { loadExpenseTransactionData } from '../data/expenseManagerTransactions';
import { getExpensePeriodBounds } from '../domain/overview';
import type { ExpenseOverviewData } from '../domain/overview';
import type { ExpenseReportsData } from '../domain/reports';
import type { ExpenseTransactionRecord } from '../domain/transactions';

function money(value: number, currency: string) { try { return new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(value); } catch { return `${currency} ${value.toFixed(2)}`; } }
function monthStart(date: Date) { return new Date(date.getFullYear(), date.getMonth(), 1); }
function dateOnly(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function recurringExpenses(transactions: ExpenseTransactionRecord[]) { const groups = new Map<string, ExpenseTransactionRecord[]>(); transactions.filter((item) => item.type === 'expense').forEach((item) => { const key = `${item.category_id ?? 'uncategorized'}|${item.amount.toFixed(2)}`; groups.set(key, [...(groups.get(key) ?? []), item]); }); return [...groups.values()].map((rows) => rows.sort((a, b) => a.date.localeCompare(b.date))).filter((rows) => rows.length >= 3).filter((rows) => rows.slice(1).every((row, index) => { const previous = new Date(`${rows[index].date}T12:00:00`); const current = new Date(`${row.date}T12:00:00`); const days = Math.round((current.getTime() - previous.getTime()) / 86400000); return days >= 20 && days <= 40; })).slice(0, 3); }

export function ExpenseIntelligencePanel() {
  const [overview, setOverview] = useState<ExpenseOverviewData | null>(null); const [reports, setReports] = useState<ExpenseReportsData | null>(null); const [transactions, setTransactions] = useState<ExpenseTransactionRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const bounds = useMemo(() => getExpensePeriodBounds(monthStart(new Date())), []);
  const historyStart = useMemo(() => { const date = new Date(); date.setDate(date.getDate() - 90); return dateOnly(date); }, []);
  const historyEnd = useMemo(() => dateOnly(new Date()), []);
  useEffect(() => { let active = true; const run = async () => { try { const { data, error: authError } = await supabase.auth.getUser(); if (authError || !data.user) throw authError ?? new Error('Signed-in user could not be resolved.'); const [nextOverview, nextReports, nextTransactions] = await Promise.all([loadExpenseOverview(bounds.start, bounds.end), loadExpenseReports(bounds.start, bounds.end), loadExpenseTransactionData(data.user.id, { fromDate: historyStart, toDate: historyEnd })]); if (!active) return; setOverview(nextOverview); setReports(nextReports); setTransactions(nextTransactions.transactions); } catch (cause) { if (active) setError(cause instanceof Error ? cause.message : 'Unable to calculate financial insights.'); } finally { if (active) setLoading(false); } }; void run(); return () => { active = false; }; }, [bounds.end, bounds.start, historyEnd, historyStart]);
  const recurring = useMemo(() => recurringExpenses(transactions), [transactions]);
  if (loading) return <section className="expense-intelligence" aria-live="polite"><p>Calculating financial insights from persisted records…</p></section>;
  if (error) return <section className="expense-intelligence" role="alert"><strong>Insights unavailable</strong><p>{error}</p></section>;
  if (!overview || !reports || !overview.has_financial_records) return null;
  const insights: string[] = []; const primaryCurrency = reports.summary.length === 1 ? reports.summary[0].currency : overview.period_currencies.length === 1 ? overview.period_currencies[0].currency : null;
  if (primaryCurrency && overview.income > overview.expenses && overview.income > 0) insights.push(`You are cash-flow positive this month by ${money(overview.income - overview.expenses, primaryCurrency)}.`);
  if (primaryCurrency && overview.expenses > overview.income && overview.expenses > 0) insights.push(`Expenses exceed income this month by ${money(overview.expenses - overview.income, primaryCurrency)}.`);
  const top = overview.top_categories[0]; if (top) insights.push(`${top.name} is your largest spending category at ${money(top.amount, top.currency)}.`);
  const rising = reports.category_trends.find((item) => item.previous_amount > 0 && item.current_amount >= item.previous_amount * 1.2); if (rising) insights.push(`${rising.name} spending is up ${Math.round(((rising.current_amount - rising.previous_amount) / rising.previous_amount) * 100)}% versus the previous month.`);
  const budget = reports.budgets.find((item) => item.budget_amount > 0 && item.spent >= item.budget_amount * 0.8); if (budget) insights.push(`${budget.category_name} is ${budget.spent >= budget.budget_amount ? 'over' : 'approaching'} its budget limit.`);
  if (recurring.length) insights.push(`${recurring.length} recurring expense pattern${recurring.length === 1 ? '' : 's'} detected from repeated persisted transactions.`);
  return <section className="expense-intelligence" aria-labelledby="expense-intelligence-title"><style>{`.expense-intelligence{width:min(1120px,100%);margin:14px auto 0;padding:16px;border:1px solid rgba(37,99,235,.12);border-radius:21px;background:linear-gradient(145deg,rgba(239,246,255,.8),rgba(255,255,255,.92));box-shadow:0 12px 28px rgba(15,23,42,.05)}.expense-intelligence__eyebrow{color:#2563eb;font-size:8px;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.expense-intelligence h2{margin:3px 0 0;color:#172033;font-size:16px;font-weight:950}.expense-intelligence p{margin:5px 0 0;color:#64748b;font-size:10px;line-height:1.5;font-weight:650}.expense-intelligence__list{display:grid;gap:7px;margin-top:12px}.expense-intelligence__item{padding:10px 11px;border:1px solid rgba(148,163,184,.13);border-radius:13px;background:rgba(255,255,255,.78);color:#334155;font-size:10px;font-weight:750;line-height:1.45}.expense-intelligence__empty{margin-top:11px;padding:11px;border:1px dashed rgba(148,163,184,.25);border-radius:13px;color:#64748b;font-size:10px;font-weight:700}@media(max-width:600px){.expense-intelligence{padding:13px}}`}</style><span className="expense-intelligence__eyebrow">Deterministic intelligence</span><h2 id="expense-intelligence-title">Financial insights</h2><p>Derived only from persisted transactions, budgets, accounts, and report aggregates. No invented values or external AI service.</p>{insights.length ? <div className="expense-intelligence__list">{insights.map((insight) => <div className="expense-intelligence__item" key={insight}>• {insight}</div>)}</div> : <div className="expense-intelligence__empty">No significant trend or budget signal was detected for the current period.</div>}</section>;
}
