import { createClient } from "npm:@supabase/supabase-js@2";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS"};
const MODEL="gemini-3.5-flash-lite",TZ="Asia/Karachi",MAX_HISTORY=8,MAX_ROUNDS=4;
const json=(s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:{...H,"Content-Type":"application/json"}});
class E extends Error{constructor(public status:number,public code:string,m:string){super(m)}}
function client(req:Request){const a=req.headers.get("Authorization");if(!a?.startsWith("Bearer "))throw new E(401,"AUTHORIZATION_MISSING","Missing user authorization.");return createClient(Deno.env.get("SUPABASE_URL")!,JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")??"{}").default,{global:{headers:{Authorization:a}},auth:{persistSession:false,autoRefreshToken:false}})}
async function auth(req:Request){const a=req.headers.get("Authorization");const c=client(req),{data,error}=await c.auth.getUser(a!.slice(7));if(error||!data.user)throw new E(401,"AUTHENTICATION_FAILED","Your Work Social session is not valid.");return{c,u:data.user}}
async function worker(c:any,u:string){const{data,error}=await c.from("worker_profiles").select("id").eq("profile_id",u).maybeSingle();if(error)throw new E(500,"DATABASE_ERROR",error.message);if(!data)throw new E(404,"WORK_IDENTITY_UNAVAILABLE","Your Work Identity is not set up.");return data.id}
const SYSTEM=`You are Work Social AI — the user's intelligent operating assistant for the complete Work Social 4-in-1 product. You understand and guide four domains: (1) Social Media: Home/feed, posts, video, profile, friends, friend requests, Inbox/private messaging, activity and notifications; (2) Work Platform: Work Entries, item, size, pieces/quantity, rate, total, notes, work reports, and Work Finance including payment/advance received; (3) Personal Diary: notes, journal, todo, ideas and events; (4) Finance Manager: Overview, Transactions, Accounts, Categories/Subcategories, Budgets and Reports. Explain what a module is, how to use it, and practical benefits. You are also an action assistant: when a user wants something recorded, identify the correct domain and workflow, collect all required information, then prepare a real action for confirmation. Never invent records, IDs, balances, categories or capabilities. Never say an action was saved until confirmation execution succeeds. If a request is ambiguous between Work, Work Finance, Finance Manager or Personal Diary, ask which destination. Do not ask for information that is already known. Ask one focused missing question at a time. For Work Entry creation required fields are item name, quantity/pieces and rate; size and note are optional; total=quantity×rate. For Work Finance received records required fields are type (payment or advance), amount and date/time. For Finance Manager expense/income required fields are type, amount, account, category and date; note is optional. For transfer required fields are amount, from account, to account and date. For Diary creation required field is content; title/type/date are optional. For social read requests use read tools. Use concise Roman Urdu/Hinglish naturally when the user does. If the user gives incomplete data, ask exactly what is missing. If the user says 'add'/'save'/'record'/'likh do'/'dal do', treat it as an action request, not merely an explanation. Persistent writes always require confirmation.`;
const tools=[
{name:"get_my_profile",description:"Read authenticated user's real social profile.",parametersJsonSchema:{type:"object",properties:{},additionalProperties:false}},
{name:"get_my_posts",description:"Read recent real posts by authenticated user.",parametersJsonSchema:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:10}},required:["limit"],additionalProperties:false}},
{name:"get_notifications",description:"Read recent real notifications.",parametersJsonSchema:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:20}},required:["limit"],additionalProperties:false}},
{name:"get_work_entries",description:"Read real active Work Entries.",parametersJsonSchema:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:50},item_name:{type:["string","null"]},size:{type:["string","null"]}},required:["limit","item_name","size"],additionalProperties:false}},
{name:"get_work_report",description:"Read real Work totals and entries for a period.",parametersJsonSchema:{type:"object",properties:{from_date:{type:"string"},to_date:{type:"string"}},required:["from_date","to_date"],additionalProperties:false}},
{name:"get_diary_entries",description:"Read real Personal Diary entries.",parametersJsonSchema:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:30}},required:["limit"],additionalProperties:false}},
{name:"get_work_finance",description:"Read real Work Finance received payment/advance records and totals.",parametersJsonSchema:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:50}},required:["limit"],additionalProperties:false}},
{name:"get_finance_overview",description:"Read real Finance Manager accounts, categories and recent transactions for this user.",parametersJsonSchema:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:30}},required:["limit"],additionalProperties:false}},
{name:"create_work_entry",description:"Prepare a real Work Entry. Required item_name, quantity, rate. Ask for missing fields before calling this tool.",parametersJsonSchema:{type:"object",properties:{item_name:{type:"string"},size:{type:["string","null"]},quantity:{type:"number",exclusiveMinimum:0},rate:{type:"number",minimum:0},special_note:{type:["string","null"]},occurred_at_iso:{type:["string","null"]}},required:["item_name","size","quantity","rate","special_note","occurred_at_iso"],additionalProperties:false}},
{name:"create_diary_entry",description:"Prepare a real Personal Diary entry. Content is required.",parametersJsonSchema:{type:"object",properties:{entry_type:{type:"string",enum:["note","todo","idea","journal","anything","event"]},title:{type:["string","null"]},content:{type:"string",minLength:1},date_iso:{type:["string","null"]}},required:["entry_type","title","content","date_iso"],additionalProperties:false}},
{name:"create_work_finance_received",description:"Prepare a real Work Finance received record. Use only for work-related payment/advance received. Required entry_type and amount.",parametersJsonSchema:{type:"object",properties:{entry_type:{type:"string",enum:["payment","advance"]},amount:{type:"number",exclusiveMinimum:0},received_at_iso:{type:["string","null"]}},required:["entry_type","amount","received_at_iso"],additionalProperties:false}},
{name:"create_finance_transaction",description:"Prepare a real Finance Manager transaction. Expense/income need amount, account_id, category_id, date. Transfer needs amount, from_account_id, to_account_id, date. Use get_finance_overview first when IDs are unknown.",parametersJsonSchema:{type:"object",properties:{type:{type:"string",enum:["expense","income","transfer"]},amount:{type:"number",exclusiveMinimum:0},account_id:{type:["string","null"]},category_id:{type:["string","null"]},from_account_id:{type:["string","null"]},to_account_id:{type:["string","null"]},date:{type:"string"},note:{type:["string","null"]}},required:["type","amount","account_id","category_id","from_account_id","to_account_id","date","note"],additionalProperties:false}}
];
async function pending(c:any,u:string,conv:string,tool:string,args:any,summary:string){const{data,error}=await c.from("ai_pending_actions").insert({user_id:u,conversation_id:conv,tool_name:tool,arguments:args,display_summary:summary,status:"pending",expires_at:new Date(Date.now()+600000).toISOString()}).select("id,display_summary,expires_at").single();if(error)throw new E(500,"DATABASE_ERROR",error.message);return{confirmation_required:true,id:data.id,action_id:data.id,confirmation_id:data.id,display_summary:data.display_summary,expires_at:data.expires_at}}
const safe=(v:any)=>String(v??"").trim();
async function tool(c:any,u:string,conv:string,name:string,a:any){const w=await worker(c,u);if(name==="get_my_profile"){const{data,error}=await c.from("profiles").select("id,username,display_name,bio,avatar_url").eq("id",u).single();if(error)throw new E(500,"DATABASE_ERROR",error.message);return data}
if(name==="get_my_posts"){const{data,error}=await c.from("posts").select("id,content,privacy,created_at,location_name").eq("profile_id",u).order("created_at",{ascending:false}).limit(Number(a.limit)||10);if(error)throw new E(500,"DATABASE_ERROR",error.message);return data??[]}
if(name==="get_notifications"){const{data,error}=await c.from("notifications").select("id,type,sender_id,post_id,comment_id,is_read,created_at,metadata").eq("receiver_id",u).order("created_at",{ascending:false}).limit(Number(a.limit)||10);if(error)throw new E(500,"DATABASE_ERROR",error.message);return data??[]}
if(name==="get_work_entries"){let q=c.from("work_entries").select("id,item_name,size,quantity,rate,total,special_note,occurred_at").eq("worker_profile_id",w).eq("work_context","my_work").eq("lifecycle_state","active").order("occurred_at",{ascending:false}).limit(Number(a.limit)||20);if(a.item_name)q=q.ilike("item_name",`%${safe(a.item_name)}%`);const{data,error}=await q;if(error)throw new E(500,"DATABASE_ERROR",error.message);return data??[]}
if(name==="get_work_report"){const{data,error}=await c.from("work_entries").select("item_name,quantity,total,occurred_at").eq("worker_profile_id",w).eq("work_context","my_work").eq("lifecycle_state","active").gte("occurred_at",`${a.from_date}T00:00:00+05:00`).lt("occurred_at",`${a.to_date}T00:00:00+05:00`).limit(5000);if(error)throw new E(500,"DATABASE_ERROR",error.message);let pieces=0,value=0;for(const x of data??[]){pieces+=Number(x.quantity)||0;value+=Number(x.total)||0}return{from:a.from_date,to:a.to_date,entry_count:(data??[]).length,total_pieces:pieces,recorded_work_value:value,entries:data??[]}}
if(name==="get_diary_entries"){const{data,error}=await c.from("worker_diary_entries").select("id,entry_type,title,content,completed,created_at,event_start_at,event_end_at,event_timezone").eq("worker_profile_id",w).order("updated_at",{ascending:false}).limit(Number(a.limit)||20);if(error)throw new E(500,"DATABASE_ERROR",error.message);return data??[]}
if(name==="get_work_finance"){const{data,error}=await c.from("worker_finance_received").select("id,entry_type,amount,received_at,created_at").eq("worker_profile_id",w).is("deleted_at",null).order("received_at",{ascending:false}).limit(Number(a.limit)||30);if(error)throw new E(500,"DATABASE_ERROR",error.message);let total=0;for(const x of data??[])total+=Number(x.amount)||0;return{total_received:total,records:data??[]}}
if(name==="get_finance_overview"){const l=Math.min(Math.max(Number(a.limit)||20,1),30);const [ac,ca,tr]=await Promise.all([c.from("expense_accounts").select("id,name,type,currency,opening_balance").eq("user_id",u).order("created_at"),c.from("expense_categories").select("id,name,type,is_archived").eq("user_id",u).eq("is_archived",false).order("name"),c.from("expense_transactions").select("id,type,amount,account_id,category_id,from_account_id,to_account_id,date,note").eq("user_id",u).order("date",{ascending:false}).limit(l)]);if(ac.error)throw new E(500,"DATABASE_ERROR",ac.error.message);if(ca.error)throw new E(500,"DATABASE_ERROR",ca.error.message);if(tr.error)throw new E(500,"DATABASE_ERROR",tr.error.message);return{accounts:ac.data??[],categories:ca.data??[],recent_transactions:tr.data??[]}}
if(name==="create_work_entry"){if(Number(a.quantity)<=0||Number(a.rate)<0)throw new E(400,"INVALID_WORK_VALUE","Quantity and rate must be valid.");return pending(c,u,conv,name,{worker_profile_id:w,item_name:safe(a.item_name),size:a.size?safe(a.size):null,quantity:Number(a.quantity),rate:Number(a.rate),special_note:a.special_note?safe(a.special_note):null,occurred_at_iso:a.occurred_at_iso||new Date().toISOString()},`Work Entry\n${safe(a.item_name)}${a.size?` · Size ${safe(a.size)}`:""}\n${a.quantity} pieces × ${a.rate} = ${Number(a.quantity)*Number(a.rate)}`)}
if(name==="create_diary_entry")return pending(c,u,conv,name,{worker_profile_id:w,entry_type:a.entry_type,title:a.title?safe(a.title):null,content:safe(a.content),date_iso:a.date_iso||null},`Personal Diary\n${a.title?safe(a.title)+"\n":""}${safe(a.content)}`);
if(name==="create_work_finance_received")return pending(c,u,conv,name,{worker_profile_id:w,entry_type:a.entry_type,amount:Number(a.amount),received_at_iso:a.received_at_iso||new Date().toISOString()},`Work Finance · ${a.entry_type}\nAmount: PKR ${Number(a.amount).toLocaleString()}`);
if(name==="create_finance_transaction"){const t=a.type,amount=Number(a.amount);if(t!=="transfer"&&(!a.account_id||!a.category_id))throw new E(400,"FINANCE_FIELDS_REQUIRED","Account and category are required.");if(t==="transfer"&&(!a.from_account_id||!a.to_account_id||a.from_account_id===a.to_account_id))throw new E(400,"TRANSFER_FIELDS_REQUIRED","From and to accounts are required and must differ.");return pending(c,u,conv,name,{user_id:u,type:t,amount,account_id:a.account_id||null,category_id:a.category_id||null,from_account_id:a.from_account_id||null,to_account_id:a.to_account_id||null,date:safe(a.date),note:a.note?safe(a.note):null},`Finance Manager · ${t}\nAmount: PKR ${amount.toLocaleString()}\nDate: ${safe(a.date)}`)}
throw new E(400,"UNREGISTERED_TOOL","Tool is not registered.")}
async function execute(c:any,u:string,id:string){const{data:a,error}=await c.from("ai_pending_actions").select("id,tool_name,arguments,status,expires_at").eq("id",id).eq("user_id",u).single();if(error||!a)throw new E(404,"PENDING_ACTION_NOT_FOUND","Action not found.");if(a.status!=="pending")throw new E(409,"ACTION_NOT_PENDING",`Action is already ${a.status}.`);if(new Date(a.expires_at)<=new Date())throw new E(409,"CONFIRMATION_EXPIRED","Confirmation expired.");const x=a.arguments as any;if(a.tool_name==="create_work_entry"){const{data,error}=await c.from("work_entries").insert({worker_profile_id:x.worker_profile_id,work_context:"my_work",item_name:x.item_name,size:x.size,quantity:x.quantity,rate:x.rate,special_note:x.special_note,occurred_at:x.occurred_at_iso}).select("id,item_name,size,quantity,rate,total,special_note,occurred_at").single();if(error)throw new E(500,"DATABASE_ERROR",error.message);await c.from("ai_pending_actions").update({status:"confirmed"}).eq("id",id).eq("user_id",u);return{success:true,work_entry:data}}
if(a.tool_name==="create_diary_entry"){const{data,error}=await c.from("worker_diary_entries").insert({worker_profile_id:x.worker_profile_id,entry_type:x.entry_type,title:x.title,content:x.content,completed:x.entry_type==="todo"?false:null,event_timezone:TZ}).select("id,entry_type,title,content,completed,created_at").single();if(error)throw new E(500,"DATABASE_ERROR",error.message);await c.from("ai_pending_actions").update({status:"confirmed"}).eq("id",id).eq("user_id",u);return{success:true,entry:data}}
if(a.tool_name==="create_work_finance_received"){const{data,error}=await c.from("worker_finance_received").insert({worker_profile_id:x.worker_profile_id,entry_type:x.entry_type,amount:x.amount,received_at:x.received_at_iso}).select("id,entry_type,amount,received_at").single();if(error)throw new E(500,"DATABASE_ERROR",error.message);await c.from("ai_pending_actions").update({status:"confirmed"}).eq("id",id).eq("user_id",u);return{success:true,work_finance:data}}
if(a.tool_name==="create_finance_transaction"){const{data,error}=await c.from("expense_transactions").insert({user_id:u,type:x.type,amount:x.amount,account_id:x.account_id,category_id:x.category_id,from_account_id:x.from_account_id,to_account_id:x.to_account_id,date:x.date,note:x.note}).select("id,type,amount,account_id,category_id,from_account_id,to_account_id,date,note").single();if(error)throw new E(500,"DATABASE_ERROR",error.message);await c.from("ai_pending_actions").update({status:"confirmed"}).eq("id",id).eq("user_id",u);return{success:true,transaction:data}}
throw new E(400,"UNSUPPORTED_PENDING_ACTION","Unsupported action.")}
async function callGemini(contents:any){const k=Deno.env.get("GEMINI_API_KEY");if(!k)throw new E(500,"GEMINI_CONFIG_ERROR","Gemini configuration is unavailable.");const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${encodeURIComponent(k)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents,systemInstruction:{parts:[{text:SYSTEM}]},tools:[{functionDeclarations:tools}],generationConfig:{thinkingConfig:{thinkingLevel:"MINIMAL"},maxOutputTokens:512}})});const p=await r.json();if(!r.ok)throw new E(r.status===429?429:502,"GEMINI_ERROR",p?.error?.message||`Gemini HTTP ${r.status}`);return p}
const parts=(r:any)=>r?.candidates?.[0]?.content?.parts??[],calls=(r:any)=>parts(r).filter((p:any)=>p.functionCall),text=(r:any)=>parts(r).filter((p:any)=>typeof p.text==="string"&&!p.thought).map((p:any)=>p.text).join("\n").trim();
async function chat(req:Request){const{c,u}=await auth(req),b=await req.json(),message=String(b.message??"").trim();if(!message||message.length>8000)return json(400,{code:"INVALID_MESSAGE",error:"Message must contain 1-8000 characters."});let conv=typeof b.conversation_id==="string"?b.conversation_id:null;if(!conv){const{data,error}=await c.from("ai_conversations").insert({user_id:u.id,title:message.slice(0,80),status:"active"}).select("id").single();if(error)throw new E(500,"DATABASE_ERROR",error.message);conv=data.id}const{data:h,error:he}=await c.from("ai_messages").select("role,content").eq("conversation_id",conv).eq("user_id",u.id).order("created_at",{ascending:false}).limit(MAX_HISTORY);if(he)throw new E(500,"DATABASE_ERROR",he.message);const history=(h??[]).reverse().map((x:any)=>({role:x.role==="assistant"?"model":"user",parts:[{text:String(x.content).slice(0,2500)}]}));await c.from("ai_messages").insert({conversation_id:conv,user_id:u.id,role:"user",content:message,metadata:{smart_assistant:true}});let r=await callGemini([...history,{role:"user",parts:[{text:message}]}]);const pendingActions:any[]=[];for(let round=0;round<MAX_ROUNDS;round++){const cs=calls(r);if(!cs.length)break;const responses:any[]=[];for(const call of cs){let result:any,status="executed";try{result=await tool(c,u.id,conv,call.functionCall.name,call.functionCall.args??{});if(result.confirmation_required){status="awaiting_confirmation";pendingActions.push(result)}}catch(e){status="failed";result={error:e instanceof Error?e.message:"Tool failed."}}responses.push({functionResponse:{name:call.functionCall.name,response:{result},...(call.functionCall.id?{id:call.functionCall.id}:{})}});await c.from("ai_tool_calls").insert({user_id:u.id,conversation_id:conv,tool_name:call.functionCall.name,arguments:call.functionCall.args??{},result,status,completed_at:new Date().toISOString()})}const mc=r?.candidates?.[0]?.content;if(!mc)break;r=await callGemini([...history,{role:"user",parts:[{text:message}]},mc,{role:"user",parts:responses}])}const msg=text(r)||"Main samajh gaya. Thora aur detail bata dein.";await c.from("ai_messages").insert({conversation_id:conv,user_id:u.id,role:"assistant",content:msg,metadata:{smart_assistant:true,pending_actions:pendingActions}});await c.from("ai_conversations").update({updated_at:new Date().toISOString()}).eq("id",conv).eq("user_id",u.id);return json(200,{conversation_id:conv,message:msg,pending_actions:pendingActions})}
async function confirm(req:Request){const{c,u}=await auth(req),b=await req.json();return json(200,await execute(c,u.id,String(b.action_id??b.confirmation_id??b.id??"")))}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{const b=await req.clone().json();return b?.action==="confirm"?await confirm(req):await chat(req)}catch(e){if(e instanceof E)return json(e.status,{code:e.code,error:e.message});console.error(e);return json(500,{code:"UNEXPECTED_ERROR",error:"AI request failed."})}});