import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { supabase } from '../../lib/supabase/client';

type Profile = { id: string; display_name: string | null; avatar_url: string | null };
type Signal = { callId: string; from: string; to: string; kind: 'audio' | 'video'; type: 'offer' | 'answer' | 'ice' | 'hangup' | 'reject'; sdp?: RTCSessionDescriptionInit; candidate?: RTCIceCandidateInit };
const rtcConfig: RTCConfiguration = { iceServers: [{ urls: 'stun:stun.l.google.com:19302' }] };
const PhoneIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.12 5.2 2 2 0 0 1 4.11 3h3a2 2 0 0 1 2 1.72c.12.9.33 1.78.62 2.63a2 2 0 0 1-.45 2.11L8 10.73a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.85.29 1.73.5 2.63.62A2 2 0 0 1 22 16.92Z" /></svg>;
const VideoIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m16 13 5 3V8l-5 3V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-5Z" /></svg>;

export function InboxCallControls({ profileId }: { profileId: string }) {
  const [conversationId, setConversationId] = useState<string | null>(() => new URLSearchParams(window.location.search).get('conversation'));
  const [peer, setPeer] = useState<Profile | null>(null), [online, setOnline] = useState(false);
  const [call, setCall] = useState<{ id: string; kind: 'audio' | 'video'; incoming: boolean } | null>(null), [connected, setConnected] = useState(false), [muted, setMuted] = useState(false), [cameraOff, setCameraOff] = useState(false);
  const [header, setHeader] = useState<HTMLElement | null>(null), [error, setError] = useState<string | null>(null);
  const channelRef = useRef<ReturnType<typeof supabase.channel> | null>(null), pcRef = useRef<RTCPeerConnection | null>(null), localRef = useRef<MediaStream | null>(null), remoteRef = useRef<MediaStream | null>(null), localVideo = useRef<HTMLVideoElement | null>(null), remoteVideo = useRef<HTMLVideoElement | null>(null), pendingIce = useRef<RTCIceCandidateInit[]>([]), callRef = useRef(call);
  useEffect(() => { callRef.current = call; }, [call]);
  useEffect(() => { const update = () => { setConversationId(new URLSearchParams(window.location.search).get('conversation')); setHeader(document.querySelector('.premium-chat-page section > header, .premium-chat-header, .chat-header')); }; update(); const observer = new MutationObserver(update); observer.observe(document.body, { childList: true, subtree: true }); window.addEventListener('popstate', update); return () => { observer.disconnect(); window.removeEventListener('popstate', update); }; }, []);
  useEffect(() => { let cancelled = false; const loadPeer = async () => { if (!conversationId) { setPeer(null); setOnline(false); return; } const { data: members } = await supabase.from('conversation_members').select('profile_id').eq('conversation_id', conversationId).neq('profile_id', profileId).limit(1); if (cancelled || !members?.[0]?.profile_id) { setPeer(null); return; } const { data } = await supabase.from('profiles').select('id,display_name,avatar_url').eq('id', members[0].profile_id).maybeSingle(); if (!cancelled) setPeer((data ?? null) as Profile | null); }; void loadPeer(); return () => { cancelled = true; }; }, [conversationId, profileId]);
  useEffect(() => { if (!conversationId || !peer) return; const channel = supabase.channel(`work-social-call:${conversationId}`, { config: { private: true, presence: { key: profileId } } }); channel.on('presence', { event: 'sync' }, () => { const state = channel.presenceState<{ userId?: string }>(); setOnline(Object.values(state).flat().some((x: any) => x.userId === peer.id)); }); channel.on('broadcast', { event: 'signal' }, ({ payload }) => { void handleSignal(payload as Signal); }); channel.subscribe(async status => { if (status === 'SUBSCRIBED') await channel.track({ userId: profileId, online_at: new Date().toISOString() }); }); channelRef.current = channel; return () => { channelRef.current = null; void supabase.removeChannel(channel); }; }, [conversationId, peer?.id, profileId]);
  const send = async (signal: Signal) => { if (channelRef.current) await channelRef.current.send({ type: 'broadcast', event: 'signal', payload: signal }); };
  const cleanup = () => { pcRef.current?.close(); pcRef.current = null; localRef.current?.getTracks().forEach(t => t.stop()); localRef.current = null; remoteRef.current?.getTracks().forEach(t => t.stop()); remoteRef.current = null; if (localVideo.current) localVideo.current.srcObject = null; if (remoteVideo.current) remoteVideo.current.srcObject = null; pendingIce.current = []; setCall(null); setConnected(false); setMuted(false); setCameraOff(false); };
  const setupPeer = async (kind: 'audio' | 'video', initiator: boolean, callId: string) => { if (!peer) throw new Error('Contact unavailable.'); const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: kind === 'video' }); localRef.current = stream; if (localVideo.current) { localVideo.current.srcObject = stream; localVideo.current.muted = true; } const pc = new RTCPeerConnection(rtcConfig); pcRef.current = pc; remoteRef.current = new MediaStream(); if (remoteVideo.current) remoteVideo.current.srcObject = remoteRef.current; stream.getTracks().forEach(track => pc.addTrack(track, stream)); pc.ontrack = e => { e.streams[0]?.getTracks().forEach(track => remoteRef.current?.addTrack(track)); setConnected(true); }; pc.onicecandidate = e => { if (e.candidate) void send({ callId, from: profileId, to: peer.id, kind, type: 'ice', candidate: e.candidate.toJSON() }); }; pc.onconnectionstatechange = () => { if (pc.connectionState === 'connected') setConnected(true); if (['failed','closed','disconnected'].includes(pc.connectionState)) cleanup(); }; if (initiator) { const offer = await pc.createOffer(); await pc.setLocalDescription(offer); await send({ callId, from: profileId, to: peer.id, kind, type: 'offer', sdp: offer }); } };
  const handleSignal = async (signal: Signal) => { if (!peer || signal.to !== profileId || signal.from !== peer.id) return; try { if (signal.type === 'hangup' || signal.type === 'reject') { cleanup(); return; } if (signal.type === 'offer') { if (callRef.current) return; setCall({ id: signal.callId, kind: signal.kind, incoming: true }); const accept = window.confirm(`${peer.display_name || 'Contact'} is calling you. Accept ${signal.kind} call?`); if (!accept) { await send({ ...signal, from: profileId, to: peer.id, type: 'reject' }); cleanup(); return; } setCall({ id: signal.callId, kind: signal.kind, incoming: false }); await setupPeer(signal.kind, false, signal.callId); const pc = pcRef.current; if (!pc || !signal.sdp) return; await pc.setRemoteDescription(signal.sdp); for (const c of pendingIce.current.splice(0)) await pc.addIceCandidate(c); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); await send({ callId: signal.callId, from: profileId, to: peer.id, kind: signal.kind, type: 'answer', sdp: answer }); } else if (signal.type === 'answer' && pcRef.current && signal.sdp) { await pcRef.current.setRemoteDescription(signal.sdp); for (const c of pendingIce.current.splice(0)) await pcRef.current.addIceCandidate(c); } else if (signal.type === 'ice' && signal.candidate) { if (pcRef.current?.remoteDescription) await pcRef.current.addIceCandidate(signal.candidate); else pendingIce.current.push(signal.candidate); } } catch (e) { setError(e instanceof Error ? e.message : 'Call setup failed.'); cleanup(); } };
  const startCall = async (kind: 'audio' | 'video') => { if (!peer || !conversationId || call) return; try { const callId = crypto.randomUUID(); setError(null); setCall({ id: callId, kind, incoming: false }); await setupPeer(kind, true, callId); } catch (e) { setError(e instanceof Error ? e.message : 'Microphone/camera permission was denied.'); cleanup(); } };
  const hangup = async () => { if (call && peer) await send({ callId: call.id, from: profileId, to: peer.id, kind: call.kind, type: 'hangup' }); cleanup(); };
  const toggleMute = () => { const track = localRef.current?.getAudioTracks()[0]; if (!track) return; track.enabled = !track.enabled; setMuted(!track.enabled); };
  const toggleCamera = () => { const track = localRef.current?.getVideoTracks()[0]; if (!track) return; track.enabled = !track.enabled; setCameraOff(!track.enabled); };
  const title = peer?.display_name || 'Contact';
  const controls = useMemo(() => header && peer && conversationId ? createPortal(<div className="inbox-call-actions" data-inbox-popover><span className={`call-presence ${online ? 'online' : ''}`} title={online ? 'Online' : 'Offline'} /><span className="call-presence-label">{online ? 'Online' : 'Offline'}</span><button type="button" aria-label={`Voice call ${title}`} title="Voice call" onClick={() => void startCall('audio')} disabled={!!call}><PhoneIcon /></button><button type="button" aria-label={`Video call ${title}`} title="Video call" onClick={() => void startCall('video')} disabled={!!call}><VideoIcon /></button></div>, header) : null, [header, peer, conversationId, online, call, title]);
  return <>{controls}<style>{`.inbox-call-actions{margin-left:auto;display:flex;align-items:center;gap:8px}.inbox-call-actions button{width:42px;height:42px;display:grid;place-items:center;border:1px solid rgba(99,102,241,.16);border-radius:14px;background:rgba(255,255,255,.94);color:#3730a3;cursor:pointer;box-shadow:0 6px 18px rgba(15,23,42,.08);transition:transform .16s ease,box-shadow .16s ease,background .16s ease}.inbox-call-actions button:hover{transform:translateY(-1px);background:#fff;box-shadow:0 9px 24px rgba(15,23,42,.13)}.inbox-call-actions button:active{transform:scale(.95)}.inbox-call-actions button:disabled{opacity:.5;cursor:not-allowed}.inbox-call-actions button:focus-visible{outline:3px solid rgba(99,102,241,.25);outline-offset:2px}.inbox-call-actions svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}.call-presence{width:8px;height:8px;border-radius:50%;background:#94a3b8}.call-presence.online{background:#22c55e;box-shadow:0 0 0 3px rgba(34,197,94,.13),0 0 10px rgba(34,197,94,.35)}.call-presence-label{font-size:11px;font-weight:800;color:#64748b}`}</style>{call && <div className="inbox-call-stage" role="dialog" aria-label={`${call.kind} call with ${title}`}><div className="inbox-call-card"><div className="inbox-call-videos">{call.kind === 'video' ? <><video ref={remoteVideo} autoPlay playsInline /><video ref={localVideo} className="inbox-call-local" autoPlay playsInline muted /></> : <div style={{height:'100%',display:'grid',placeItems:'center'}}><PhoneIcon /></div>}</div><div className="inbox-call-info"><div><div className="inbox-call-name">{title}</div><div className="inbox-call-status">{connected ? 'Connected' : call.incoming ? 'Connecting…' : 'Calling…'} · {call.kind === 'video' ? 'Video' : 'Audio'}</div></div><div className="inbox-call-buttons"><button type="button" onClick={toggleMute} aria-label={muted ? 'Unmute' : 'Mute'}>{muted ? 'Unmute' : 'Mute'}</button>{call.kind === 'video' && <button type="button" onClick={toggleCamera} aria-label={cameraOff ? 'Turn camera on' : 'Turn camera off'}>{cameraOff ? 'Camera on' : 'Camera off'}</button>}<button type="button" className="end" onClick={() => void hangup()} aria-label="End call">End</button></div></div>{error && <div className="inbox-call-error">{error}</div>}</div></div>}</>;
}
