import { PRIMARY_LOCAL_TEXT_MODEL } from './primaryLocalTextModel';
import { ModelManager } from './modelManager';
import { InMemoryModelRegistry } from './modelRegistry';
import { sha256Hex } from './sha256';
import type { AiModel, DeviceCapabilityProvider, ModelStorage } from './modelContracts';
import type { DeviceCapability } from '../device/deviceCapability';

const GIB = 1024 ** 3;
const capability = (overrides: Partial<DeviceCapability> = {}): DeviceCapability => ({
  supported: true, tier: 'STANDARD', availableRam: 5 * GIB, totalRam: 6 * GIB, cpuCores: 8,
  architecture: 'arm64-v8a', androidVersion: '35', availableStorage: 10 * GIB,
  thermalState: 'nominal', batteryLevel: 1, isCharging: true, reason: null, limitations: [], platform: 'android', ...overrides,
});
class TestStorage implements ModelStorage {
  readonly unrelated = new Blob(['unrelated']); private readonly files = new Map<string, Blob>([['unrelated', this.unrelated]]); verifyCalls = 0;
  getModelPath(model: AiModel): string { return `models/${model.id}/${model.version}`; }
  async exists(model: AiModel): Promise<boolean> { return this.files.has(this.getModelPath(model)); }
  async getSize(model: AiModel): Promise<number | null> { return (await this.read(model))?.size ?? null; }
  async write(model: AiModel, data: Blob): Promise<void> { this.files.set(this.getModelPath(model), data); }
  async read(model: AiModel): Promise<Blob | null> { return this.files.get(this.getModelPath(model)) ?? null; }
  async delete(model: AiModel): Promise<void> { this.files.delete(this.getModelPath(model)); }
  async verifyChecksum(model: AiModel): Promise<boolean> { this.verifyCalls += 1; if (!model.sha256) return false; const data = await this.read(model); return data ? (await sha256Hex(data)) === model.sha256.toLowerCase() : false; }
  hasUnrelatedData(): boolean { return this.files.get('unrelated') === this.unrelated; }
}
class FailingStorage extends TestStorage { async write(): Promise<void> { throw new Error('quota exceeded'); } }
class TestDevice implements DeviceCapabilityProvider { constructor(private readonly current: DeviceCapability) {} getDeviceCapability(): Promise<DeviceCapability> { return Promise.resolve(this.current); } }
function assert(condition: boolean, message: string): void { if (!condition) throw new Error(message); }
function assertEqual<T>(actual: T, expected: T, message: string): void { assert(actual === expected, `${message}: expected ${String(expected)}, got ${String(actual)}`); }
function modelWithChecksum(sha256: string): AiModel { return { ...PRIMARY_LOCAL_TEXT_MODEL, sha256, availability: 'UNKNOWN', status: 'NOT_INSTALLED' }; }

async function run(): Promise<void> {
  const registry = new InMemoryModelRegistry(); const storage = new TestStorage(); const device = new TestDevice(capability()); const manager = new ModelManager(registry, storage, device);
  const data = new Blob(['work-social-model-manager-test']); const checksum = await sha256Hex(data); const model = modelWithChecksum(checksum);
  assertEqual(manager.registerModel(model).status, 'NOT_INSTALLED', 'registered model starts not installed');
  assertEqual(manager.getModel(model.id)?.id, model.id, 'registered model is retrievable'); assertEqual(manager.listModels().length, 1, 'registry lists registered model'); assertEqual(manager.getModel('missing'), undefined, 'unknown model is undefined');
  assertEqual((await manager.checkInstallationEligibility(model.id)).eligible, true, 'capable Android device is eligible'); assertEqual(manager.getModel(model.id)?.availability, 'AVAILABLE', 'eligible model is available');
  assertEqual((await manager.installFromBlob(model.id, data)).status, 'INSTALLED', 'valid file becomes installed'); assertEqual(manager.getModel(model.id)?.status, 'INSTALLED', 'installed status is retained'); assertEqual((await manager.discoverInstalledModels())[0]?.status, 'INSTALLED', 'discovery verifies installed file');
  storage.verifyCalls = 0; const verifiedReferences = await Promise.all([manager.getVerifiedModelReference(model.id), manager.getVerifiedModelReference(model.id)]); assertEqual(storage.verifyCalls, 1, 'concurrent verification shares one in-flight checksum operation'); assert(verifiedReferences[0] === verifiedReferences[1], 'concurrent verification returns the shared handoff');
  assertEqual((await manager.removeInstalledModel(model.id)).status, 'NOT_INSTALLED', 'remove returns not installed'); assertEqual(await storage.exists(model), false, 'model file is deleted'); assertEqual(storage.hasUnrelatedData(), true, 'unrelated storage survives model deletion');
  const mismatch = modelWithChecksum('0'.repeat(64)); const mismatchStorage = new TestStorage(); const mismatchManager = new ModelManager(new InMemoryModelRegistry(), mismatchStorage, device); mismatchManager.registerModel(mismatch); const mismatchResult = await mismatchManager.installFromBlob(mismatch.id, data); assertEqual(mismatchResult.status, 'INVALID', 'checksum mismatch is invalid'); assertEqual(mismatchResult.diagnostic?.code, 'MODEL_DOWNLOAD_CHECKSUM_FAILED', 'checksum mismatch has dedicated download code'); assertEqual(await mismatchStorage.exists(mismatch), false, 'checksum-invalid bytes are never persisted');
  const missingFileManager = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), device); missingFileManager.registerModel(modelWithChecksum(checksum)); assertEqual((await missingFileManager.discoverInstalledModels())[0]?.status, 'NOT_INSTALLED', 'missing file stays not installed');
  const unknownRam = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), new TestDevice(capability({ totalRam: null, tier: 'UNKNOWN' }))); unknownRam.registerModel(model); assert((await unknownRam.checkInstallationEligibility(model.id)).reasons.some((r) => r.code === 'UNKNOWN_DEVICE_CAPABILITY'), 'unknown RAM is conservative');
  const lowRam = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), new TestDevice(capability({ totalRam: 1 * GIB, tier: 'LOW' }))); lowRam.registerModel(model); assert((await lowRam.checkInstallationEligibility(model.id)).reasons.some((r) => r.code === 'INSUFFICIENT_RAM'), 'low RAM is rejected'); assertEqual(lowRam.getModel(model.id)?.availability, 'UNAVAILABLE', 'ineligible model is unavailable');
  const lowStorage = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), new TestDevice(capability({ availableStorage: 600 * 1024 ** 2 }))); lowStorage.registerModel(model); assert((await lowStorage.checkInstallationEligibility(model.id)).reasons.some((r) => r.code === 'INSUFFICIENT_STORAGE'), 'low storage is rejected');
  const unsupportedArch = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), new TestDevice(capability({ architecture: 'mips64' }))); unsupportedArch.registerModel(model); assert((await unsupportedArch.checkInstallationEligibility(model.id)).reasons.some((r) => r.code === 'UNSUPPORTED_ARCHITECTURE'), 'unsupported architecture is rejected');
  const unknownArch = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), new TestDevice(capability({ architecture: null }))); unknownArch.registerModel(model); assert((await unknownArch.checkInstallationEligibility(model.id)).reasons.some((r) => r.code === 'UNKNOWN_DEVICE_CAPABILITY'), 'unknown architecture is rejected');
  const web = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), new TestDevice(capability({ platform: 'web', supported: true }))); web.registerModel(model); assertEqual((await web.checkInstallationEligibility(model.id)).eligible, true, 'browser WASM runtime is eligible for the browser model');
  const androidBoundModel = { ...model, platformRequirements: { requiredPlatform: 'android' as const, minimumAndroidVersion: 26 } };
  const oldAndroid = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), new TestDevice(capability({ androidVersion: '25' }))); oldAndroid.registerModel(androidBoundModel); assert((await oldAndroid.checkInstallationEligibility(androidBoundModel.id)).reasons.some((r) => r.code === 'ANDROID_VERSION_TOO_OLD'), 'old Android is rejected for Android-bound models');
  const unknownAndroid = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), new TestDevice(capability({ androidVersion: null }))); unknownAndroid.registerModel(androidBoundModel); assert((await unknownAndroid.checkInstallationEligibility(androidBoundModel.id)).reasons.some((r) => r.code === 'UNKNOWN_DEVICE_CAPABILITY'), 'unknown Android version is rejected for Android-bound models');
  const noChecksumManager = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), device); const noChecksum = { ...PRIMARY_LOCAL_TEXT_MODEL }; noChecksumManager.registerModel(noChecksum); assertEqual((await noChecksumManager.installFromBlob(noChecksum.id, data)).status, 'INVALID', 'missing checksum cannot install');

  const ggufBytes = new Uint8Array([0x47, 0x47, 0x55, 0x46, 0x03, 0x00, 0x00, 0x00]); const ggufFile = new File([ggufBytes], 'qwen2.5-0.5b-instruct-q4_k_m.gguf', { type: 'application/octet-stream' }); const ggufChecksum = await sha256Hex(ggufFile); const importModel: AiModel = { ...PRIMARY_LOCAL_TEXT_MODEL, version: 'import-test', sizeBytes: ggufFile.size, sha256: ggufChecksum, availability: 'UNKNOWN', status: 'NOT_INSTALLED' };
  const importStorage = new TestStorage(); const importManager = new ModelManager(new InMemoryModelRegistry(), importStorage, device); importManager.registerModel(importModel); const importResult = await importManager.importLocalFile(importModel.id, ggufFile); assertEqual(importResult.status, 'INSTALLED', 'valid GGUF import becomes installed'); assertEqual(importResult.diagnostic?.code, 'MODEL_IMPORT_VERIFIED', 'valid GGUF import reports verified diagnostic'); assertEqual(importResult.diagnostic?.checksum, 'PASS', 'valid GGUF checksum passes'); assertEqual(importResult.diagnostic?.gguf, 'VALID', 'valid GGUF header passes'); assertEqual(await importStorage.exists(importModel), true, 'successful import uses the existing storage abstraction');
  const wrongSizeModel: AiModel = { ...importModel, id: 'wrong-size', sizeBytes: ggufFile.size + 1, status: 'NOT_INSTALLED' }; const wrongSizeManager = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), device); wrongSizeManager.registerModel(wrongSizeModel); const wrongSizeResult = await wrongSizeManager.importLocalFile(wrongSizeModel.id, ggufFile); assertEqual(wrongSizeResult.diagnostic?.code, 'MODEL_IMPORT_SIZE_FAILED', 'wrong-size import is rejected'); assertEqual(await wrongSizeManager.getVerifiedModelReference(wrongSizeModel.id).catch(() => null), null, 'wrong-size model is not runtime-verifiable');
  const invalidGguf = new File([new Uint8Array([0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00])], 'invalid.gguf'); const invalidGgufModel: AiModel = { ...importModel, id: 'invalid-gguf', sha256: await sha256Hex(invalidGguf), status: 'NOT_INSTALLED' }; const invalidGgufManager = new ModelManager(new InMemoryModelRegistry(), new TestStorage(), device); invalidGgufManager.registerModel(invalidGgufModel); const invalidGgufResult = await invalidGgufManager.importLocalFile(invalidGgufModel.id, invalidGguf); assertEqual(invalidGgufResult.diagnostic?.code, 'MODEL_IMPORT_GGUF_INVALID', 'non-GGUF header is rejected');
  const wrongShaModel: AiModel = { ...importModel, id: 'wrong-sha', sha256: '0'.repeat(64), status: 'NOT_INSTALLED' }; const wrongShaStorage = new TestStorage(); const wrongShaManager = new ModelManager(new InMemoryModelRegistry(), wrongShaStorage, device); wrongShaManager.registerModel(wrongShaModel); const wrongShaResult = await wrongShaManager.importLocalFile(wrongShaModel.id, ggufFile); assertEqual(wrongShaResult.diagnostic?.code, 'MODEL_IMPORT_CHECKSUM_FAILED', 'wrong SHA is rejected'); assertEqual(wrongShaResult.diagnostic?.checksum, 'FAIL', 'wrong SHA reports checksum failure'); assertEqual(await wrongShaStorage.exists(wrongShaModel), false, 'wrong SHA is never persisted');
  const failingStorage = new FailingStorage(); const failingManager = new ModelManager(new InMemoryModelRegistry(), failingStorage, device); failingManager.registerModel(importModel); const failingResult = await failingManager.importLocalFile(importModel.id, ggufFile); assertEqual(failingResult.status, 'NOT_INSTALLED', 'storage failure does not mark model installed'); assertEqual(failingResult.diagnostic?.code, 'MODEL_STORAGE_WRITE_FAILED', 'storage failure is structured');
  const cancelledStorage = new TestStorage(); const cancelledManager = new ModelManager(new InMemoryModelRegistry(), cancelledStorage, device); cancelledManager.registerModel(importModel); const controller = new AbortController(); controller.abort(); let aborted = false; try { await cancelledManager.importLocalFile(importModel.id, ggufFile, controller.signal); } catch (error) { aborted = error instanceof Error && 'code' in error && (error as { code: string }).code === 'MODEL_IMPORT_ABORTED'; } assert(aborted, 'cancelled import reports MODEL_IMPORT_ABORTED'); assertEqual(cancelledManager.getModel(importModel.id)?.status, 'NOT_INSTALLED', 'cancelled import does not mark installed'); assertEqual(await cancelledStorage.exists(importModel), false, 'cancelled import does not persist bytes');

  assertEqual(manager.removeModelMetadata(model.id), true, 'registered model metadata can be removed'); assertEqual(manager.getModel(model.id), undefined, 'removed metadata is absent'); assertEqual(manager.removeModelMetadata('missing'), false, 'unknown metadata removal is false');
  console.log('Model Manager tests passed: registry, eligibility, remote integrity, local GGUF import validation, persistence, cancellation, safe deletion, and concurrent verification.');
}
run().catch((error: unknown) => { console.error(error); throw error; });
