import type { AiModel, LocalModelSource, ModelStorage } from './modelContracts';
import { sha256Hex } from './sha256';
import { LocalInferenceRuntimeError } from '../runtime/localInferenceContracts';
import { sanitizeMessage, type LocalAiDiagnostic } from '../runtime/localAiDiagnostics';
const DATABASE_NAME = 'work-social-ai-models'; const STORE_NAME = 'models'; const STORAGE_NAMESPACE = 'models/'; const PROVENANCE_NAMESPACE = 'provenance/';
export class WebModelStorage implements ModelStorage {
 private databasePromise: Promise<IDBDatabase> | null = null;
 getModelPath(model: AiModel): string { return `${STORAGE_NAMESPACE}${encodeURIComponent(model.id)}/${encodeURIComponent(model.version)}`; }
 private getProvenancePath(model: AiModel): string { return `${PROVENANCE_NAMESPACE}${encodeURIComponent(model.id)}/${encodeURIComponent(model.version)}`; }
 async exists(model: AiModel): Promise<boolean> { return (await this.read(model)) !== null; }
 async getSize(model: AiModel): Promise<number | null> { const data = await this.read(model); return data?.size ?? null; }
 async write(model: AiModel, data: Blob): Promise<void> { await this.withStore('readwrite', 'MODEL_STORAGE_WRITE_FAILED', model, (store) => store.put(data, this.getModelPath(model))); await requestPersistentStorage(); }
 async read(model: AiModel): Promise<Blob | null> { return this.withStore<Blob | undefined>('readonly', 'MODEL_STORAGE_READ_FAILED', model, (store) => store.get(this.getModelPath(model))).then((data) => data ?? null); }
 async delete(model: AiModel): Promise<void> { await this.withStore('readwrite', 'MODEL_STORAGE_WRITE_FAILED', model, (store) => { const request = store.delete(this.getModelPath(model)); store.delete(this.getProvenancePath(model)); return request; }); }
 async verifyChecksum(model: AiModel): Promise<boolean> { if (!model.sha256) return false; const data = await this.read(model); if (!data) return false; try { return (await sha256Hex(data)) === model.sha256.toLowerCase(); } catch (error) { throw storageError('MODEL_STORAGE_READ_FAILED', 'Stored model checksum could not be computed.', model, error); } }
 async getProvenanceSource(model: AiModel): Promise<LocalModelSource | null> { const source = await this.withStore<LocalModelSource | undefined>('readonly', 'MODEL_STORAGE_READ_FAILED', model, (store) => store.get(this.getProvenancePath(model))); return source === 'imported-local-gguf' || source === 'downloaded-local-gguf' ? source : null; }
 async setProvenanceSource(model: AiModel, source: LocalModelSource): Promise<void> { await this.withStore('readwrite', 'MODEL_STORAGE_WRITE_FAILED', model, (store) => store.put(source, this.getProvenancePath(model))); }
 /** Close this instance's cached connection so a fresh manager/storage instance can be tested or constructed cleanly. */
 async dispose(): Promise<void> { const database = this.databasePromise ? await this.databasePromise.catch(() => null) : null; this.databasePromise = null; database?.close(); }
 private openDatabase(): Promise<IDBDatabase> { if (this.databasePromise) return this.databasePromise; this.databasePromise = new Promise<IDBDatabase>((resolve, reject) => { if (typeof indexedDB === 'undefined') { reject(new Error('IndexedDB is not available in this runtime.')); return; } let openRequest: IDBOpenDBRequest; try { openRequest = indexedDB.open(DATABASE_NAME, 1); } catch (error) { reject(error); return; } openRequest.onupgradeneeded = () => { if (!openRequest.result.objectStoreNames.contains(STORE_NAME)) openRequest.result.createObjectStore(STORE_NAME); }; openRequest.onerror = () => reject(openRequest.error ?? new Error('Unable to open model storage.')); openRequest.onblocked = () => reject(new Error('Model storage is blocked by another database connection.')); openRequest.onsuccess = () => { const database = openRequest.result; database.onversionchange = () => { database.close(); this.databasePromise = null; }; database.onclose = () => { if (this.databasePromise) this.databasePromise = null; }; resolve(database); }; }).catch((error) => { this.databasePromise = null; throw error; }); return this.databasePromise; }
 private async withStore<T = void>(mode: IDBTransactionMode, code: 'MODEL_STORAGE_READ_FAILED' | 'MODEL_STORAGE_WRITE_FAILED', model: AiModel, operation: (store: IDBObjectStore) => IDBRequest<T>): Promise<T> { let database: IDBDatabase; try { database = await this.openDatabase(); } catch (error) { throw storageError(code, 'IndexedDB database could not be opened.', model, error); } return new Promise((resolve, reject) => { let transaction: IDBTransaction; try { transaction = database.transaction(STORE_NAME, mode); } catch (error) { this.databasePromise = null; reject(storageError(code, 'IndexedDB object store transaction could not be created.', model, error)); return; } let request: IDBRequest<T>; try { request = operation(transaction.objectStore(STORE_NAME)); } catch (error) { reject(storageError(code, 'IndexedDB object store operation failed.', model, error)); return; } let result: T; let requestError: DOMException | null = null; request.onsuccess = () => { result = request.result; }; request.onerror = () => { requestError = request.error; }; transaction.oncomplete = () => { if (requestError) reject(storageError(code, 'IndexedDB model storage operation failed.', model, requestError)); else resolve(result!); }; transaction.onerror = () => reject(storageError(code, 'IndexedDB model storage transaction failed.', model, transaction.error ?? requestError)); transaction.onabort = () => reject(storageError(code, 'IndexedDB model storage transaction was aborted.', model, transaction.error ?? requestError)); }); }
}
async function requestPersistentStorage(): Promise<void> { if (typeof navigator === 'undefined' || !navigator.storage?.persist) return; try { await navigator.storage.persist(); } catch {} }
function storageError(code: 'MODEL_STORAGE_READ_FAILED' | 'MODEL_STORAGE_WRITE_FAILED', message: string, model: AiModel, error?: unknown): LocalInferenceRuntimeError { const diagnostic: LocalAiDiagnostic = { stage: code === 'MODEL_STORAGE_READ_FAILED' ? 'MODEL_STORAGE_READ' : 'MODEL_STORAGE_WRITE', code, message, resource: 'IndexedDB model record', errorName: error instanceof Error ? error.name : undefined, errorMessage: error instanceof Error ? sanitizeMessage(error.message) : undefined, cause: error instanceof Error ? sanitizeMessage(error.message) : undefined, timestamp: new Date().toISOString(), modelId: model.id, modelVersion: model.version }; return new LocalInferenceRuntimeError(code, message, diagnostic); }
