import { useEffect, useMemo, useState } from 'react';
import { navigate } from '../../../app/Router';
import { getWorkerWorkEntry } from '../api/workEntries';
import { formatWorkDecimal } from '../logic/workEntryCalculations';
import { useWorkerFinance } from '../hooks/useWorkerFinance';
import type { FinanceListEntry, FinanceReceivedRecord, FinanceReceivedType } from '../types/finance';
import type { WorkEntry } from '../types/workEntry';

type Filter = 'all' | 'earnings' | 'payments' | 'advances' | 'received';
type UndoTarget = { id: string; entryType: FinanceReceivedType };
const amountRe = /^(?:0|[1-9]\d*)(?:\.\d{1,4})?$/;
const card = { border: '1px solid rgba(99,102,241,.14)', borderRadius: 18, background: 'rgba(255,255,255,.94)', boxShadow: '0 10px 28px rgba(15,23,42,.07)' };
const button = { minHeight: 44, borderRadius: 12, border: '1px solid #cbd5e1', background: '#fff', font: 'inherit', fontWeight: 800, cursor: 'pointer' };
function dateLabel(value: string) { return new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }); }
function amountLabel(value: string) { return `Rs. ${formatWorkDecimal(value)}`; }
function filterLabel(value: Filter) { return value === 'all' ? 'All' : value === 'earnings' ? 'Earnings' : value === 'payments' ? 'Payments' : value === 'advances' ? 'Advances' : 'All Received'; }
function matchesFilter(entry: FinanceListEntry, filter: Filter) { if (filter === 'all') return true; if (filter === 'earnings') return entry.kind === 'earning'; if (filter === 'payments') return entry.kind === 'payment'; if (filter === 'advances') return entry.kind === 'advance'; return entry.kind === 'payment' || entry.kind === 'advance'; }
function amountTone(value: string): 'positive' | 'negative' | 'neutral' { const normalized = value.trim(); if (/^-0+(?:\.0+)?$/.test(normalized) || /^0+(?:\.0+)?$/.test(normalized)) return 'neutral'; return normalized.startsWith('-') ? 'negative' : 'positive'; }

export function WorkerFinance() {
  const [filter, setFilter] = useState<Filter>('all');
  const finance = useWorkerFinance(filter);
  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState<FinanceReceivedRecord | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<FinanceReceivedRecord | null>(null);
  const [undoTarget, setUndoTarget] = useState<UndoTarget | null>(null);
  const [type, setType] = useState<FinanceReceivedType>('payment');
  const [amount, setAmount] = useState('');
  const [formError, setFormError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [selectedEntry, setSelectedEntry] = useState<WorkEntry | null>(null);
  const [detailsLoading, setDetailsLoading] = useState(false);
  const [detailsError, setDetailsError] = useState<string | null>(null);

  useEffect(() => {
    if (!modalOpen) { setEditing(null); setAmount(''); setType('payment'); setFormError(null); }
  }, [modalOpen]);
  useEffect(() => { if (!undoTarget) return; const timer = window.setTimeout(() => setUndoTarget(null), 8000); return () => window.clearTimeout(timer); }, [undoTarget]);

  const visibleEntries = useMemo(() => finance.entries.filter((entry) => matchesFilter(entry, filter)), [finance.entries, filter]);
  const displayedEntries = visibleEntries;
  const hasMore = finance.historyHasMore;

  const openAdd = () => { setEditing(null); setType('payment'); setAmount(''); setFormError(null); setModalOpen(true); };
  const openEdit = (record: FinanceReceivedRecord) => { setEditing(record); setType(record.entry_type); setAmount(record.amount); setFormError(null); setModalOpen(true); };
  const submit = async () => {
    const normalized = amount.trim();
    if (!normalized) { setFormError('Amount is required.'); return; }
    if (!amountRe.test(normalized) || normalized === '0') { setFormError('Enter a valid amount greater than zero, with up to 4 decimal places.'); return; }
    setFormError(null);
    const result = editing ? await finance.editReceived(editing.id, type, normalized) : await finance.addReceived(type, normalized);
    if (result.error) { setFormError(result.error.message); return; }
    setModalOpen(false); setNotice('Saved successfully');
  };
  const confirmDelete = async () => {
    if (!deleteTarget) return;
    const result = await finance.removeReceived(deleteTarget.id);
    if (result.error) { setNotice(`Could not delete: ${result.error.message}`); return; }
    setDeleteTarget(null); setUndoTarget({ id: deleteTarget.id, entryType: deleteTarget.entry_type }); setNotice(`${deleteTarget.entry_type === 'payment' ? 'Payment' : 'Advance'} deleted`);
  };
  const undoDelete = async () => { if (!undoTarget) return; const result = await finance.restoreReceived(undoTarget.id); if (result.error) { setNotice(`Could not restore: ${result.error.message}`); return; } setUndoTarget(null); setNotice('Restored successfully'); };
  const dismissNotice = () => { setUndoTarget(null); setNotice(null); };
  const openDetails = async (entry: WorkEntry) => {
    setSelectedEntry(null); setDetailsError(null); setDetailsLoading(true);
    const result = await getWorkerWorkEntry(entry.id); setDetailsLoading(false);
    if (result.error) { setDetailsError(result.error.message); return; }
    if (!result.data) { setDetailsError('This Work Entry is no longer available.'); return; }
    setSelectedEntry(result.data);
  };

  if (finance.loading) return <main style={{ width: '100%', maxWidth: 900, margin: '0 auto', padding: '24px 14px 112px', boxSizing: 'border-box' }}><p style={{ color: '#64748b' }}>Loading Finance…</p></main>;
  if (finance.error) return <main style={{ width: '100%', maxWidth: 900, margin: '0 auto', padding: '24px 14px 112px', boxSizing: 'border-box' }}><button type="button" onClick={() => navigate('/work')} style={{ ...button, padding: '0 12px' }}>← Work House</button><p role="alert" style={{ ...card, marginTop: 16, padding: 18, color: '#b91c1c', fontWeight: 750 }}>{finance.error}</p></main>;

  return <main style={{ width: '100%', maxWidth: 900, margin: '0 auto', padding: '18px 14px 112px', boxSizing: 'border-box' }}>
    <header style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 18 }}><div><button type="button" onClick={() => navigate('/work')} style={{ ...button, minHeight: 38, padding: '0 11px', fontSize: 13 }}>← Work House</button><div style={{ marginTop: 12, color: '#64748b', fontSize: 11, fontWeight: 850, letterSpacing: '.08em', textTransform: 'uppercase' }}>Worker Finance</div><h1 style={{ margin: '4px 0 0', fontSize: 'clamp(28px, 7vw, 42px)', letterSpacing: '-.04em' }}>Finance</h1></div><button type="button" onClick={openAdd} style={{ ...button, flex: '0 0 auto', padding: '0 15px', border: '1px solid rgba(79,70,229,.3)', background: '#4f46e5', color: '#fff', boxShadow: '0 8px 18px rgba(79,70,229,.18)' }}>+ Add</button></header>
    {notice && <div role="status" aria-live="polite" style={{ ...card, marginBottom: 12, padding: '10px 13px', color: undoTarget ? '#991b1b' : '#166534', background: undoTarget ? '#fef2f2' : '#f0fdf4', borderColor: undoTarget ? '#fecaca' : '#bbf7d0', fontSize: 13, fontWeight: 850, display: 'flex', alignItems: 'center', gap: 10 }}><span style={{ flex: 1 }}>{notice}</span>{undoTarget && <button type="button" onClick={() => void undoDelete()} disabled={finance.saving} style={{ ...button, minHeight: 36, padding: '0 11px', color: '#991b1b', borderColor: '#fecaca', background: '#fff' }}>Undo</button>}<button type="button" onClick={dismissNotice} aria-label="Dismiss message" style={{ border: 0, background: 'transparent', fontSize: 18, cursor: 'pointer', padding: 2 }}>×</button></div>}
    <section aria-label="Finance summary" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 10, marginBottom: 16 }}><SummaryCard label="Total Earnings" value={amountLabel(finance.summary.total_earnings)} tone="positive" /><SummaryCard label="Received" value={amountLabel(finance.summary.received)} tone="negative" /><SummaryCard label="Remaining" value={amountLabel(finance.summary.remaining)} tone={amountTone(finance.summary.remaining)} /></section>
    <section style={{ ...card, padding: 12, marginBottom: 14 }} aria-label="Finance filter"><label htmlFor="finance-filter" style={{ display: 'grid', gap: 6, fontSize: 12, fontWeight: 850, color: '#475569' }}>Filter<select id="finance-filter" value={filter} onChange={(event) => setFilter(event.target.value as Filter)} style={{ minHeight: 44, borderRadius: 12, border: '1px solid #cbd5e1', padding: '0 11px', background: '#fff', font: 'inherit', fontWeight: 750 }}>{(['all', 'earnings', 'payments', 'advances', 'received'] as Filter[]).map((item) => <option key={item} value={item}>{filterLabel(item)}</option>)}</select></label></section>
    <section aria-labelledby="finance-list-heading"><h2 id="finance-list-heading" style={{ margin: '0 0 10px', fontSize: 19 }}>{filterLabel(filter)}</h2>{visibleEntries.length === 0 ? <section style={{ ...card, padding: 24, textAlign: 'center' }}><h3 style={{ margin: 0, fontSize: 17 }}>{finance.entries.length ? 'No matching finance records' : 'No finance records yet'}</h3><p style={{ margin: '7px 0 0', color: '#64748b', fontSize: 13, lineHeight: 1.5 }}>{finance.entries.length ? 'Try another filter.' : 'Your earnings and received amounts will appear here.'}</p></section> : <><div style={{ display: 'grid', gap: 10 }}>{displayedEntries.map((entry) => <FinanceRow key={entry.id} entry={entry} onDetails={openDetails} onEdit={openEdit} onDelete={setDeleteTarget} />)}</div>{hasMore && <button type="button" onClick={() => void finance.loadMoreHistory()} disabled={finance.historyLoadingMore} style={{ ...button, width: '100%', minHeight: 38, marginTop: 10, background: 'linear-gradient(180deg,#fff,#f3f6fa)', boxShadow: 'inset 0 1px 0 #fff, 0 3px 8px rgba(15,23,42,.08)', opacity: finance.historyLoadingMore ? .7 : 1 }}>{finance.historyLoadingMore ? 'Loading…' : 'Load More'}</button>}</>}</section>
    {modalOpen && <AddReceivedModal editing={editing} type={type} setType={setType} amount={amount} setAmount={setAmount} formError={formError} saving={finance.saving} onCancel={() => setModalOpen(false)} onSave={() => void submit()} />}
    {deleteTarget && <DeleteModal saving={finance.saving} onCancel={() => setDeleteTarget(null)} onDelete={() => void confirmDelete()} />}
    {(selectedEntry || detailsLoading || detailsError) && <WorkEntryDetails entry={selectedEntry} loading={detailsLoading} error={detailsError} onClose={() => { setSelectedEntry(null); setDetailsError(null); }} />}
  </main>;
}

function SummaryCard({ label, value, tone = 'neutral' }: { label: string; value: string; tone?: 'positive' | 'negative' | 'neutral' }) { const valueColor = tone === 'positive' ? '#15803d' : tone === 'negative' ? '#b91c1c' : '#0f172a'; return <section style={{ ...card, padding: 17 }}><div style={{ color: '#64748b', fontSize: 11, fontWeight: 850, letterSpacing: '.06em', textTransform: 'uppercase' }}>{label}</div><div style={{ marginTop: 6, fontSize: 'clamp(23px,6vw,32px)', fontWeight: 950, letterSpacing: '-.04em', color: valueColor }}>{value}</div></section>; }
function FinanceRow({ entry, onDetails, onEdit, onDelete }: { entry: FinanceListEntry; onDetails: (entry: WorkEntry) => void; onEdit: (record: FinanceReceivedRecord) => void; onDelete: (record: FinanceReceivedRecord) => void }) { const earning = entry.kind === 'earning'; const label = earning ? 'Earnings' : entry.kind === 'payment' ? 'Payment' : 'Advance'; return <article style={{ ...card, padding: 15, borderLeft: `4px solid ${earning ? '#16a34a' : '#dc2626'}` }}><div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}><div><div style={{ fontSize: 19, fontWeight: 950, color: earning ? '#15803d' : '#b91c1c' }}>{earning ? '+' : '−'} {amountLabel(entry.amount)}</div><div style={{ marginTop: 3, fontSize: 12, fontWeight: 900, color: '#334155' }}>{label}</div></div><span aria-label={label} style={{ display: 'inline-flex', padding: '5px 8px', borderRadius: 999, background: earning ? '#f0fdf4' : '#fef2f2', color: earning ? '#166534' : '#991b1b', fontSize: 11, fontWeight: 900 }}>{label}</span></div><div style={{ marginTop: 9, color: '#64748b', fontSize: 12 }}>{earning ? `Work Entry · ${dateLabel(entry.occurred_at)}` : `${label} · ${dateLabel(entry.occurred_at)}`}</div>{earning ? <button type="button" onClick={() => onDetails(entry.workEntry)} style={{ marginTop: 9, border: 0, background: 'transparent', padding: 0, color: '#4338ca', font: 'inherit', fontSize: 12, fontWeight: 850, cursor: 'pointer' }}>View details →</button> : <div style={{ display: 'flex', gap: 8, marginTop: 11 }}><button type="button" onClick={() => onEdit(entry.record)} style={{ ...button, minHeight: 38, padding: '0 12px', fontSize: 12 }}>Edit</button><button type="button" onClick={() => onDelete(entry.record)} style={{ ...button, minHeight: 38, padding: '0 12px', fontSize: 12, color: '#b91c1c', borderColor: '#fecaca' }}>Delete</button></div>}</article>; }
function AddReceivedModal({ editing, type, setType, amount, setAmount, formError, saving, onCancel, onSave }: { editing: FinanceReceivedRecord | null; type: FinanceReceivedType; setType: (type: FinanceReceivedType) => void; amount: string; setAmount: (value: string) => void; formError: string | null; saving: boolean; onCancel: () => void; onSave: () => void }) { return <div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onCancel(); }} style={{ position: 'fixed', inset: 0, zIndex: 1300, display: 'flex', alignItems: 'flex-end', justifyContent: 'center', background: 'rgba(15,23,42,.56)', backdropFilter: 'blur(7px)' }}><section role="dialog" aria-modal="true" aria-labelledby="received-modal-title" style={{ width: '100%', maxWidth: 560, borderRadius: '24px 24px 0 0', background: '#fff', padding: '12px 16px calc(20px + env(safe-area-inset-bottom))', boxSizing: 'border-box', boxShadow: '0 -20px 70px rgba(15,23,42,.25)' }}><div style={{ width: 42, height: 4, borderRadius: 99, background: '#cbd5e1', margin: '0 auto 12px' }} /><h2 id="received-modal-title" style={{ margin: 0, fontSize: 19 }}>{editing ? 'Edit Received' : 'Add Received'}</h2><div style={{ display: 'grid', gap: 12, marginTop: 14 }}><label style={{ display: 'grid', gap: 6, fontSize: 12, fontWeight: 850 }}>Type<select value={type} onChange={(event) => setType(event.target.value as FinanceReceivedType)} disabled={saving} style={{ minHeight: 44, borderRadius: 12, border: '1px solid #cbd5e1', padding: '0 11px', background: '#fff', font: 'inherit' }}><option value="payment">Payment</option><option value="advance">Advance</option></select></label><label style={{ display: 'grid', gap: 6, fontSize: 12, fontWeight: 850 }}>Amount<input value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal" disabled={saving} style={{ minHeight: 44, borderRadius: 12, border: '1px solid #cbd5e1', padding: '0 11px', background: '#fff', font: 'inherit' }} /></label>{formError && <p role="alert" style={{ margin: 0, color: '#b91c1c', fontSize: 12, fontWeight: 750 }}>{formError}</p>}<div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}><button type="button" onClick={onCancel} disabled={saving} style={{ ...button, padding: '0 13px' }}>Cancel</button><button type="button" onClick={onSave} disabled={saving} style={{ ...button, padding: '0 15px', background: '#4f46e5', color: '#fff', borderColor: '#4f46e5' }}>{saving ? 'Saving…' : editing ? 'Save changes' : 'Add'}</button></div></div></section></div>; }
function DeleteModal({ saving, onCancel, onDelete }: { saving: boolean; onCancel: () => void; onDelete: () => void }) { return <div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onCancel(); }} style={{ position: 'fixed', inset: 0, zIndex: 1300, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16, background: 'rgba(15,23,42,.56)', backdropFilter: 'blur(7px)' }}><section role="dialog" aria-modal="true" aria-labelledby="delete-title" style={{ width: '100%', maxWidth: 420, ...card, padding: 18, background: '#fff' }}><h2 id="delete-title" style={{ margin: 0, fontSize: 18 }}>Delete received record?</h2><p style={{ margin: '8px 0 16px', color: '#64748b', fontSize: 13, lineHeight: 1.5 }}>This removes the selected received record. You can undo the deletion for a short time.</p><div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}><button type="button" onClick={onCancel} disabled={saving} style={{ ...button, padding: '0 13px' }}>Cancel</button><button type="button" onClick={onDelete} disabled={saving} style={{ ...button, padding: '0 13px', color: '#b91c1c', borderColor: '#fecaca', background: '#fff5f5' }}>{saving ? 'Deleting…' : 'Delete'}</button></div></section></div>; }
function WorkEntryDetails({ entry, loading, error, onClose }: { entry: WorkEntry | null; loading: boolean; error: string | null; onClose: () => void }) { return <div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }} style={{ position: 'fixed', inset: 0, zIndex: 1200, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16, background: 'rgba(15,23,42,.56)', backdropFilter: 'blur(7px)' }}><section role="dialog" aria-modal="true" aria-labelledby="entry-details-title" style={{ width: '100%', maxWidth: 560, maxHeight: '85vh', overflowY: 'auto', ...card, padding: 18, background: '#fff' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }}><h2 id="entry-details-title" style={{ margin: 0, fontSize: 19 }}>Work Entry Details</h2><button type="button" onClick={onClose} aria-label="Close details" style={{ ...button, minHeight: 36, minWidth: 36, padding: 0 }}>×</button></div>{loading && <p style={{ color: '#64748b' }}>Loading Work Entry…</p>}{error && <p role="alert" style={{ color: '#b91c1c', fontWeight: 750 }}>{error}</p>}{entry && <div style={{ display: 'grid', gap: 10, marginTop: 14 }}>{[['Date', dateLabel(entry.date)], ['Location', entry.location], ['Description', entry.description || '—'], ['Total', amountLabel(entry.total)]].map(([label, value]) => <div key={label} style={{ ...card, padding: 11 }}><div style={{ fontSize: 10, fontWeight: 850, color: '#64748b', textTransform: 'uppercase' }}>{label}</div><div style={{ marginTop: 3, fontSize: 14, fontWeight: 800, color: '#172033' }}>{value}</div></div>)}</div>}</section></div>; }
