import { useEffect, useState } from 'react';
import { navigate } from '../../../app/Router';
import { supabase } from '../../../lib/supabase/client';
import '../worker-compact.css';
import { useCurrentWorkerProfileId } from '../hooks/useCurrentWorkerProfileId';
import { useWorkerProfile } from '../hooks/useWorkerProfile';

type Destination = { path: string; label: string; icon: string; salaryLabel?: string };
type TeamInvitation = { id:string; sender_id:string; type:string; metadata:Record<string,unknown>|null; created_at:string; sender?:{display_name:string|null;username:string|null;gender:string|null} };
type ContractorTeamContext = { team_id:number; team_number:number; team_name:string };
const workerDestinations: Destination[] = [
  { path: '/work', label: 'Home', icon: '⌂' },
  { path: '/work/finance', label: 'Finance', salaryLabel: 'Salary', icon: '¤' },
  { path: '/work/settings', label: 'Settings', icon: '⚙' },
];
const contractorDestinations: Destination[] = [
  { path: '/work/contractor?view=overview', label: 'Home', icon: '⌂' },
  { path: '/work/contractor?view=finance', label: 'Finance', icon: '¤' },
  { path: '/work/contractor?view=settings', label: 'Settings', icon: '⚙' },
];
function teamNumberFromPath(pathname:string){const match=pathname.match(/^\/work\/team-work\/(\d+)(?:\/|$)/);return match?.[1]??null}
function contractorTeamNumber(pathname:string,search:string){const query=new URLSearchParams(search);if(pathname==='/work/contractor'&&['team','team-work','team-settings'].includes(query.get('view')??''))return query.get('team');const match=pathname.match(/^\/work\/contractor\/team-(?:finance|settings|work)\/(\d+)(?:\/|$)/);return match?.[1]??null}
function isActive(pathname:string,search:string,path:string){const [targetPath,targetQuery]=path.split('?');if(targetPath==='/work')return pathname==='/work';if(targetPath!=='/work/contractor')return pathname===targetPath||pathname.startsWith(`${targetPath}/`);const current=new URLSearchParams(search),target=new URLSearchParams(targetQuery??'');const currentView=current.get('view')??'overview',targetView=target.get('view')??'overview';return pathname==='/work/contractor'&&currentView===targetView&&(!target.get('team')||target.get('team')===current.get('team'))}
function pronoun(g:string|null|undefined){return g==='male'?'his':g==='female'?'her':'their'}
function navigateNavigation(path:string){window.history.replaceState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'))}
export function WorkerNavigation(){const pathname=window.location.pathname,search=window.location.search;const query=new URLSearchParams(search);const contractorView=query.get('view');const contractorPersonalTeam=contractorView==='team-dashboard'||contractorView==='finance'||contractorView==='settings'?query.get('team'):null;const session=useCurrentWorkerProfileId();const {workerProfile}=useWorkerProfile(session.profileId??'');const isContractor=pathname==='/work/contractor';const isSalaryPerson=workerProfile?.worker_type==='salary_person';const workerTeamNumber=teamNumberFromPath(pathname);const contractorTeam=contractorTeamNumber(pathname,search);const teamContext=Boolean(workerTeamNumber||contractorTeam);const teamNumber=contractorTeam??workerTeamNumber;const [teamFinanceId,setTeamFinanceId]=useState<number|null>(null);const [flash,setFlash]=useState<TeamInvitation|null>(null);const [responding,setResponding]=useState(false);
 useEffect(()=>{let active=true;setTeamFinanceId(null);if(!contractorTeam)return;const loadTeamContext=async()=>{const {data,error}=await supabase.rpc('get_contractor_team_context_by_number',{p_team_number:Number(contractorTeam)});if(!active)return;if(error||!data?.[0]){setTeamFinanceId(null);return}setTeamFinanceId(Number((data[0] as ContractorTeamContext).team_id))};void loadTeamContext();return()=>{active=false}},[contractorTeam]);
 const contractorPersonalDestinations:Destination[]=contractorPersonalTeam?[{path:`/work/contractor?view=team-dashboard&team=${contractorPersonalTeam}`,label:'Home',icon:'⌂'},{path:`/work/contractor?view=finance&team=${contractorPersonalTeam}`,label:'Finance',icon:'¤'},{path:`/work/contractor?view=settings&team=${contractorPersonalTeam}`,label:'Settings',icon:'⚙'}]:contractorDestinations;
 const teamDestinations:Destination[]=teamNumber&&contractorTeam?[{path:`/work/contractor?view=team&team=${teamNumber}`,label:'Home',icon:'⌂'},...(teamFinanceId?[{path:`/work/contractor/team-finance/${teamFinanceId}`,label:'Finance',icon:'¤'}]:[]),{path:`/work/contractor?view=team-settings&team=${teamNumber}`,label:'Settings',icon:'⚙'}]:workerTeamNumber?[{path:`/work/team-work/${workerTeamNumber}`,label:'Home',icon:'⌂'},{path:`/work/team-work/${workerTeamNumber}/finance`,label:'Finance',icon:'¤'},{path:`/work/team-work/${workerTeamNumber}/settings`,label:'Settings',icon:'⚙'}]:[];
 const destinations=teamContext?teamDestinations:(isContractor?contractorPersonalDestinations:workerDestinations);
 useEffect(()=>{const workerId=session.profileId;if(!workerId||isContractor||teamContext)return;let mounted=true;const channel=supabase.channel(`team-invitations-flash:${workerId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`receiver_id=eq.${workerId}`},async payload=>{const row=payload.new as TeamInvitation;if(row.type!=='team_invitation')return;const {data:s}=await supabase.from('profiles').select('id,display_name,username,gender').eq('id',row.sender_id).maybeSingle();if(mounted)setFlash({...row,sender:s??undefined})}).subscribe();return()=>{mounted=false;void supabase.removeChannel(channel)}},[session.profileId,isContractor,teamContext]);
 useEffect(()=>{if(!flash)return;const t=window.setTimeout(()=>setFlash(null),10000);return()=>window.clearTimeout(t)},[flash]);
 const respond=async(accept:boolean)=>{if(!flash||responding)return;setResponding(true);const {error}=await supabase.rpc('respond_to_contractor_team_invitation',{p_invitation_id:flash.id,p_accept:accept});setResponding(false);if(error)return;setFlash(null)};
 const flashSender=flash?.sender?.display_name??flash?.sender?.username??'A contractor';const team=flash&&((typeof flash.metadata?.team_number==='number'||typeof flash.metadata?.team_number==='string')?String(flash.metadata?.team_number):'');
 return <><style>{`.wn-team-flash{position:fixed;right:12px;top:74px;z-index:1450;width:min(360px,calc(100% - 24px));padding:14px;border:1px solid rgba(255,255,255,.94);border-radius:18px;background:linear-gradient(145deg,rgba(236,253,245,.99),rgba(255,255,255,.99) 55%,rgba(239,246,255,.98));box-shadow:0 24px 65px rgba(15,23,42,.26),inset 0 1px 0 #fff;animation:wnFlash .22s ease-out}.wn-team-flash-title{color:#047857;font-size:11px;font-weight:950}.wn-team-flash-copy{margin-top:5px;color:#334155;font-size:10px;line-height:1.45}.wn-team-flash-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.wn-team-btn{min-height:35px;border-radius:10px;border:1px solid rgba(100,116,139,.16);font-size:9px;font-weight:950;box-shadow:0 4px 0 rgba(15,23,42,.07),inset 0 1px 0 #fff}.wn-team-accept{background:linear-gradient(145deg,#10b981,#047857);color:#fff}.wn-team-decline{background:linear-gradient(145deg,#fff,#fef2f2);color:#b91c1c}@keyframes wnFlash{from{opacity:0;transform:translateY(-8px) scale(.98)}to{opacity:1;transform:none}}`}</style>{flash&&<div className="wn-team-flash" role="alert"><div className="wn-team-flash-title">♛ Work Team Invitation</div><div className="wn-team-flash-copy"><strong>{flashSender}</strong> invited you to join {pronoun(flash.sender?.gender)} work team{team?` · Team ${team}`:''}.</div><div className="wn-team-flash-actions"><button type="button" className="wn-team-btn wn-team-accept" disabled={responding} onClick={()=>void respond(true)}>Accept</button><button type="button" className="wn-team-btn wn-team-decline" disabled={responding} onClick={()=>void respond(false)}>Decline</button></div></div>}<nav aria-label={teamContext?'Team workspace navigation':isContractor?'Contractor navigation':'Worker navigation'} style={{position:'fixed',left:8,right:8,bottom:0,zIndex:1000,display:'grid',gridTemplateColumns:`repeat(${Math.max(destinations.length,1)},minmax(0,1fr))`,gap:5,padding:6,boxSizing:'border-box',background:'linear-gradient(145deg,rgba(15,23,42,.97),rgba(30,41,59,.96),rgba(49,46,129,.96))',border:'1px solid rgba(255,255,255,.14)',borderRadius:17,boxShadow:'0 10px 24px rgba(15,23,42,.28)'}}>{destinations.map(destination=>{const active=isActive(pathname,search,destination.path);const label=!teamContext&&!isContractor&&isSalaryPerson&&destination.salaryLabel?destination.salaryLabel:destination.label;return <button key={destination.path} type="button" onClick={()=>navigateNavigation(destination.path)} aria-current={active?'page':undefined} style={{position:'relative',minHeight:44,minWidth:0,border:active?'1px solid rgba(125,211,252,.5)':'1px solid rgba(255,255,255,.07)',borderRadius:12,color:'#fff',background:active?'rgba(59,130,246,.35)':'rgba(255,255,255,.035)',cursor:'pointer',font:'inherit',padding:'2px 4px'}}><span aria-hidden="true" style={{display:'block',fontSize:16,lineHeight:1.05}}>{destination.icon}</span><span style={{fontSize:9,lineHeight:1.1,fontWeight:800}}>{label}</span></button>})}</nav></>}
