import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { navigate } from '../../../app/Router';
import { getWorkerWorkEntry } from '../api/workEntries';
import { formatWorkDecimal, getWorkerWorkDayBounds, getWorkerWorkMonthBounds, getWorkerWorkWeekBounds, getWorkerWorkWeekStart } from '../logic/workEntryCalculations';
import { useWorkerPersonalFinance } from '../hooks/useWorkerFinance';
import type { FinanceReceivedRecord, FinanceReceivedType } from '../types/finance';
import type { WorkEntry } from '../types/workEntry';

type View = 'earnings' | 'received';
type Period = 'daily' | 'weekly' | 'monthly';
const card = { border: '1px solid rgba(148,163,184,.18)', borderRadius: 22, background: 'linear-gradient(145deg,rgba(30,41,59,.9),rgba(15,23,42,.96))', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.08), 0 18px 42px rgba(2,6,23,.28)' };
const lightCard = { ...card, background: 'linear-gradient(145deg,rgba(30,41,59,.82),rgba(15,23,42,.94))' };
const button = { minHeight: 42, borderRadius: 13, border: '1px solid rgba(148,163,184,.2)', background: 'rgba(30,41,59,.72)', color: '#e2e8f0', font: 'inherit', fontWeight: 850, cursor: 'pointer' };
function amountLabel(value: string) { return `PKR ${formatWorkDecimal(value)}`; }
function dateLabel(value: string) { return new Date(value).toLocaleDateString('en-PK', { month: 'short', day: 'numeric', year: 'numeric' }); }
function addDays(value: Date, days: number) { return new Date(value.getTime() + days * 86400000); }
function monthAnchor(value: Date) { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Karachi', year: 'numeric', month: '2-digit' }).formatToParts(value); const year = parts.find((p) => p.type === 'year')?.value ?? '1970'; const month = parts.find((p) => p.type === 'month')?.value ?? '01'; return new Date(`${year}-${month}-01T00:00:00+05:00`); }
function periodAnchor(period: Period, value: Date) { return period === 'daily' ? new Date(value) : period === 'weekly' ? getWorkerWorkWeekStart(value) : monthAnchor(value); }
function shiftAnchor(period: Period, value: Date, direction: number) { const anchor = periodAnchor(period, value); return period === 'daily' ? addDays(anchor, direction) : period === 'weekly' ? addDays(anchor, direction * 7) : monthAnchor(new Date(anchor.getFullYear(), anchor.getMonth() + direction, 1)); }
function periodBounds(period: Period, anchor: Date) { if (period === 'daily') { const value = getWorkerWorkDayBounds(anchor); return { start: value.dayStart, end: value.dayEnd }; } if (period === 'weekly') { const value = getWorkerWorkWeekBounds(anchor); return { start: value.weekStart, end: value.weekEnd }; } const value = getWorkerWorkMonthBounds(anchor); return { start: value.monthStart, end: value.monthEnd }; }
function periodTitle(period: Period, anchor: Date) { if (period === 'daily') return anchor.toLocaleDateString('en-PK', { weekday: 'short', month: 'short', day: 'numeric' }); if (period === 'weekly') { const start = periodAnchor('weekly', anchor); const end = addDays(start, 6); return `${start.toLocaleDateString('en-PK', { month: 'short', day: 'numeric' })} – ${end.toLocaleDateString('en-PK', { month: 'short', day: 'numeric', year: 'numeric' })}`; } return anchor.toLocaleDateString('en-PK', { month: 'long', year: 'numeric' }); }
function isCurrentPeriod(period: Period, anchor: Date) { return periodAnchor(period, anchor).getTime() === periodAnchor(period, new Date()).getTime(); }

export function WorkerFinance() {
  const [view, setView] = useState<View>('earnings'); const [period, setPeriod] = useState<Period>('monthly'); const [anchor, setAnchor] = useState(() => new Date()); const [modalOpen, setModalOpen] = useState(false); const [editing, setEditing] = useState<FinanceReceivedRecord | null>(null); const [deleteTarget, setDeleteTarget] = useState<FinanceReceivedRecord | null>(null); const [type, setType] = useState<FinanceReceivedType>('payment'); const [amount, setAmount] = useState(''); const [formError, setFormError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [selectedEntry, setSelectedEntry] = useState<WorkEntry | null>(null); const [detailsLoading, setDetailsLoading] = useState(false); const [detailsError, setDetailsError] = useState<string | null>(null);
  const bounds = useMemo(() => periodBounds(period, periodAnchor(period, anchor)), [period, anchor]); const finance = useWorkerPersonalFinance(view, period, bounds); const futureDisabled = isCurrentPeriod(period, anchor);
  useEffect(() => { if (!modalOpen) { setEditing(null); setAmount(''); setType('payment'); setFormError(null); } }, [modalOpen]);
  const openAdd = () => { setEditing(null); setType('payment'); setAmount(''); setFormError(null); setModalOpen(true); }; const openEdit = (record: FinanceReceivedRecord) => { setEditing(record); setType(record.entry_type); setAmount(record.amount); setFormError(null); setModalOpen(true); };
  const submit = async () => { const normalized = amount.trim(); if (!normalized || !/^(?:0|[1-9]\d*)(?:\.\d{1,4})?$/.test(normalized) || normalized === '0') { setFormError('Enter a valid amount greater than zero, with up to 4 decimal places.'); return; } const result = editing ? await finance.editReceived(editing.id, type, normalized) : await finance.addReceived(type, normalized); if (result.error) { setFormError(result.error.message); return; } setModalOpen(false); setNotice('Saved successfully'); };
  const confirmDelete = async () => { if (!deleteTarget) return; const result = await finance.removeReceived(deleteTarget.id); if (result.error) { setNotice(`Could not delete: ${result.error.message}`); return; } setDeleteTarget(null); setNotice('Received record deleted'); }; const undoDelete = async () => { if (!finance.lastDeletedId) return; const result = await finance.restoreReceived(finance.lastDeletedId); if (result.error) { setNotice(`Could not restore: ${result.error.message}`); return; } setNotice('Restored successfully'); };
  const openDetails = async (entry: WorkEntry) => { setSelectedEntry(null); setDetailsError(null); setDetailsLoading(true); const result = await getWorkerWorkEntry(entry.id); setDetailsLoading(false); if (result.error) { setDetailsError(result.error.message); return; } if (!result.data) { setDetailsError('This Work Entry is no longer available.'); return; } setSelectedEntry(result.data); };
  if (finance.loading) return <main style={{ width: '100%', maxWidth: 920, margin: '0 auto', padding: '24px 14px 112px' }}><p style={{ color: '#94a3b8' }}>Loading Worker Finance…</p></main>;
  if (finance.error) return <main style={{ width: '100%', maxWidth: 920, margin: '0 auto', padding: '24px 14px 112px' }}><button type="button" onClick={() => navigate('/work')} style={{ ...button, padding: '0 13px' }}>← Work House</button><p role="alert" style={{ ...lightCard, marginTop: 16, padding: 18, color: '#fca5a5' }}>{finance.error}</p></main>;
  return <main style={{ width: '100%', maxWidth: 920, margin: '0 auto', padding: '16px 14px 112px', boxSizing: 'border-box', color: '#e2e8f0' }}>
    <header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 18 }}><div><button type="button" onClick={() => navigate('/work')} style={{ ...button, minHeight: 36, padding: '0 11px', fontSize: 12 }}>← Work House</button><div style={{ marginTop: 13, color: '#67e8f9', fontSize: 10, fontWeight: 950, letterSpacing: '.14em', textTransform: 'uppercase' }}>Worker · Personal Finance</div><h1 style={{ margin: '4px 0 0', fontSize: 'clamp(28px,7vw,42px)', lineHeight: .98, letterSpacing: '-.045em', fontWeight: 950, color: '#f8fafc' }}>Finance Command Center</h1></div><button type="button" onClick={openAdd} style={{ ...button, minHeight: 42, padding: '0 14px', borderColor: 'rgba(103,232,249,.3)', background: 'linear-gradient(135deg,#4f46e5,#0891b2)', color: '#fff', boxShadow: '0 10px 24px rgba(8,145,178,.22)' }}>+ Add</button></header>
    {notice && <div role="status" style={{ ...lightCard, marginBottom: 12, padding: '10px 13px', color: '#a7f3d0', fontSize: 12, fontWeight: 850, display: 'flex', alignItems: 'center', gap: 10 }}><span style={{ flex: 1 }}>{notice}</span>{finance.lastDeletedId && <button type="button" onClick={() => void undoDelete()} disabled={finance.saving} style={{ ...button, minHeight: 34, padding: '0 10px', color: '#c4b5fd', borderColor: 'rgba(167,139,250,.28)' }}>Undo</button>}<button type="button" onClick={() => setNotice(null)} style={{ border: 0, background: 'transparent', color: '#64748b', fontSize: 16, cursor: 'pointer' }} aria-label="Dismiss message">×</button></div>}
    <section aria-label="Finance summary" style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 10, marginBottom: 14 }}><SummaryCard label="Total Earnings" value={amountLabel(finance.summary.total_earnings)} accent="cyan" /><SummaryCard label="Current Balance" value={amountLabel(finance.summary.current_balance)} accent="blue" /><SummaryCard label="Advance" value={amountLabel(finance.summary.advance)} accent="violet" /><SummaryCard label="Received Amount" value={amountLabel(finance.summary.received)} accent="emerald" clickable onClick={() => setView('received')} /></section>
    <section style={{ ...card, padding: 12, marginBottom: 14 }}><div style={{ display: 'flex', gap: 8, marginBottom: 10 }}><ViewButton active={view === 'earnings'} onClick={() => setView('earnings')}>Payments · Earnings</ViewButton><ViewButton active={view === 'received'} onClick={() => setView('received')}>Received History</ViewButton></div>{view === 'earnings' && <><div style={{ display: 'flex', gap: 7, marginBottom: 10 }}>{(['daily', 'weekly', 'monthly'] as Period[]).map((item) => <PeriodButton key={item} active={period === item} onClick={() => { setPeriod(item); setAnchor(new Date()); }}>{item}</PeriodButton>)}</div><div style={{ display: 'grid', gridTemplateColumns: '42px 1fr 42px', gap: 8, alignItems: 'center' }}><button type="button" aria-label={`Previous ${period}`} onClick={() => setAnchor((current) => shiftAnchor(period, current, -1))} style={{ ...button, minHeight: 38, padding: 0 }}>‹</button><div style={{ textAlign: 'center' }}><div style={{ fontSize: 10, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '.12em', fontWeight: 900 }}>Earnings period</div><div style={{ marginTop: 2, fontSize: 15, fontWeight: 950, color: '#f8fafc' }}>{periodTitle(period, anchor)}</div></div><button type="button" aria-label={`Next ${period}`} disabled={futureDisabled} onClick={() => setAnchor((current) => shiftAnchor(period, current, 1))} style={{ ...button, minHeight: 38, padding: 0, opacity: futureDisabled ? .35 : 1, cursor: futureDisabled ? 'not-allowed' : 'pointer' }}>›</button></div></>}{view === 'received' && <div style={{ padding: '4px 2px 2px' }}><div style={{ fontSize: 10, color: '#67e8f9', textTransform: 'uppercase', letterSpacing: '.12em', fontWeight: 900 }}>Actual received ledger</div><div style={{ marginTop: 3, color: '#cbd5e1', fontSize: 12 }}>Payments and advances from worker_finance_received only.</div></div>}</section>
    <section aria-labelledby="finance-history-heading"><div style={{ display: 'flex', alignItems: 'end', justifyContent: 'space-between', gap: 10, marginBottom: 9 }}><div><div style={{ color: '#64748b', fontSize: 10, textTransform: 'uppercase', letterSpacing: '.12em', fontWeight: 900 }}>{view === 'earnings' ? 'Work Entries only' : 'Received Amount history'}</div><h2 id="finance-history-heading" style={{ margin: '3px 0 0', fontSize: 19, letterSpacing: '-.02em', color: '#f8fafc' }}>{view === 'earnings' ? 'Earnings' : 'Received History'}</h2></div><span style={{ color: '#64748b', fontSize: 11 }}>{finance.entries.length} loaded</span></div>{finance.entries.length === 0 ? <div style={{ ...lightCard, padding: 26, textAlign: 'center' }}><div style={{ fontSize: 15, fontWeight: 900 }}>No records in this view</div><div style={{ marginTop: 6, color: '#94a3b8', fontSize: 12 }}>{view === 'earnings' ? 'No real Work Entries exist for the selected period.' : 'No active received or advance records exist yet.'}</div></div> : <div style={{ display: 'grid', gap: 9 }}>{finance.entries.map((entry) => entry.kind === 'earning' ? <EarningRow key={entry.id} entry={entry.workEntry} onDetails={openDetails} /> : <ReceivedRow key={entry.id} record={entry.record} onEdit={openEdit} onDelete={setDeleteTarget} />)}</div>}{finance.hasMore && <button type="button" onClick={() => void finance.loadMore()} disabled={finance.loadingMore} style={{ ...button, width: '100%', marginTop: 10, opacity: finance.loadingMore ? .6 : 1 }}>{finance.loadingMore ? 'Loading…' : 'Load More'}</button>}</section>
    {modalOpen && <AddReceivedModal editing={editing} type={type} setType={setType} amount={amount} setAmount={setAmount} formError={formError} saving={finance.saving} onCancel={() => setModalOpen(false)} onSave={() => void submit()} />}{deleteTarget && <DeleteModal saving={finance.saving} onCancel={() => setDeleteTarget(null)} onDelete={() => void confirmDelete()} />}{(selectedEntry || detailsLoading || detailsError) && <WorkEntryDetails entry={selectedEntry} loading={detailsLoading} error={detailsError} onClose={() => { setSelectedEntry(null); setDetailsError(null); }} />}
  </main>;
}
function SummaryCard({ label, value, accent, clickable, onClick }: { label: string; value: string; accent: string; clickable?: boolean; onClick?: () => void }) { return <section role={clickable ? 'button' : undefined} tabIndex={clickable ? 0 : undefined} onClick={onClick} onKeyDown={(event) => { if (clickable && (event.key === 'Enter' || event.key === ' ')) { event.preventDefault(); onClick?.(); } }} style={{ ...lightCard, minWidth: 0, padding: 15, textAlign: 'left', cursor: clickable ? 'pointer' : 'default', borderColor: clickable ? 'rgba(52,211,153,.35)' : 'rgba(148,163,184,.18)', boxShadow: clickable ? 'inset 0 1px 0 rgba(255,255,255,.09),0 0 24px rgba(16,185,129,.1),0 18px 42px rgba(2,6,23,.28)' : lightCard.boxShadow }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 }}><span style={{ color: '#94a3b8', fontSize: 9, letterSpacing: '.1em', textTransform: 'uppercase', fontWeight: 950 }}>{label}</span>{clickable && <span style={{ color: '#6ee7b7', fontSize: 10, fontWeight: 900 }}>OPEN →</span>}</div><div style={{ marginTop: 8, fontSize: 'clamp(20px,5.5vw,30px)', letterSpacing: '-.045em', lineHeight: 1, fontWeight: 950, color: accent === 'emerald' ? '#6ee7b7' : accent === 'violet' ? '#c4b5fd' : accent === 'blue' ? '#93c5fd' : '#67e8f9' }}>{value}</div></section>; }
function ViewButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: ReactNode }) { return <button type="button" onClick={onClick} style={{ ...button, flex: 1, minHeight: 38, padding: '0 10px', fontSize: 11, borderColor: active ? 'rgba(103,232,249,.32)' : 'rgba(148,163,184,.16)', background: active ? 'linear-gradient(135deg,rgba(79,70,229,.85),rgba(8,145,178,.72))' : 'rgba(15,23,42,.6)', color: active ? '#fff' : '#94a3b8' }}>{children}</button>; }
function PeriodButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: ReactNode }) { return <button type="button" onClick={onClick} style={{ ...button, flex: 1, minHeight: 34, padding: '0 8px', fontSize: 10, textTransform: 'uppercase', letterSpacing: '.08em', background: active ? 'rgba(8,145,178,.22)' : 'rgba(15,23,42,.55)', borderColor: active ? 'rgba(103,232,249,.3)' : 'rgba(148,163,184,.12)', color: active ? '#67e8f9' : '#94a3b8' }}>{children}</button>; }
function EarningRow({ entry, onDetails }: { entry: WorkEntry; onDetails: (entry: WorkEntry) => void }) { return <article style={{ ...lightCard, padding: 14, borderLeft: '3px solid #22d3ee' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10 }}><div><div style={{ color: '#67e8f9', fontSize: 17, fontWeight: 950 }}>+ {amountLabel(entry.total)}</div><div style={{ marginTop: 4, color: '#f8fafc', fontSize: 13, fontWeight: 850 }}>{entry.item_name || 'Work Entry'}</div></div><div style={{ color: '#64748b', fontSize: 10, whiteSpace: 'nowrap' }}>{dateLabel(entry.occurred_at)}</div></div><div style={{ marginTop: 7, color: '#94a3b8', fontSize: 11 }}>Qty {formatWorkDecimal(entry.quantity)} × Rate {amountLabel(entry.rate)}</div><button type="button" onClick={() => onDetails(entry)} style={{ marginTop: 9, border: 0, padding: 0, background: 'transparent', color: '#a5b4fc', font: 'inherit', fontSize: 11, fontWeight: 850, cursor: 'pointer' }}>View Work Entry details →</button></article>; }
function ReceivedRow({ record, onEdit, onDelete }: { record: FinanceReceivedRecord; onEdit: (record: FinanceReceivedRecord) => void; onDelete: (record: FinanceReceivedRecord) => void }) { const advance = record.entry_type === 'advance'; return <article style={{ ...lightCard, padding: 14, borderLeft: `3px solid ${advance ? '#a78bfa' : '#34d399'}` }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10 }}><div><div style={{ color: advance ? '#c4b5fd' : '#6ee7b7', fontSize: 17, fontWeight: 950 }}>+ {amountLabel(record.amount)}</div><div style={{ marginTop: 4, color: '#f8fafc', fontSize: 12, fontWeight: 900 }}>{advance ? 'Advance' : 'Received Payment'}</div></div><div style={{ color: '#64748b', fontSize: 10 }}>{dateLabel(record.received_at)}</div></div><div style={{ display: 'flex', gap: 8, marginTop: 11 }}><button type="button" onClick={() => onEdit(record)} style={{ ...button, minHeight: 34, padding: '0 11px', fontSize: 11 }}>Edit</button><button type="button" onClick={() => onDelete(record)} style={{ ...button, minHeight: 34, padding: '0 11px', fontSize: 11, color: '#fda4af', borderColor: 'rgba(244,63,94,.25)' }}>Delete</button></div></article>; }
function AddReceivedModal({ editing, type, setType, amount, setAmount, formError, saving, onCancel, onSave }: { editing: FinanceReceivedRecord | null; type: FinanceReceivedType; setType: (type: FinanceReceivedType) => void; amount: string; setAmount: (value: string) => void; formError: string | null; saving: boolean; onCancel: () => void; onSave: () => void }) { return <div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onCancel(); }} style={{ position: 'fixed', inset: 0, zIndex: 1300, display: 'flex', alignItems: 'flex-end', justifyContent: 'center', padding: '0 8px 8px', background: 'rgba(2,6,23,.68)', backdropFilter: 'blur(8px)' }}><section role="dialog" aria-modal="true" aria-labelledby="received-modal-title" style={{ width: '100%', maxWidth: 560, padding: 16, borderRadius: 22, border: '1px solid rgba(103,232,249,.18)', background: 'linear-gradient(145deg,#172033,#0f172a)', boxShadow: '0 -10px 42px rgba(0,0,0,.35)' }}><h2 id="received-modal-title" style={{ margin: 0, color: '#f8fafc', fontSize: 18 }}>{editing ? 'Edit Received' : 'Add Received'}</h2><div style={{ marginTop: 14, display: 'grid', gap: 11 }}><div><div style={{ color: '#94a3b8', fontSize: 10, fontWeight: 900, textTransform: 'uppercase', letterSpacing: '.1em', marginBottom: 6 }}>Type</div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 7 }}><button type="button" onClick={() => setType('payment')} disabled={saving} style={{ ...button, color: type === 'payment' ? '#fff' : '#94a3b8', background: type === 'payment' ? 'rgba(16,185,129,.2)' : 'rgba(15,23,42,.65)' }}>Payment</button><button type="button" onClick={() => setType('advance')} disabled={saving} style={{ ...button, color: type === 'advance' ? '#fff' : '#94a3b8', background: type === 'advance' ? 'rgba(139,92,246,.2)' : 'rgba(15,23,42,.65)' }}>Advance</button></div></div><label style={{ color: '#94a3b8', fontSize: 10, fontWeight: 900, textTransform: 'uppercase', letterSpacing: '.1em' }}>Amount<input value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal" disabled={saving} style={{ display: 'block', width: '100%', boxSizing: 'border-box', marginTop: 6, minHeight: 46, padding: '0 12px', borderRadius: 13, border: '1px solid rgba(148,163,184,.2)', background: 'rgba(2,6,23,.45)', color: '#f8fafc', font: 'inherit', fontSize: 16 }} /></label>{formError && <p role="alert" style={{ margin: 0, color: '#fca5a5', fontSize: 12 }}>{formError}</p>}<div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}><button type="button" onClick={onCancel} disabled={saving} style={button}>Cancel</button><button type="button" onClick={onSave} disabled={saving} style={{ ...button, background: 'linear-gradient(135deg,#4f46e5,#0891b2)', borderColor: 'rgba(103,232,249,.3)', color: '#fff' }}>{saving ? 'Saving…' : editing ? 'Save changes' : 'Add'}</button></div></div></section></div>; }
function DeleteModal({ saving, onCancel, onDelete }: { saving: boolean; onCancel: () => void; onDelete: () => void }) { return <div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onCancel(); }} style={{ position: 'fixed', inset: 0, zIndex: 1350, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 18, background: 'rgba(2,6,23,.68)', backdropFilter: 'blur(8px)' }}><section role="dialog" aria-modal="true" aria-labelledby="delete-title" style={{ width: '100%', maxWidth: 380, padding: 18, borderRadius: 20, border: '1px solid rgba(244,63,94,.2)', background: '#111827', boxShadow: '0 22px 60px rgba(0,0,0,.4)' }}><h2 id="delete-title" style={{ margin: 0, color: '#f8fafc', fontSize: 17 }}>Delete received record?</h2><p style={{ color: '#94a3b8', fontSize: 12, lineHeight: 1.5 }}>The record will be soft-deleted and can still be restored.</p><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}><button type="button" onClick={onCancel} disabled={saving} style={button}>Cancel</button><button type="button" onClick={onDelete} disabled={saving} style={{ ...button, color: '#fecdd3', borderColor: 'rgba(244,63,94,.3)' }}>{saving ? 'Deleting…' : 'Delete'}</button></div></section></div>; }
function WorkEntryDetails({ entry, loading, error, onClose }: { entry: WorkEntry | null; loading: boolean; error: string | null; onClose: () => void }) { return <div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }} style={{ position: 'fixed', inset: 0, zIndex: 1250, display: 'flex', alignItems: 'flex-end', justifyContent: 'center', padding: '0 8px 8px', background: 'rgba(2,6,23,.64)', backdropFilter: 'blur(8px)' }}><section role="dialog" aria-modal="true" aria-labelledby="entry-details-title" style={{ width: '100%', maxWidth: 560, padding: 18, borderRadius: 22, border: '1px solid rgba(99,102,241,.2)', background: 'linear-gradient(145deg,#172033,#0f172a)', boxShadow: '0 -10px 42px rgba(0,0,0,.35)' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}><h2 id="entry-details-title" style={{ margin: 0, color: '#f8fafc', fontSize: 18 }}>Work Entry details</h2><button type="button" onClick={onClose} style={{ ...button, minHeight: 34, width: 34, padding: 0 }}>×</button></div>{loading ? <p style={{ color: '#94a3b8' }}>Loading…</p> : error ? <p role="alert" style={{ color: '#fca5a5' }}>{error}</p> : entry ? <div style={{ marginTop: 14, display: 'grid', gap: 9, color: '#cbd5e1', fontSize: 12 }}><div><strong style={{ color: '#f8fafc' }}>{entry.item_name}</strong></div><div>Earnings: <strong style={{ color: '#67e8f9' }}>{amountLabel(entry.total)}</strong></div><div>Quantity: {formatWorkDecimal(entry.quantity)}</div><div>Rate: {amountLabel(entry.rate)}</div><div>Date: {dateLabel(entry.occurred_at)}</div>{entry.special_note && <div>Note: {entry.special_note}</div>}</div> : null}</section></div>; }
