import { useEffect, useState } from 'react';
import type { ProfileUpdateInput } from '../api/updateProfile';
import { getProfile } from '../api/getProfile';
import { updateProfile } from '../api/updateProfile';
import { AvatarUploader } from './AvatarUploader';
import { PostFeed } from '../../posts/components/PostFeed';
import { supabase } from '../../../lib/supabase/client';

type Profile = { id:string; username:string; display_name:string; bio:string|null; avatar_url:string|null; date_of_birth:string|null; gender:string|null; location:string|null; website:string|null; created_at:string; updated_at:string; };
interface ProfilePanelProps { profileId:string; viewerId?:string; }
function formatJoinedDate(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString(undefined,{year:'numeric',month:'long'});}
export function ProfilePanel({profileId,viewerId}:ProfilePanelProps){
 const isOwner=!viewerId||viewerId===profileId; const [profile,setProfile]=useState<Profile|null>(null); const [form,setForm]=useState<ProfileUpdateInput>({display_name:'',bio:'',date_of_birth:'',gender:'',location:'',website:''}); const [editing,setEditing]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const [saved,setSaved]=useState(false); const [following,setFollowing]=useState(false); const [friend,setFriend]=useState(false); const [friendPending,setFriendPending]=useState(false); const [busyAction,setBusyAction]=useState(false);
 useEffect(()=>{let active=true;(async()=>{setLoading(true);setError(null);const {data,error:e}=await getProfile(profileId);if(!active)return;if(e||!data){setProfile(null);setError(e?.message??'Profile could not be loaded.');setLoading(false);return;}const p=data as Profile;setProfile(p);setForm({display_name:p.display_name??'',bio:p.bio??'',date_of_birth:p.date_of_birth??'',gender:p.gender??'',location:p.location??'',website:p.website??''});setLoading(false);})();return()=>{active=false};},[profileId]);
 useEffect(()=>{if(isOwner||!viewerId)return;let active=true;(async()=>{const [{data:follows,error:fe},{data:friends,error:fre},{data:req,error:re}]=await Promise.all([supabase.from('follows').select('following_id').eq('follower_id',viewerId).eq('following_id',profileId).maybeSingle(),supabase.from('friends').select('profile_a_id, profile_b_id').or(`and(profile_a_id.eq.${viewerId},profile_b_id.eq.${profileId}),and(profile_a_id.eq.${profileId},profile_b_id.eq.${viewerId})`).maybeSingle(),supabase.from('friend_requests').select('id').eq('sender_id',viewerId).eq('receiver_id',profileId).eq('status','pending').maybeSingle()]);if(!active)return;const e=fe??fre??re;if(e){setError(e.message);return;}setFollowing(Boolean(follows));setFriend(Boolean(friends));setFriendPending(Boolean(req));})();return()=>{active=false};},[isOwner,viewerId,profileId]);
 const openEditor=()=>{if(!profile||!isOwner)return;setForm({display_name:profile.display_name??'',bio:profile.bio??'',date_of_birth:profile.date_of_birth??'',gender:profile.gender??'',location:profile.location??'',website:profile.website??''});setError(null);setSaved(false);setEditing(true);};
 const handleSave=async()=>{if(!profile||!isOwner)return;const normalized={display_name:form.display_name.trim(),bio:form.bio.trim(),date_of_birth:form.date_of_birth,gender:form.gender,location:form.location.trim(),website:form.website.trim()};if(!normalized.display_name){setError('Display name is required.');return;}setSaving(true);setError(null);const {data,e}=await updateProfile(profileId,normalized);if(e||!data){setError(e?.message??'Profile could not be saved.');setSaving(false);return;}setProfile(data as Profile);setEditing(false);setSaved(true);setSaving(false);};
 const toggleFollow=async()=>{if(!viewerId||isOwner||busyAction)return;setBusyAction(true);setError(null);const r=following?await supabase.from('follows').delete().eq('follower_id',viewerId).eq('following_id',profileId):await supabase.from('follows').insert({follower_id:viewerId,following_id:profileId});if(r.error)setError(r.error.message);else setFollowing(!following);setBusyAction(false);};
 const sendFriendRequest=async()=>{if(!viewerId||isOwner||friend||friendPending||busyAction)return;setBusyAction(true);setError(null);const {error:e}=await supabase.from('friend_requests').insert({sender_id:viewerId,receiver_id:profileId,status:'pending'});if(e)setError(e.message);else setFriendPending(true);setBusyAction(false);};
 const chatWithProfile=async()=>{if(!viewerId||isOwner||busyAction)return;setBusyAction(true);setError(null);const {data:conversation,error:e}=await supabase.rpc('create_direct_conversation',{target_profile:profileId});if(e||!conversation){setError(e?.message??'Could not open chat.');setBusyAction(false);return;}window.location.assign(`/inbox?conversation=${encodeURIComponent(conversation)}`);};
 if(loading)return <section className="foundation-card"><p>Loading profile…</p></section>;if(error&&!profile)return <section className="foundation-card"><p role="alert">{error}</p></section>;if(!profile)return <section className="foundation-card"><p>Profile not found.</p></section>;
 if(editing&&isOwner)return <section className="foundation-card"><h2>Edit your profile</h2><AvatarUploader userId={profileId} avatarUrl={profile.avatar_url} onUploaded={(url)=>setProfile(p=>p?{...p,avatar_url:url}:p)}/><label>Display name<input value={form.display_name} onChange={e=>setForm(v=>({...v,display_name:e.target.value}))}/></label><label>Bio<textarea value={form.bio} onChange={e=>setForm(v=>({...v,bio:e.target.value}))}/></label><label>Date of birth<input type="date" value={form.date_of_birth} onChange={e=>setForm(v=>({...v,date_of_birth:e.target.value}))}/></label><label>Gender<select value={form.gender} onChange={e=>setForm(v=>({...v,gender:e.target.value}))}><option value="">Prefer not to say</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="other">Other</option></select></label><label>Location<input value={form.location} onChange={e=>setForm(v=>({...v,location:e.target.value}))}/></label><label>Website<input type="url" value={form.website} onChange={e=>setForm(v=>({...v,website:e.target.value}))}/></label>{error&&<p role="alert">{error}</p>}<button type="button" onClick={()=>void handleSave()} disabled={saving}>{saving?'Saving…':'Save profile'}</button><button type="button" onClick={()=>setEditing(false)} disabled={saving}>Cancel</button></section>;
 return <section><section className="foundation-card" style={{textAlign:'center'}}>{profile.avatar_url?<img src={profile.avatar_url} alt={`${profile.display_name} profile`} width={112} height={112} style={{borderRadius:'50%',objectFit:'cover'}}/>:<div aria-hidden="true">👤</div>}<h2>{profile.display_name}</h2><p>@{profile.username}</p>{profile.bio&&<p>{profile.bio}</p>}<div style={{display:'flex',justifyContent:'center',flexWrap:'wrap',gap:8}}>{isOwner?<><button type="button" onClick={()=>window.location.assign('/friends')}>Friends</button><button type="button" onClick={openEditor}>Edit</button></>:<><button type="button" onClick={()=>void chatWithProfile()} disabled={busyAction}>💬 Chat with {profile.display_name}</button><button type="button" onClick={()=>void toggleFollow()} disabled={busyAction}>{following?'Following':'Follow'}</button><button type="button" onClick={()=>void sendFriendRequest()} disabled={busyAction||friend}>{friend?'Friends':friendPending?'Request sent':'Add as Friend'}</button></>}</div>{error&&<p role="alert">{error}</p>}{saved&&<p role="status">Profile saved.</p>}</section><section style={{marginTop:20}}><PostFeed refreshKey={0} profileId={profileId} feedProfileId={profileId} scope="profile"/></section><footer className="foundation-card" style={{marginTop:20,textAlign:'center'}}><p>Joined {formatJoinedDate(profile.created_at)}</p></footer></section>;
}
