import { useEffect, useState } from 'react';
import { navigate } from '../../../app/Router';
import { supabase } from '../../../lib/supabase/client';

interface Props { profileId: string; teamNumber: string; }
type Team = { team_number: number; name: string; purpose: string; created_at: string };
const shell={width:'100%',maxWidth:760,minHeight:'100%',margin:'0 auto',padding:'14px 12px 104px',boxSizing:'border-box' as const,background:'radial-gradient(circle at 8% 0%,rgba(16,185,129,.14),transparent 30%),radial-gradient(circle at 92% 12%,rgba(14,165,233,.12),transparent 28%)'};
const card={padding:16,border:'1px solid rgba(255,255,255,.82)',borderRadius:18,background:'linear-gradient(145deg,rgba(255,255,255,.98),rgba(248,250,252,.92))',boxShadow:'0 18px 42px rgba(15,23,42,.10),inset 0 1px 0 rgba(255,255,255,.95)'};
export function ContractorTeamSettingsPage({profileId,teamNumber}:Props){
 const [team,setTeam]=useState<Team|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const parsed=Number(teamNumber);if(!Number.isSafeInteger(parsed)||parsed<100001){setError('Invalid Team ID.');setLoading(false);return;}const {data,error:e}=await supabase.from('contractor_teams').select('team_number,name,purpose,created_at').eq('leader_profile_id',profileId).eq('team_number',parsed).maybeSingle<Team>();if(e){setError(e.message);setLoading(false);return;}if(!data){setError('This team could not be found in your Contractor workspace.');setLoading(false);return;}setTeam(data);setLoading(false)};
 useEffect(()=>{void load()},[profileId,teamNumber]);
 if(loading)return <main style={shell}><section style={{...card,marginTop:18}}><strong>Loading Team Settings…</strong><p style={{margin:'6px 0 0',color:'#64748b',fontSize:12}}>Loading your real team configuration.</p></section></main>;
 if(error||!team)return <main style={shell}><section style={{...card,marginTop:18}} role="alert"><strong style={{color:'#991b1b'}}>Unable to load Team Settings</strong><p style={{color:'#64748b',fontSize:12}}>{error||'Team unavailable.'}</p><button type="button" onClick={()=>void load()} style={{minHeight:38,padding:'0 12px',border:0,borderRadius:10,background:'#047857',color:'#fff',fontWeight:900}}>Retry</button></section></main>;
 return <main style={shell}><header style={{...card,marginTop:2}}><div style={{display:'flex',alignItems:'center',gap:9}}><button type="button" onClick={()=>navigate(`/work/contractor?view=team&team=${team.team_number}`)} aria-label="Back to Team Dashboard" style={{width:38,height:38,border:'1px solid rgba(100,116,139,.14)',borderRadius:12,background:'#fff',color:'#334155',fontSize:20,fontWeight:950,cursor:'pointer'}}>‹</button><div><div style={{color:'#059669',fontSize:9,fontWeight:950,letterSpacing:'.14em'}}>TEAM SETTINGS</div><h1 style={{margin:'4px 0 0',fontSize:28,letterSpacing:'-.045em'}}>Team Settings</h1></div></div><p style={{margin:'12px 0 0',color:'#64748b',fontSize:11,lineHeight:1.5}}>Real configuration for your Contractor team. No membership or finance data is changed from this screen.</p></header><section style={{...card,marginTop:10,display:'grid',gap:10}}><Info title="Team Name">{team.name}</Info><Info title="Team ID">{team.team_number}</Info><Info title="Purpose">{team.purpose||'No purpose provided.'}</Info><Info title="Created">{new Intl.DateTimeFormat('en-PK',{timeZone:'Asia/Karachi',dateStyle:'medium'}).format(new Date(team.created_at))}</Info></section><section style={{...card,marginTop:10}}><strong style={{fontSize:13}}>Workspace navigation</strong><p style={{margin:'5px 0 12px',color:'#64748b',fontSize:10}}>Switching or exiting the team only changes the active workspace URL. Your team membership remains untouched.</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><button type="button" onClick={()=>navigate(`/work/contractor?view=team&team=${team.team_number}`)} style={button}>Team Dashboard</button><button type="button" onClick={()=>navigate('/work/contractor?view=dashboard')} style={button}>Exit Team</button></div></section></main>;
}
function Info({title,children}:{title:string;children:React.ReactNode}){return <div style={{padding:12,borderRadius:14,border:'1px solid rgba(5,150,105,.14)',background:'linear-gradient(145deg,#ecfdf5,#eff6ff)'}}><div style={{fontSize:9,color:'#64748b',fontWeight:950,letterSpacing:'.1em',textTransform:'uppercase'}}>{title}</div><div style={{marginTop:4,color:'#172033',fontSize:13,fontWeight:850,overflowWrap:'anywhere'}}>{children}</div></div>}
const button={minHeight:42,borderRadius:11,border:'1px solid rgba(5,150,105,.2)',background:'linear-gradient(145deg,#ecfdf5,#dbeafe)',color:'#047857',fontWeight:900,cursor:'pointer'};
