import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { navigate } from '../../../app/Router';
import { supabase } from '../../../lib/supabase/client';
import { AccountModeSwitchCard } from '../../account/components/AccountModeSwitchCard';
import { ContractorPersonalDashboard } from '../components/ContractorPersonalDashboard';
import { ContractorTeamPersonalDashboard } from '../components/ContractorTeamPersonalDashboard';
import { ContractorCreateTeamWorkflow } from '../components/ContractorCreateTeamWorkflow';
import { ContractorTeamListMenu } from '../components/ContractorTeamListMenu';
import { ContractorAddMembersWorkflow } from '../components/ContractorAddMembersWorkflow';
import { ContractorTeamPage } from './ContractorTeamPage';
import { ContractorTeamSettingsPage } from './ContractorTeamSettingsPage';
import { ContractorOverviewPage } from './ContractorOverviewPage';
import { ContractorTeamDetailPage } from './ContractorTeamDetailPage';

type Profile={id:string;display_name:string|null;username:string|null;avatar_url:string|null};
type ContractorAccount={profile_id:string;contractor_id:string;is_commission_based:boolean;work_types:string[];works_with:string[];business_name:string|null};
const WORK_TYPES=['Manufacturing / Production','Stitching / Garments','Packaging','Construction','Services','Other'] as const;
const WORKS_WITH=['Workers','Teams'] as const;
const shell={width:'100%',maxWidth:760,minHeight:'100%',margin:'0 auto',padding:'18px 12px 104px',boxSizing:'border-box' as const,background:'radial-gradient(circle at 8% 0%,rgba(16,185,129,.14),transparent 30%),radial-gradient(circle at 92% 12%,rgba(14,165,233,.12),transparent 28%)'};
const card={padding:16,border:'1px solid rgba(255,255,255,.78)',borderRadius:18,background:'linear-gradient(145deg,rgba(255,255,255,.97),rgba(248,250,252,.9))',boxShadow:'0 18px 42px rgba(15,23,42,.10),inset 0 1px 0 rgba(255,255,255,.95)'};
const input={width:'100%',minHeight:44,padding:'0 12px',boxSizing:'border-box' as const,border:'1px solid rgba(100,116,139,.2)',borderRadius:12,background:'rgba(255,255,255,.9)',color:'#172033',font:'inherit',outline:'none'};
function initials(name:string){const v=name.trim();return v?v.split(/\s+/).slice(0,2).map(x=>x.charAt(0)).join('').toUpperCase():'C'}
export function ContractorAccountPage(){
 const [profile,setProfile]=useState<Profile|null>(null),[account,setAccount]=useState<ContractorAccount|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[commissionBased,setCommissionBased]=useState<boolean|null>(null),[workTypes,setWorkTypes]=useState<string[]>([]),[worksWith,setWorksWith]=useState<string[]>([]),[businessName,setBusinessName]=useState('');
 const query=new URLSearchParams(window.location.search);const view=query.get('view');const teamNumber=query.get('team');const teamId=query.get('team_id');const editing=view==='setup';
 const load=async()=>{setLoading(true);setError('');const u=await supabase.auth.getUser();if(u.error||!u.data.user){setError(u.error?.message||'Authenticated identity is unavailable.');setLoading(false);return;}const p=await supabase.from('profiles').select('id,display_name,username,avatar_url').eq('id',u.data.user.id).maybeSingle<Profile>();if(p.error||!p.data){setError(p.error?.message||'Profile could not be loaded.');setLoading(false);return;}setProfile(p.data);const a=await supabase.from('contractor_accounts').select('profile_id,contractor_id,is_commission_based,work_types,works_with,business_name').eq('profile_id',u.data.user.id).maybeSingle<ContractorAccount>();if(a.error){setError(a.error.message);setLoading(false);return;}if(a.data){setAccount(a.data);setCommissionBased(a.data.is_commission_based);setWorkTypes(a.data.work_types??[]);setWorksWith(a.data.works_with??[]);setBusinessName(a.data.business_name??'')}setLoading(false)};
 useEffect(()=>{void load()},[]);
 const toggle=(values:string[],value:string,setter:(v:string[])=>void)=>setter(values.includes(value)?values.filter(x=>x!==value):[...values,value]);
 const save=async()=>{if(!profile)return;if(commissionBased===null)return setError('Please choose whether you are a commission-based contractor.');if(!workTypes.length)return setError('Please select at least one contracting work type.');if(!worksWith.length)return setError('Please select workers, teams, or both.');setSaving(true);setError('');const r=await supabase.from('contractor_accounts').upsert({profile_id:profile.id,is_commission_based:commissionBased,work_types:workTypes,works_with:worksWith,business_name:businessName.trim()||null},{onConflict:'profile_id'}).select('profile_id,contractor_id,is_commission_based,work_types,works_with,business_name').single<ContractorAccount>();setSaving(false);if(r.error||!r.data){setError(r.error?.message||'Contractor profile could not be saved.');return;}setAccount(r.data);setSaved(true);window.setTimeout(()=>navigate('/work/contractor?view=overview'),500)};
 if(loading)return <main style={shell}><section style={{...card,marginTop:18}}><strong>Loading Contractor Account…</strong></section></main>;
 if(!profile)return <main style={shell}><section style={{...card,marginTop:18}} role="alert"><strong>Unable to load Contractor Account</strong><p style={{color:'#64748b',fontSize:12}}>{error}</p><button type="button" onClick={()=>void load()}>Retry</button></section></main>;
 if(account&&!editing&&(!view||view==='overview'))return <ContractorOverviewPage profileId={profile.id}/>;
 if(account&&!editing&&view==='team-detail'&&teamId&&teamNumber)return <ContractorTeamDetailPage profileId={profile.id} teamId={teamId} teamNumber={teamNumber}/>;
 if(account&&!editing&&view==='dashboard')return <><ContractorPersonalDashboard profileId={profile.id} displayName={profile.display_name}/><ContractorCreateTeamWorkflow profileId={profile.id}/><ContractorTeamListMenu profileId={profile.id}/></>;
 if(account&&!editing&&view==='team-dashboard'&&teamNumber)return <ContractorTeamPersonalDashboard profileId={profile.id} displayName={profile.display_name} teamNumber={teamNumber}/>;
 if(account&&!editing&&view==='team-work'&&teamNumber)return <><ContractorTeamPage profileId={profile.id} teamNumber={teamNumber}/><ContractorAddMembersWorkflow profileId={profile.id} teamNumber={teamNumber}/></>;
 if(account&&!editing&&view==='team'&&teamNumber)return <><ContractorTeamPage profileId={profile.id} teamNumber={teamNumber}/><ContractorAddMembersWorkflow profileId={profile.id} teamNumber={teamNumber}/></>;
 if(account&&!editing&&view==='team-settings'&&teamNumber)return <ContractorTeamSettingsPage profileId={profile.id} teamNumber={teamNumber}/>;
 if(account&&!editing&&view==='settings')return <main style={shell}><header style={{marginBottom:14}}><div style={{color:'#059669',fontSize:10,fontWeight:900,letterSpacing:'.12em'}}>CONTRACTOR ACCOUNT</div><h1 style={{margin:'4px 0',fontSize:34}}>Settings</h1></header><section style={{...card,display:'grid',gap:10}}><Info title="Contractor ID">{account.contractor_id}</Info><Info title="Commission-based contractor">{account.is_commission_based?'Yes':'No'}</Info><Info title="Contracting work">{account.work_types.join(' · ')}</Info><Info title="Works with">{account.works_with.join(' · ')}</Info><Info title="Company / Business Name">{account.business_name||'Not provided'}</Info></section><button type="button" onClick={()=>navigate('/work/contractor?view=setup')} style={{width:'100%',marginTop:12,minHeight:46,borderRadius:12,border:'1px solid rgba(5,150,105,.26)',background:'linear-gradient(145deg,#ecfdf5,#d1fae5)',color:'#047857',fontWeight:900}}>Edit Contractor Setup</button><div style={{marginTop:12}}><AccountModeSwitchCard currentMode="contractor" profileId={profile.id}/></div></main>;
 return <main style={shell}><header style={{marginBottom:14}}><div style={{color:'#059669',fontSize:10,fontWeight:900,letterSpacing:'.12em'}}>CONTRACTOR ACCOUNT SETUP</div><h1 style={{margin:'4px 0',fontSize:34,letterSpacing:'-.045em'}}>{editing?'Edit your Contractor Account':'Set up your Contractor Account'}</h1><p style={{color:'#64748b',fontSize:12}}>Real Contractor identity and workflow setup.</p></header><section style={{...card,display:'grid',gap:17}}><div style={{display:'flex',alignItems:'center',gap:12}}>{profile.avatar_url?<img src={profile.avatar_url} alt="Profile" width={58} height={58} style={{width:58,height:58,objectFit:'cover',borderRadius:17}}/>:<div style={{width:58,height:58,display:'grid',placeItems:'center',borderRadius:17,background:'linear-gradient(145deg,#d1fae5,#dbeafe)',color:'#047857',fontWeight:950}}>{initials(profile.display_name??'')}</div>}<div><strong>{profile.display_name||'Your profile'}</strong>{profile.username&&<div style={{fontSize:11,color:'#64748b'}}>@{profile.username}</div>}</div></div><fieldset style={{border:0,padding:0,margin:0}}><legend style={{fontWeight:900,fontSize:14}}>Commission-based contractor?</legend><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}>{[true,false].map(v=><Choice key={String(v)} selected={commissionBased===v} onClick={()=>setCommissionBased(v)}>{v?'Yes':'No'}</Choice>)}</div></fieldset><fieldset style={{border:0,padding:0,margin:0}}><legend style={{fontWeight:900,fontSize:14}}>Contracting work</legend><div style={{display:'grid',gap:7,marginTop:8}}>{WORK_TYPES.map(v=><Choice key={v} selected={workTypes.includes(v)} onClick={()=>toggle(workTypes,v,setWorkTypes)}>{v}</Choice>)}</div></fieldset><fieldset style={{border:0,padding:0,margin:0}}><legend style={{fontWeight:900,fontSize:14}}>Works with</legend><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}>{WORKS_WITH.map(v=><Choice key={v} selected={worksWith.includes(v)} onClick={()=>toggle(worksWith,v,setWorksWith)}>{v}</Choice>)}</div></fieldset><label style={{display:'grid',gap:7,fontWeight:900,fontSize:14}}>Company / Business Name <span style={{fontSize:10,color:'#94a3b8'}}>Optional</span><input value={businessName} onChange={e=>setBusinessName(e.target.value)} maxLength={160} placeholder="Optional business name" style={input}/></label>{error&&<div role="alert" style={{padding:10,borderRadius:11,background:'#fff7f7',color:'#b91c1c',fontSize:11}}>{error}</div>}<button type="button" disabled={saving} onClick={()=>void save()} style={{minHeight:48,border:0,borderRadius:13,background:'linear-gradient(145deg,#059669,#047857)',color:'#fff',fontWeight:950}}>{saving?'Saving…':editing?'Save Changes':'Save Contractor Profile'}</button>{saved&&<div role="status" style={{padding:12,borderRadius:12,background:'#ecfdf5',color:'#047857',fontWeight:900}}>Saved Successfully ✓</div>}</section></main>;
}
function Info({title,children}:{title:string;children:ReactNode}){return <div style={{padding:12,borderRadius:14,border:'1px solid rgba(5,150,105,.14)',background:'linear-gradient(145deg,#ecfdf5,#eff6ff)'}}><span style={{fontSize:10,color:'#64748b',fontWeight:850,textTransform:'uppercase',letterSpacing:'.08em'}}>{title}</span><div style={{marginTop:5,fontSize:13,fontWeight:800}}>{children}</div></div>}
function Choice({selected,onClick,children}:{selected:boolean;onClick:()=>void;children:ReactNode}){return <button type="button" aria-pressed={selected} onClick={onClick} style={{minHeight:44,padding:'9px 11px',borderRadius:12,border:selected?'1px solid rgba(5,150,105,.42)':'1px solid rgba(100,116,139,.2)',background:selected?'linear-gradient(145deg,#ecfdf5,#d1fae5)':'linear-gradient(145deg,#fff,#f8fafc)',color:selected?'#047857':'#334155',fontWeight:850,textAlign:'left'}}><span style={{marginRight:7}}>{selected?'✓':'○'}</span>{children}</button>}
