import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { navigate } from '../../../app/Router';
import { AccountModeSwitchCard } from '../../account/components/AccountModeSwitchCard';
import { supabase } from '../../../lib/supabase/client';
import { ContractorPersonalDashboard } from '../components/ContractorPersonalDashboard';
import { ContractorCreateTeamWorkflow } from '../components/ContractorCreateTeamWorkflow';
import { ContractorTeamListMenu } from '../components/ContractorTeamListMenu';
import { ContractorAddMembersWorkflow } from '../components/ContractorAddMembersWorkflow';
import { ContractorTeamPage } from './ContractorTeamPage';
import { ContractorTeamSettingsPage } from './ContractorTeamSettingsPage';

type Profile={id:string;display_name:string|null;username:string|null;avatar_url:string|null};
type ContractorAccount={profile_id:string;contractor_id:string;is_commission_based:boolean;work_types:string[];works_with:string[];business_name:string|null};
const WORK_TYPES=['Manufacturing / Production','Stitching / Garments','Packaging','Construction','Services','Other'] as const;
const WORKS_WITH=['Workers','Teams'] as const;
const shell={width:'100%',maxWidth:760,minHeight:'100%',margin:'0 auto',padding:'18px 12px 104px',boxSizing:'border-box' as const,background:'radial-gradient(circle at 8% 0%,rgba(16,185,129,.14),transparent 30%),radial-gradient(circle at 92% 12%,rgba(14,165,233,.12),transparent 28%)'};
const card={padding:16,border:'1px solid rgba(255,255,255,.78)',borderRadius:18,background:'linear-gradient(145deg,rgba(255,255,255,.97),rgba(248,250,252,.9))',boxShadow:'0 18px 42px rgba(15,23,42,.10),inset 0 1px 0 rgba(255,255,255,.95)',backdropFilter:'blur(14px)',WebkitBackdropFilter:'blur(14px)'};
const input={width:'100%',minHeight:44,padding:'0 12px',boxSizing:'border-box' as const,border:'1px solid rgba(100,116,139,.2)',borderRadius:12,background:'rgba(255,255,255,.9)',color:'#172033',font:'inherit',outline:'none'};
function initials(name:string){const v=name.trim();return v?v.split(/\s+/).slice(0,2).map(x=>x.charAt(0)).join('').toUpperCase():'C'}
export function ContractorAccountPage(){
 const [profile,setProfile]=useState<Profile|null>(null);const [account,setAccount]=useState<ContractorAccount|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [copied,setCopied]=useState(false);const [commissionBased,setCommissionBased]=useState<boolean|null>(null);const [workTypes,setWorkTypes]=useState<string[]>([]);const [worksWith,setWorksWith]=useState<string[]>([]);const [businessName,setBusinessName]=useState('');
 const view=new URLSearchParams(window.location.search).get('view');const teamNumber=new URLSearchParams(window.location.search).get('team');const editing=Boolean(account)&&view==='setup';const showSetup=!account||view==='setup';
 const load=async()=>{setLoading(true);setError('');const {data:u,error:ue}=await supabase.auth.getUser();if(ue||!u.user){setError(ue?.message??'Authenticated Work Social identity is unavailable.');setLoading(false);return;}const p=await supabase.from('profiles').select('id,display_name,username,avatar_url').eq('id',u.user.id).maybeSingle<Profile>();if(p.error||!p.data){setError(p.error?.message??'Your Work Social profile could not be loaded.');setLoading(false);return;}setProfile(p.data);const a=await supabase.from('contractor_accounts').select('profile_id,contractor_id,is_commission_based,work_types,works_with,business_name').eq('profile_id',u.user.id).maybeSingle<ContractorAccount>();if(a.error){setError(a.error.message);setLoading(false);return;}if(a.data){setAccount(a.data);setCommissionBased(a.data.is_commission_based);setWorkTypes(a.data.work_types??[]);setWorksWith(a.data.works_with??[]);setBusinessName(a.data.business_name??'')}setLoading(false)};
 useEffect(()=>{void load()},[]);useEffect(()=>{if(!copied)return;const timer=window.setTimeout(()=>setCopied(false),1800);return()=>window.clearTimeout(timer)},[copied]);
 const toggle=(values:string[],value:string,setter:(v:string[])=>void)=>setter(values.includes(value)?values.filter(x=>x!==value):[...values,value]);
 const copyContractorId=async()=>{if(!account?.contractor_id||!navigator.clipboard)return;try{await navigator.clipboard.writeText(account.contractor_id);setCopied(true)}catch{setCopied(false)}};
 const save=async()=>{setError('');if(commissionBased===null)return setError('Please choose whether you are a commission-based contractor.');if(!workTypes.length)return setError('Please select at least one contracting work type.');if(!worksWith.length)return setError('Please select whether you work with workers, teams, or both.');if(!profile)return setError('Your Work Social profile is unavailable.');setSaving(true);const {data,error:e}=await supabase.from('contractor_accounts').upsert({profile_id:profile.id,is_commission_based:commissionBased,work_types:workTypes,works_with:worksWith,business_name:businessName.trim()||null},{onConflict:'profile_id'}).select('profile_id,contractor_id,is_commission_based,work_types,works_with,business_name').single<ContractorAccount>();setSaving(false);if(e||!data)return setError(e?.message??'Contractor profile could not be saved.');setAccount(data);setSaved(true);window.setTimeout(()=>navigate(editing?'/work/contractor?view=settings':'/work/contractor?view=dashboard'),700)};
 if(loading)return <main style={shell}><section style={{...card,marginTop:18}}><strong>Loading Contractor Account…</strong><p style={{margin:'6px 0 0',color:'#64748b',fontSize:12}}>Loading your real Work Social identity and Contractor setup.</p></section></main>;
 if(error&&!profile)return <main style={shell}><section style={{...card,marginTop:18}} role="alert"><strong style={{color:'#991b1b'}}>Unable to load Contractor Account</strong><p style={{color:'#64748b',fontSize:12}}>{error}</p><button type="button" onClick={()=>void load()}>Retry</button></section></main>;
 if(!profile)return null;
 const profileCard=<section style={{...card,display:'flex',alignItems:'center',gap:12,marginBottom:14}}>{profile.avatar_url?<img src={profile.avatar_url} alt="Profile picture" width={62} height={62} style={{width:62,height:62,objectFit:'cover',borderRadius:18}}/>:<div style={{width:62,height:62,display:'grid',placeItems:'center',borderRadius:18,background:'linear-gradient(145deg,#d1fae5,#dbeafe)',color:'#047857',fontSize:21,fontWeight:950}}>{initials(profile.display_name??'')}</div>}<div style={{minWidth:0,flex:1}}><div style={{color:'#059669',fontSize:9,fontWeight:900,letterSpacing:'.12em',textTransform:'uppercase'}}>Work Social Identity</div><h2 style={{margin:'3px 0',color:'#172033',fontSize:20,letterSpacing:'-.03em',overflowWrap:'anywhere'}}>{profile.display_name||'Your profile'}</h2>{profile.username&&<div style={{marginTop:2,color:'#64748b',fontSize:12}}>@{profile.username}</div>}{account?.contractor_id&&<div style={{marginTop:9,display:'flex',alignItems:'center',gap:7,flexWrap:'wrap'}}><span style={{color:'#64748b',fontSize:9,fontWeight:900,letterSpacing:'.08em',textTransform:'uppercase'}}>Contractor ID</span><code style={{fontSize:11,fontWeight:900,color:'#065f46',overflowWrap:'anywhere'}}>{account.contractor_id}</code><button type="button" onClick={()=>void copyContractorId()} style={{minHeight:28,padding:'0 9px',borderRadius:8,border:'1px solid rgba(5,150,105,.18)',background:'linear-gradient(145deg,#fff,#ecfdf5)',color:copied?'#166534':'#047857',fontSize:10,fontWeight:900,cursor:'pointer'}}>{copied?'Copied ✓':'Copy'}</button></div>}</div></section>;
 if(!showSetup&&view==='dashboard')return <><ContractorPersonalDashboard profileId={profile.id} displayName={profile.display_name}/><ContractorCreateTeamWorkflow profileId={profile.id}/><ContractorTeamListMenu profileId={profile.id}/></>;
 if(!showSetup&&view==='team'&&teamNumber)return <><ContractorTeamPage profileId={profile.id} teamNumber={teamNumber}/><ContractorAddMembersWorkflow profileId={profile.id} teamNumber={teamNumber}/></>;
 if(!showSetup&&view==='team-work'&&teamNumber)return <><ContractorTeamPage profileId={profile.id} teamNumber={teamNumber}/><ContractorAddMembersWorkflow profileId={profile.id} teamNumber={teamNumber}/></>;
 if(!showSetup&&view==='team-settings'&&teamNumber)return <ContractorTeamSettingsPage profileId={profile.id} teamNumber={teamNumber}/>;
 if(!showSetup&&view==='finance')return <main style={shell}><header style={{marginBottom:14}}><div style={{color:'#059669',fontSize:10,fontWeight:900,letterSpacing:'.12em'}}>CONTRACTOR FINANCE</div><h1 style={{margin:'4px 0',fontSize:34}}>Finance</h1><p style={{color:'#64748b',fontSize:12}}>Empty foundation — later-phase payments and reconciliation are not active.</p></header><section style={{...card,textAlign:'center'}}><div style={{fontSize:34}}>¤</div><h2>Finance foundation</h2><p style={{color:'#64748b',fontSize:12}}>No fake totals are shown.</p></section></main>;
 if(!showSetup&&view==='settings')return <main style={shell}><header style={{marginBottom:14}}><div style={{color:'#059669',fontSize:10,fontWeight:900,letterSpacing:'.12em'}}>CONTRACTOR ACCOUNT</div><h1 style={{margin:'4px 0',fontSize:34}}>Settings</h1><p style={{color:'#64748b',fontSize:12}}>Your saved Contractor setup information.</p></header>{profileCard}<section style={{display:'grid',gap:10}}><Info title="Commission-based contractor">{account?.is_commission_based?'Yes':'No'}</Info><Info title="Contracting work"><div style={{display:'grid',gap:7}}>{(account?.work_types??[]).map(x=><div key={x}>{x}</div>)}</div></Info><Info title="Works with"><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{(account?.works_with??[]).map(x=><span key={x} style={{padding:'7px 10px',borderRadius:999,background:'#fff'}}>{x}</span>)}</div></Info><Info title="Company / Business Name">{account?.business_name||'Not provided'}</Info></section><button type="button" onClick={()=>navigate('/work/contractor?view=setup')} style={{width:'100%',marginTop:12,minHeight:46,borderRadius:12,border:'1px solid rgba(5,150,105,.26)',background:'linear-gradient(145deg,#ecfdf5,#d1fae5)',color:'#047857',fontWeight:900,cursor:'pointer'}}>Edit Contractor Setup</button><div style={{marginTop:12}}><AccountModeSwitchCard currentMode="contractor" profileId={profile.id}/></div></main>;
 return <main style={shell}><header style={{marginBottom:14}}><div style={{color:'#059669',fontSize:10,fontWeight:900,letterSpacing:'.12em'}}>CONTRACTOR ACCOUNT SETUP</div><h1 style={{margin:'4px 0',fontSize:34,letterSpacing:'-.045em'}}>{editing?'Edit your Contractor Account':'Set up your Contractor Account'}</h1><p style={{color:'#64748b',fontSize:12}}>{editing?'Update your saved Contractor setup information.':'A lightweight Contractor profile foundation.'}</p></header>{profileCard}{error&&<p role="alert" style={{color:'#b91c1c',fontSize:12}}>{error}</p>}<section style={{...card,display:'grid',gap:17}}><fieldset style={{border:0,padding:0,margin:0}}><legend style={{fontWeight:900,fontSize:14}}>Are you a commission-based contractor?</legend><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}>{[true,false].map(v=><Choice key={String(v)} selected={commissionBased===v} onClick={()=>setCommissionBased(v)}>{v?'Yes':'No'}</Choice>)}</div></fieldset><fieldset style={{border:0,padding:0,margin:0}}><legend style={{fontWeight:900,fontSize:14}}>What type of contracting work do you do?</legend><div style={{display:'grid',gap:7,marginTop:8}}>{WORK_TYPES.map(v=><Choice key={v} selected={workTypes.includes(v)} onClick={()=>toggle(workTypes,v,setWorkTypes)}>{v}</Choice>)}</div></fieldset><fieldset style={{border:0,padding:0,margin:0}}><legend style={{fontWeight:900,fontSize:14}}>Do you work with workers or teams?</legend><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}>{WORKS_WITH.map(v=><Choice key={v} selected={worksWith.includes(v)} onClick={()=>toggle(worksWith,v,setWorksWith)}>{v}</Choice>)}</div></fieldset><label style={{display:'grid',gap:7,fontWeight:900,fontSize:14}}>Company / Business Name <span style={{fontSize:10,color:'#94a3b8'}}>Optional</span><input value={businessName} onChange={e=>setBusinessName(e.target.value)} maxLength={160} placeholder="Optional business name" style={input}/></label><button type="button" disabled={saving} onClick={()=>void save()} style={{minHeight:48,borderRadius:13,border:0,background:'linear-gradient(145deg,#059669,#047857)',color:'#fff',fontWeight:950,cursor:saving?'wait':'pointer',boxShadow:'0 7px 0 rgba(4,120,87,.16),0 13px 22px rgba(5,150,105,.14)'}}>{saving?'Saving…':editing?'Save Changes':'Save Contractor Profile'}</button>{saved&&<div role="status" style={{padding:12,borderRadius:12,background:'#ecfdf5',color:'#047857',fontWeight:900}}>Saved Successfully ✓</div>}</section></main>;
}
function Info({title,children}:{title:string;children:ReactNode}){return <div style={{padding:12,borderRadius:14,border:'1px solid rgba(5,150,105,.14)',background:'linear-gradient(145deg,#ecfdf5,#eff6ff)',boxShadow:'inset 0 1px 0 #fff,0 8px 18px rgba(15,23,42,.05)'}}><span style={{fontSize:10,color:'#64748b',fontWeight:850,textTransform:'uppercase',letterSpacing:'.08em'}}>{title}</span><div style={{marginTop:5,color:'#172033',fontSize:13,fontWeight:800}}>{children}</div></div>}
function Choice({selected,onClick,children}:{selected:boolean;onClick:()=>void;children:ReactNode}){return <button type="button" aria-pressed={selected} onClick={onClick} style={{minHeight:44,padding:'9px 11px',borderRadius:12,border:selected?'1px solid rgba(5,150,105,.42)':'1px solid rgba(100,116,139,.2)',background:selected?'linear-gradient(145deg,#ecfdf5,#d1fae5)':'linear-gradient(145deg,#fff,#f8fafc)',color:selected?'#047857':'#334155',fontWeight:850,textAlign:'left',cursor:'pointer',boxShadow:selected?'0 4px 0 rgba(5,150,105,.12),inset 0 1px 0 #fff':'0 3px 0 rgba(100,116,139,.08),inset 0 1px 0 #fff'}}><span style={{marginRight:7}}>{selected?'✓':'○'}</span>{children}</button>}
