import { FunctionsFetchError, FunctionsHttpError, FunctionsRelayError } from '@supabase/supabase-js';
import type { PostgrestError } from '@supabase/supabase-js';
import { supabase } from '../../../lib/supabase/client';
import { listWorkerFinanceReceived, getWorkerFinanceSummary } from '../../worker/api/finance';
import { AiRouter, getDefaultAiRoutingMode, type AiRoutingMode } from '../providers/aiRouter';
import { AiRoutingError } from '../providers/contracts';
import { GeminiAiProvider } from '../providers/geminiAiProvider';
import { LocalAiProvider } from '../providers/localAiProvider';
import { bridgeLocalAction } from '../assistant/localActionBridge';
import { offlineAiTrace } from '../runtime/localAiDiagnostics';
import type { AiAttachment as ProviderAiAttachment, AiGenerationOptions, AiMessage as ProviderAiMessage, AiResponse } from '../providers/contracts';

export interface AiConversation { id: string; title: string | null; status: string; created_at: string; updated_at: string; }
export interface AiMessage { id: string; conversation_id: string; role: 'user' | 'assistant' | 'tool'; content: string; tool_name: string | null; tool_call_id: string | null; metadata: Record<string, unknown>; created_at: string; }
export interface AiPendingAction { id: string; display_summary: string; expires_at: string; confirmation_id?: string; action_id?: string; }
export interface AiReply { conversation_id: string; message: string; pending_actions: AiPendingAction[]; provider: 'gemini' | 'local'; mode: 'online' | 'offline'; }
function normalizeAiDisplayText(content: string): string { return content.replace(/\*\*/g, ''); }
function readableError(error: unknown): string { if (error instanceof Error && error.message) return error.message; if (typeof error === 'object' && error !== null && 'message' in error) { const message = (error as { message?: unknown }).message; if (typeof message === 'string' && message) return message; } return 'Work Social AI could not complete that request.'; }
async function functionErrorMessage(error: unknown, fallback: string): Promise<string> { if (error instanceof FunctionsHttpError) { const status = error.context.status; const sbErrorCode = error.context.headers.get('sb-error-code'); let payload: Record<string, unknown> = {}; try { const parsed = await error.context.clone().json(); if (parsed && typeof parsed === 'object') payload = parsed as Record<string, unknown>; } catch {} const code = typeof payload.code === 'string' ? payload.code : null; const message = typeof payload.error === 'string' ? payload.error : null; const upstreamStatus = typeof payload.upstream_status === 'number' ? payload.upstream_status : null; const parts = [`HTTP ${status}`]; if (sbErrorCode) parts.push(`sb-error-code ${sbErrorCode}`); if (code) parts.push(`server ${code}`); if (upstreamStatus) parts.push(`upstream HTTP ${upstreamStatus}`); if (message) parts.push(message); return parts.join(' — '); } if (error instanceof FunctionsRelayError) return `Supabase Functions relay error — ${readableError(error)}`; if (error instanceof FunctionsFetchError) return `Supabase Functions fetch error — ${readableError(error)}`; return readableError(error) || fallback; }
function isFinanceQuestion(message: string): boolean { return /\b(finance|financial|earning|earnings|payment|payments|advance|advances|received|balance|remaining|paid|paisa|paise|rup(?:ee|ees)|amount|hisab|hisaab|kamai|jama|wasool|milay|mili|mila)\b/i.test(message) || /(?:فنانس|آمدنی|کمائی|ادائیگی|ایڈوانس|وصول|بقایا|رقم|حساب|جمع|ملے|ملا|ملی)/u.test(message); }
async function buildFinanceContext(profileId: string, message: string): Promise<string> { if (!isFinanceQuestion(message)) return ''; const [summaryResult, receivedResult] = await Promise.all([getWorkerFinanceSummary(), listWorkerFinanceReceived(profileId)]); if (summaryResult.error) throw summaryResult.error; if (receivedResult.error) throw receivedResult.error; const received = receivedResult.data.slice(0, 100).map((item) => ({ id: item.id, type: item.entry_type, amount: item.amount, received_at: item.received_at })); return `\n\n[READ-ONLY FINANCE CONTEXT — authoritative Finance page data for this authenticated user]\nSummary: total_earnings=${summaryResult.data?.total_earnings ?? '0'}, received=${summaryResult.data?.received ?? '0'}, remaining=${summaryResult.data?.remaining ?? '0'}\nReceived records (active only, newest first): ${JSON.stringify(received)}\nUse this Finance context for finance questions. Do not invent missing records. These received amounts are actual recorded payments/advances, while total_earnings is recorded work value.`; }
function getClientTimeContext(): { timeZone: string; nowIso: string } { const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'; const now = new Date(); const parts = new Intl.DateTimeFormat('en-CA', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }).formatToParts(now); const get = (type: string) => parts.find((part) => part.type === type)?.value ?? ''; const offsetPart = new Intl.DateTimeFormat('en-US', { timeZone, timeZoneName: 'longOffset' }).formatToParts(now).find((part) => part.type === 'timeZoneName')?.value ?? 'GMT'; const offset = offsetPart === 'GMT' ? '+00:00' : offsetPart.replace(/^GMT/, ''); const milliseconds = String(now.getMilliseconds()).padStart(3, '0'); return { timeZone, nowIso: `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}:${get('second')}.${milliseconds}${offset}` }; }
async function sendGeminiMessage(messages: ProviderAiMessage[], _attachments: ProviderAiAttachment[] = [], _options?: AiGenerationOptions): Promise<AiResponse> { const latest = [...messages].reverse().find((item) => item.role === 'user'); const trimmed = latest?.content.trim() ?? ''; if (!trimmed) throw new Error('Message cannot be empty.'); if (trimmed.length > 12000) throw new Error('Message must be 12,000 characters or fewer.'); const { data: sessionData, error: sessionError } = await supabase.auth.getSession(); if (sessionError || !sessionData.session) throw new Error('Your Work Social session has expired. Please sign in again.'); const financeContext = await buildFinanceContext(sessionData.session.user.id, trimmed); const clientTime = getClientTimeContext(); const requestMessage = `${trimmed}${financeContext}`; const { data, error } = await supabase.functions.invoke('work-social-ai', { body: { message: requestMessage, conversation_id: latest?.conversationId || null, client_timezone: clientTime.timeZone, client_now_iso: clientTime.nowIso }, headers: { Authorization: `Bearer ${sessionData.session.access_token}` } }); if (error) throw new Error(await functionErrorMessage(error, 'Work Social AI could not complete the request.')); if (!data || typeof data !== 'object') throw new Error('The AI service returned an invalid response.'); if ('error' in data && typeof data.error === 'string') throw new Error(data.error); const reply = data as Partial<AiReply>; if (typeof reply.conversation_id !== 'string' || typeof reply.message !== 'string') throw new Error('The AI service returned an incomplete response.'); const pendingActions = Array.isArray(reply.pending_actions) ? reply.pending_actions.map((action) => ({ id: action.id || action.confirmation_id || action.action_id || '', displaySummary: action.display_summary || '', expiresAt: action.expires_at || '' })).filter((action) => Boolean(action.id)) : []; return { conversationId: reply.conversation_id, message: normalizeAiDisplayText(reply.message), pendingActions, provider: 'gemini', mode: 'online' }; }
const aiRouter = new AiRouter(new GeminiAiProvider(sendGeminiMessage), new LocalAiProvider(undefined, undefined, undefined, bridgeLocalAction));

export async function sendAiMessage(message: string, conversationId: string | null, mode: AiRoutingMode = getDefaultAiRoutingMode(), router: AiRouter = aiRouter, onToken?: (text: string) => void): Promise<AiReply> {
  const requestedMode = mode;
  offlineAiTrace('OFFLINE_REQUEST_RECEIVED', { requestedMode });
  offlineAiTrace('OFFLINE_MODE_CONFIRMED', { requestedMode, modeSource: 'explicit-argument-or-router-default' });
  const response = await router.sendMessage([{ id: `request-${Date.now()}`, conversationId: conversationId ?? '', role: 'user', content: message }], [], { mode: requestedMode, ...(onToken ? { onToken } : {}) });
  if (requestedMode === 'offline' && (response.provider !== 'local' || response.mode !== 'offline')) throw new AiRoutingError('OFFLINE_ROUTE_VIOLATION', 'offline', 'local', `Offline response provenance mismatch: provider=${response.provider}, mode=${response.mode}`);
  offlineAiTrace('RESPONSE_RECEIVED', { requestedMode, provider: response.provider, responseMode: response.mode, nonEmpty: response.message.trim().length > 0 });
  return { conversation_id: response.conversationId, message: response.message, pending_actions: response.pendingActions.map((action) => ({ id: action.id, display_summary: action.displaySummary, expires_at: action.expiresAt })), provider: response.provider, mode: response.mode };
}

export async function confirmAiAction(actionId: string): Promise<{ success: boolean; entry?: Record<string, unknown> }> {
  if (!actionId) throw new Error('The action is missing its confirmation id.');
  offlineAiTrace('ACTION_CONFIRMATION_REQUESTED', { actionId });
  const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
  if (sessionError || !sessionData.session) throw new Error('Your Work Social session has expired. Please sign in again.');
  offlineAiTrace('ACTION_CONFIRMATION_STARTED', { actionId });
  try {
    const { data, error } = await supabase.functions.invoke('work-social-ai', { body: { action: 'confirm', action_id: actionId }, headers: { Authorization: `Bearer ${sessionData.session.access_token}` } });
    if (error) throw new Error(await functionErrorMessage(error, 'Work Social AI could not complete that confirmation.'));
    if (!data || typeof data !== 'object') throw new Error('The AI service returned an invalid confirmation response.');
    if ('error' in data && typeof data.error === 'string') throw new Error(data.error);
    const result = data as { success: boolean; entry?: Record<string, unknown> };
    if (!result.success) throw new Error('The confirmed action did not complete successfully.');
    offlineAiTrace('WORK_ENTRY_CREATED', { actionId });
    offlineAiTrace('ACTION_EXECUTION_COMPLETED', { actionId });
    return result;
  } catch (error) {
    offlineAiTrace('ACTION_EXECUTION_FAILED', { actionId, error: readableError(error) });
    throw error;
  }
}
export async function listAiConversations(): Promise<AiConversation[]> { const { data, error } = await supabase.from('ai_conversations').select('id,title,status,created_at,updated_at').order('updated_at', { ascending: false }).limit(30); if (error) throw new Error((error as PostgrestError).message || 'Could not load AI conversations.'); return (data ?? []) as AiConversation[]; }
export async function listAiMessages(conversationId: string): Promise<AiMessage[]> { const { data, error } = await supabase.from('ai_messages').select('id,conversation_id,role,content,tool_name,tool_call_id,metadata,created_at').eq('conversation_id', conversationId).order('created_at', { ascending: true }).limit(100); if (error) throw new Error((error as PostgrestError).message || 'Could not load AI messages.'); return (data ?? []).map((item) => ({ ...(item as AiMessage), content: normalizeAiDisplayText(item.content) })); }
