import { validateVisionImage, validateVisionImages } from './imageValidator';
import { OFFLINE_VISION_LIMITS, VisionValidationError } from './contracts';
import { isVisionModelCapable, supportsModelModality } from '../model/modelCapability';
import { createLocalInferenceRuntime } from '../runtime/localInferenceRuntime';
import { LocalInferenceRuntimeError, verifiedModelReferenceBrand, type LocalInferenceEngineAdapter, type InferenceResponse, type InferenceRequest } from '../runtime/localInferenceContracts';
import type { AiModel } from '../model/modelContracts';
import { AiRouter } from '../providers/aiRouter';
import type { AiAttachment, AiProvider, AiProviderStatus, AiResponse } from '../providers/contracts';
import { LocalAiProvider } from '../providers/localAiProvider';

let passed = 0;
async function test(name: string, run: () => Promise<void> | void): Promise<void> { try { await run(); passed += 1; console.log(`✓ ${name}`); } catch (error) { console.error(`✗ ${name}`); throw error; } }
async function expectVisionError(run: () => Promise<unknown>, code: VisionValidationError['code']): Promise<void> { try { await run(); throw new Error(`Expected ${code}.`); } catch (error) { if (!(error instanceof VisionValidationError) || error.code !== code) throw error; } }
function png(): Blob { const bytes = new Uint8Array([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0,0,0,13,0x49,0x48,0x44,0x52,0,0,0,2,0,0,0,3]); return new Blob([bytes], { type: 'image/png' }); }
function jpeg(): Blob { return new Blob([new Uint8Array([0xff,0xd8,0xff,0xc0,0,7,8,0,3,0,4,3,1,1,0,0,0,0,0,0,0,0,0,0])], { type: 'image/jpeg' }); }
function webp(): Blob { const bytes = new Uint8Array(30); bytes.set([82,73,70,70,0,0,0,0,87,69,66,80,86,80,56,88]); bytes[23]=0; bytes[24]=1; bytes[25]=0; bytes[26]=0; bytes[27]=0; bytes[28]=0; bytes[29]=0; return new Blob([bytes], { type: 'image/webp' }); }
function image(id: string, mimeType = 'image/png', data?: Blob): any { return { id, kind:'image', mimeType, name:`${id}.img`, ...(data ? { data } : {}), metadata:{ reference:`ref-${id}`, ...(data ? { declaredSizeBytes:data.size } : {}) } }; }
function model(type: AiModel['type']): AiModel { return { id:`model-${type}`, name:type, version:'test', type, format:'GGUF', sizeBytes:1, sha256:'verified', architectureRequirements:{supportedArchitectures:['arm64-v8a']}, memoryRequirements:{requiredRamBytes:1}, storageRequirements:{requiredFreeStorageBytes:1}, platformRequirements:{requiredPlatform:'android'}, downloadSource:null, availability:'AVAILABLE', status:'INSTALLED' }; }
function adapter(capabilities: Partial<NonNullable<LocalInferenceEngineAdapter['capabilities']>>): LocalInferenceEngineAdapter { return { name:'fixture', streaming:false, cancellation:false, capabilities, initialize:async()=>undefined, loadModel:async()=>undefined, unloadModel:async()=>undefined, generate:async(_request:InferenceRequest,_signal:AbortSignal):Promise<InferenceResponse>=>{throw new Error('generation should not run');}, stream:async function*(){}, cancel:async()=>undefined, dispose:async()=>undefined }; }
function provider(id:'gemini'|'local', status:AiProviderStatus, onSend:()=>void=()=>undefined, routingStatus?: (attachments?:AiAttachment[])=>Promise<AiProviderStatus>):AiProvider { const response:AiResponse={conversationId:'c',message:'ok',pendingActions:[],provider:id,mode:id==='gemini'?'online':'offline'}; return {id,mode:id==='gemini'?'online':'offline',getStatus:()=>status,sendMessage:async()=>{onSend();return response;},...(routingStatus?{getRoutingStatus:routingStatus}:{})} as AiProvider; }

async function main(): Promise<void> {
  await test('JPEG accepted and dimensions verified', async()=>{const result=await validateVisionImage(image('jpeg','image/jpeg',jpeg()));if(result.dimensions.width!==4||result.dimensions.height!==3)throw new Error('JPEG dimensions were not verified.');});
  await test('PNG accepted and dimensions verified', async()=>{const result=await validateVisionImage(image('png','image/png',png()));if(result.dimensions.width!==2||result.dimensions.height!==3)throw new Error('PNG dimensions were not verified.');});
  await test('WebP accepted and dimensions verified', async()=>{const result=await validateVisionImage(image('webp','image/webp',webp()));if(result.dimensions.width!==2||result.dimensions.height!==1)throw new Error('WebP dimensions were not verified.');});
  await test('metadata-only image keeps dimensions unknown', async()=>{const result=await validateVisionImage(image('meta'));if(result.dimensions.width!==null||result.dimensions.height!==null||result.dimensions.verifiedFromBytes)throw new Error('Unknown dimensions were fabricated.');});
  await test('unsupported MIME rejected',()=>expectVisionError(()=>validateVisionImage(image('gif','image/gif')),'UNSUPPORTED_IMAGE_TYPE'));
  await test('oversized image rejected',()=>expectVisionError(()=>validateVisionImage({...image('large'),metadata:{reference:'ref-large',declaredSizeBytes:OFFLINE_VISION_LIMITS.maxImageBytes+1}}),'IMAGE_TOO_LARGE'));
  await test('excessive image count rejected',()=>expectVisionError(()=>validateVisionImages(Array.from({length:OFFLINE_VISION_LIMITS.maxImages+1},(_,i)=>image(`i${i}`))),'IMAGE_COUNT_EXCEEDED'));
  await test('malformed metadata rejected',()=>expectVisionError(()=>validateVisionImage({id:'bad',kind:'image',mimeType:'image/png',name:'bad\u0000.png'}),'INVALID_IMAGE_METADATA'));
  await test('model modality is explicit',()=>{if(isVisionModelCapable('TEXT')||!isVisionModelCapable('VISION')||!isVisionModelCapable('MULTIMODAL'))throw new Error('Model modality capability is incorrect.');if(!supportsModelModality('VISION','VISION')||supportsModelModality('VISION','MULTIMODAL')||!supportsModelModality('MULTIMODAL','MULTIMODAL'))throw new Error('Model modality support is incorrect.');});
  await test('browser runtime reports vision unavailable',()=>{const runtime=createLocalInferenceRuntime();const caps=runtime.getCapabilities!();if(caps.textGeneration||caps.visionInput||caps.multimodalInput||caps.streaming||caps.cancellation)throw new Error('Browser runtime advertised unsupported local capabilities.');});
  await test('runtime without vision capability rejects vision inference',async()=>{const runtime=createLocalInferenceRuntime(adapter({textGeneration:true,visionInput:false,multimodalInput:false}));const ref={model:model('VISION'),[verifiedModelReferenceBrand]:true,readVerifiedModel:async()=>new Blob(['model'])} as any;await runtime.initialize();await runtime.loadModel(ref);try{await runtime.generate({messages:[],modality:'VISION',attachments:[image('x')]});throw new Error('Expected vision runtime rejection.');}catch(error){if(!(error instanceof LocalInferenceRuntimeError)||error.code!=='VISION_RUNTIME_UNAVAILABLE')throw error;}});
  await test('declared runtime capabilities are exposed truthfully',()=>{const runtime=createLocalInferenceRuntime(adapter({textGeneration:true,visionInput:true,multimodalInput:true}));const caps=runtime.getCapabilities!();if(!caps.textGeneration||!caps.visionInput||!caps.multimodalInput||caps.streaming||caps.cancellation)throw new Error('Runtime capability declaration is incorrect.');});
  await test('local provider rejects vision without fabricating an answer or using network',async()=>{const local=new LocalAiProvider(createLocalInferenceRuntime());const originalFetch=globalThis.fetch;globalThis.fetch=(()=>{throw new Error('network access is forbidden');}) as typeof fetch;try{await local.sendMessage([{id:'m',conversationId:'c',role:'user',content:'describe'}],[image('local-image')]);throw new Error('Expected structured local vision failure.');}catch(error){if(!(error instanceof LocalInferenceRuntimeError)||error.code!=='VISION_RUNTIME_UNAVAILABLE')throw error;}finally{globalThis.fetch=originalFetch;}});
  await test('router AUTO image falls back online with an explicit local-vision reason',async()=>{let geminiCalls=0;const gemini=provider('gemini',{state:'ready',provider:'gemini',mode:'online'},()=>{geminiCalls+=1;});const local=provider('local',{state:'unavailable',provider:'local',mode:'offline',reason:'The local runtime does not expose a verified vision-capable execution capability.',reasonCode:'VISION_RUNTIME_UNAVAILABLE'},()=>undefined,async()=>({state:'unavailable',provider:'local',mode:'offline',reason:'The local runtime does not expose a verified vision-capable execution capability.',reasonCode:'VISION_RUNTIME_UNAVAILABLE'}));const router=new AiRouter(gemini,local);const route=await router.route('auto',[image('router-image')]);if(route.provider!=='gemini'||route.reasonCode!=='AUTO_ONLINE_SELECTED'||!route.reason.includes('vision-capable'))throw new Error('AUTO image route was not truthful.');await router.sendMessage([{id:'m',conversationId:'c',role:'user',content:'describe'}],[image('router-image')],{mode:'auto'});if(geminiCalls!==1)throw new Error('AUTO image did not invoke Gemini.');});
  await test('router ONLINE image selects Gemini',async()=>{let calls=0;const router=new AiRouter(provider('gemini',{state:'ready',provider:'gemini',mode:'online'},()=>{calls+=1;}),provider('local',{state:'unavailable',provider:'local',mode:'offline',reasonCode:'VISION_RUNTIME_UNAVAILABLE'}));const route=await router.route('online',[image('online-image')]);if(route.provider!=='gemini'||route.reasonCode!=='ONLINE_EXPLICIT')throw new Error('ONLINE image route failed.');await router.sendMessage([{id:'m',conversationId:'c',role:'user',content:'describe'}],[image('online-image')],{mode:'online'});if(calls!==1)throw new Error('ONLINE image did not invoke Gemini.');});
  await test('router OFFLINE image never falls back to Gemini',async()=>{let calls=0;const router=new AiRouter(provider('gemini',{state:'ready',provider:'gemini',mode:'online'},()=>{calls+=1;}),provider('local',{state:'unavailable',provider:'local',mode:'offline',reason:'vision runtime unavailable',reasonCode:'VISION_RUNTIME_UNAVAILABLE'},()=>undefined,async()=>({state:'unavailable',provider:'local',mode:'offline',reason:'vision runtime unavailable',reasonCode:'VISION_RUNTIME_UNAVAILABLE'})));try{await router.route('offline',[image('offline-image')]);throw new Error('Expected offline vision error.');}catch(error){if(!(error instanceof Error)||!('code' in error)||String((error as {code?:unknown}).code)!=='VISION_RUNTIME_UNAVAILABLE')throw error;}if(calls!==0)throw new Error('OFFLINE image invoked Gemini.');});
  console.log(`Phase 10 vision tests passed: ${passed} deterministic tests.`);
}
main().catch(error=>{console.error(error);throw error;});
