import { createClient } from "npm:@supabase/supabase-js@2";
const HEADERS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS"};
type R=Record<string,any>;
class E extends Error{constructor(public status:number,public code:string,message:string){super(message)}}
const out=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers:{...HEADERS,"Content-Type":"application/json"}});
function client(req:Request){const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))throw new E(401,"AUTHORIZATION_MISSING","Missing user authorization.");const keys=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")??"{}");if(!keys.default)throw new E(500,"SUPABASE_CONFIG_ERROR","Supabase configuration is unavailable.");return createClient(Deno.env.get("SUPABASE_URL")!,keys.default,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}})}
async function user(req:Request){const auth=req.headers.get("Authorization")!,c=client(req),{data,error}=await c.auth.getUser(auth.slice(7));if(error||!data.user)throw new E(401,"AUTHENTICATION_FAILED","Your Work Social session is not valid.");return{c,u:data.user.id,auth}}
async function state(c:any,u:string,id:string){const{data:pending}=await c.from("ai_pending_actions").select("id,status,tool_name").eq("id",id).eq("user_id",u).maybeSingle();const{data:history}=await c.from("ai_tool_calls").select("id,status,execution_state,verification_state,record_ids,verification_result").eq("pending_action_id",id).eq("user_id",u).order("created_at",{ascending:false}).limit(1).maybeSingle();return{pending,history}}
async function fail(c:any,u:string,id:string,message:string){await c.from("ai_action_claims").update({failed_at:new Date().toISOString()}).eq("action_id",id).eq("user_id",u).is("consumed_at",null);await c.from("ai_pending_actions").update({status:"failed"}).eq("id",id).eq("user_id",u).eq("status","pending");await c.from("ai_tool_calls").update({status:"failed",execution_state:"failed",verification_state:"failed",error_message:message,completed_at:new Date().toISOString()}).eq("pending_action_id",id).eq("user_id",u)}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:HEADERS});try{const{c,u,auth}=await user(req),body=await req.json(),actionId=String(body?.action_id??"").trim();if(!actionId)throw new E(400,"ACTION_ID_REQUIRED","action_id is required.");const{data:claim,error:claimError}=await c.rpc("claim_ai_pending_action",{p_action_id:actionId});if(claimError||!claim?.length)throw new E(409,"ACTION_CLAIM_FAILED",claimError?.message||"The action could not be confirmed.");const baseUrl=Deno.env.get("SUPABASE_URL")!,keys=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")??"{}");let payload:R={};try{const response=await fetch(`${baseUrl}/functions/v1/work-social-ai-smart`,{method:"POST",headers:{Authorization:auth,apikey:keys.default,"Content-Type":"application/json"},body:JSON.stringify({action:"confirm",action_id:actionId})});try{payload=await response.json()}catch{payload={error:"The AI action executor returned an invalid response."}}if(!response.ok||payload?.error){const message=String(payload?.error||`Action execution returned HTTP ${response.status}.`);const current=await state(c,u,actionId);if(current.pending?.status!=="succeeded"||current.history?.status!=="verified"){await fail(c,u,actionId,message);throw new E(response.status>=400&&response.status<500?response.status:502,"ACTION_EXECUTION_FAILED",message)}}}catch(error){const current=await state(c,u,actionId);if(current.pending?.status!=="succeeded"||current.history?.status!=="verified"){const message=error instanceof Error?error.message:"The AI action executor could not be reached.";await fail(c,u,actionId,message);throw new E(502,"ACTION_EXECUTION_FAILED",message)}payload={success:true,recovered_after_executor_response_failure:true}}
const current=await state(c,u,actionId);if(current.pending?.status!=="succeeded"||current.history?.status!=="verified"||current.history?.verification_state!=="verified"){const message="The database mutation response could not be verified as persisted.";await fail(c,u,actionId,message);throw new E(502,"VERIFICATION_FAILED",message)}return out(200,{...payload,success:true,verified:true,record_ids:current.history.record_ids??[],verification_result:current.history.verification_result??null})}catch(e){const x=e instanceof E?e:new E(500,"AI_CONFIRM_INTERNAL_ERROR",e instanceof Error?e.message:"Work Social AI could not complete that confirmation.");return out(x.status,{error:x.message,code:x.code})}});
