import { useEffect, useMemo, useState } from 'react';
import { navigate } from '../../../app/Router';
import { getFinalizedSalaryTotals, getSalaryMonthSummary, getSalaryPolicy, saveAttendance, saveOvertime } from '../api/salary';
import { listSalaryAllowances, type SalaryAllowance } from '../api/salaryAllowances';
import { useWorkerProfile } from '../hooks/useWorkerProfile';
import { WorkerDashboardCustomize } from '../components/WorkerDashboardCustomize';
import type { AttendanceStatus, SalaryMonthSummary, SalaryPolicy } from '../types/salary';

const shell = { width: '100%', maxWidth: 1080, margin: '0 auto', padding: '20px 14px 120px', boxSizing: 'border-box' as const };
const panel = { border: '1px solid rgba(148,163,184,.24)', borderRadius: 24, background: 'rgba(255,255,255,.97)', boxShadow: '0 22px 50px rgba(15,23,42,.09), 0 5px 12px rgba(15,23,42,.04), inset 0 1px 0 rgba(255,255,255,1), inset 0 -1px 0 rgba(148,163,184,.08)', overflow: 'hidden' as const, position: 'relative' as const };
const input = { width: '100%', boxSizing: 'border-box' as const, minHeight: 42, padding: '8px 11px', borderRadius: 11, border: '1px solid #cbd5e1', background: '#fff', font: 'inherit' };
const button = { minHeight: 42, padding: '0 14px', borderRadius: 12, border: '1px solid rgba(100,116,139,.18)', background: 'linear-gradient(145deg,#fff,#f5f7fb)', fontWeight: 850, cursor: 'pointer', boxShadow: '0 7px 14px rgba(15,23,42,.07), 0 2px 4px rgba(15,23,42,.03), inset 0 1px 0 #fff', transition: 'transform .16s ease, box-shadow .16s ease' };
const primaryButton = { ...button, border: '0', background: 'linear-gradient(145deg,#4f46e5,#2563eb)', color: '#fff', boxShadow: 'inset 0 1px 1px rgba(255,255,255,.3), 0 10px 20px rgba(79,70,229,.2), 0 3px 6px rgba(37,99,235,.1)' };
const money = (value: number, currency: string) => `${currency} ${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
function monthValue(offset: number) { const d = new Date(); d.setDate(1); d.setMonth(d.getMonth() + offset); return d.toISOString().slice(0, 10); }

const defaultDashboardCards = [
  { id: 'current_salary', label: 'Current Month Salary', description: 'Current month salary summary.' },
  { id: 'grand_salary', label: 'Grand Salary', description: 'Finalized salary totals.' },
  { id: 'salary_overview', label: 'Attendance · Overtime · Allowance · Bonus', description: 'Monthly salary component cards.' },
  { id: 'daily_work', label: 'Daily Work Record', description: 'Attendance and overtime entry controls.' },
  { id: 'monthly_detail', label: 'Monthly Detail', description: 'Current month detail summary.' },
];

export function SalaryDashboardPage({ profileId }: { profileId: string }) {
  const { workerProfile, loading } = useWorkerProfile(profileId);
  const [policy, setPolicy] = useState<SalaryPolicy | null>(null);
  const [summary, setSummary] = useState<SalaryMonthSummary | null>(null);
  const [allowances, setAllowances] = useState<SalaryAllowance[]>([]);
  const [allowanceOpen, setAllowanceOpen] = useState(false);
  const [grand, setGrand] = useState({ months: 0, base: 0, overtime: 0, bonuses: 0, adjustments: 0, total: 0 });
  const [monthOffset, setMonthOffset] = useState(0);
  const [attendanceDate, setAttendanceDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [attendance, setAttendance] = useState<AttendanceStatus>('present');
  const [attendanceOpen, setAttendanceOpen] = useState(false);
  const [overtimeDate, setOvertimeDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [overtimeHours, setOvertimeHours] = useState('');
  const [overtimeOpen, setOvertimeOpen] = useState(false);
  const [status, setStatus] = useState('');
  const [busy, setBusy] = useState(false);
  const [dashboardOrder, setDashboardOrder] = useState(defaultDashboardCards.map(card => card.id));
  const [hiddenDashboardCards, setHiddenDashboardCards] = useState<string[]>([]);
  const month = useMemo(() => monthValue(monthOffset), [monthOffset]);

  const refresh = async () => {
    const [p, s, g, a] = await Promise.all([getSalaryPolicy(profileId), getSalaryMonthSummary(month), getFinalizedSalaryTotals(profileId), listSalaryAllowances(profileId)]);
    setPolicy(p.data); setSummary(s.data); setAllowances(a.data ?? []);
    if (s.error) setStatus(s.error.message);
    if (a.error) setStatus(a.error.message);
    if (!g.error) setGrand(g.data.reduce((acc, row) => ({ months: acc.months + 1, base: acc.base + Number(row.base_salary || 0), overtime: acc.overtime + Number(row.overtime_amount || 0), bonuses: acc.bonuses + Number(row.bonus_amount || 0), adjustments: acc.adjustments + Number(row.adjustments || 0), total: acc.total + Number(row.final_amount || 0) }), { months: 0, base: 0, overtime: 0, bonuses: 0, adjustments: 0, total: 0 }));
  };
  useEffect(() => { if (workerProfile) void refresh(); }, [workerProfile, month]);

  if (loading) return <main style={{ padding: 24 }}>Loading Salary Dashboard…</main>;
  if (!workerProfile) return <main style={{ padding: 24 }}>Worker profile unavailable.</main>;

  const currency = policy?.currency ?? 'PKR';
  const title = new Date(`${month}T00:00:00`).toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
  const salaryTypeMissing = !policy?.salary_type;
  const salaryTypeLabel = policy?.salary_type === '15_days' ? '15 Days' : policy?.salary_type ? policy.salary_type.charAt(0).toUpperCase() + policy.salary_type.slice(1) : 'Not set';
  const salaryTypeAction = <button type="button" onClick={() => navigate('/work/finance?setup=1&focus=salary-type')} style={{ border: 0, background: 'transparent', padding: 0, color: salaryTypeMissing ? '#b45309' : '#334155', fontWeight: 900, textDecoration: 'underline', textUnderlineOffset: 3, cursor: 'pointer' }}>{salaryTypeMissing ? 'Salary cycle: Not set — fix setup' : `Salary cycle: ${salaryTypeLabel}`}</button>;
  const allowanceTotal = allowances.reduce((total, row) => total + Number(row.amount || 0), 0);
  const allowanceRuleLabel = (row: SalaryAllowance) => row.eligibility_rule === 'present_only' ? 'Present only' : row.eligibility_rule === 'after_absences' ? `After ${row.loss_after_count ?? 0} absences` : row.eligibility_rule === 'after_unpaid_leaves' ? `After ${row.loss_after_count ?? 0} unpaid leaves` : row.eligibility_rule === 'custom' ? (row.rule_note || 'Custom condition') : 'Always paid';
  const allowanceSettingsButton = <button type="button" onClick={() => navigate('/work/finance?setup=1&focus=allowances')} style={{ ...button, minHeight: 36, padding: '0 11px', fontSize: 12 }}>Change</button>;
  const dashboardStyle = (id: string) => ({ order: dashboardOrder.indexOf(id) + 1, display: hiddenDashboardCards.includes(id) ? 'none' : undefined });

  const saveAttendanceEntry = async () => {
    setStatus(''); setBusy(true);
    const { error } = await saveAttendance(workerProfile.id, attendanceDate, attendance);
    setBusy(false); setStatus(error ? error.message : 'Attendance saved successfully.');
    if (!error) { setAttendanceOpen(false); await refresh(); }
  };
  const saveOvertimeEntry = async () => {
    const hours = Number(overtimeHours);
    if (!Number.isFinite(hours) || hours <= 0) { setStatus('Enter overtime hours greater than zero.'); return; }
    setStatus(''); setBusy(true);
    const { data, error } = await saveOvertime(workerProfile.id, overtimeDate, hours);
    setBusy(false); setStatus(error ? error.message : `Overtime saved: ${Number(data?.amount ?? 0).toFixed(2)} ${currency} at ${Number(data?.multiplier ?? 0)}×.`);
    if (!error) { setOvertimeHours(''); setOvertimeOpen(false); await refresh(); }
  };

  return <main style={{ ...shell, display: 'flex', flexDirection: 'column', gap: 0, background: 'radial-gradient(circle at 8% 0%,rgba(99,102,241,.08),transparent 28%),radial-gradient(circle at 95% 24%,rgba(20,184,166,.07),transparent 30%),linear-gradient(180deg,#f8fafc 0%,#eef2f7 100%)' }}><style>{`@keyframes dashFloat{from{transform:translateY(0)}to{transform:translateY(-2px)}}.salary-dashboard-card{position:relative;isolation:isolate}.salary-dashboard-card:before{content:'';position:absolute;z-index:-1;inset:8px 10px -9px;border-radius:24px;background:linear-gradient(90deg,rgba(99,102,241,.10),rgba(20,184,166,.06));filter:blur(12px);opacity:.75;pointer-events:none}.salary-dashboard-card:after{content:'';position:absolute;top:0;left:18px;right:18px;height:1px;border-radius:999px;background:linear-gradient(90deg,rgba(255,255,255,1),rgba(99,102,241,.38),rgba(20,184,166,.18),rgba(255,255,255,0));box-shadow:0 1px 5px rgba(255,255,255,.9);pointer-events:none}.salary-dashboard-card:hover{transform:translateY(-2px);box-shadow:0 28px 58px rgba(15,23,42,.11),0 6px 14px rgba(79,70,229,.07),inset 0 1px 0 #fff,inset 0 -1px 0 rgba(148,163,184,.09)}.salary-dashboard-card:active{transform:translateY(1px)}.salary-dashboard-metric{position:relative;border:1px solid rgba(148,163,184,.18)!important;background:linear-gradient(145deg,#fff,#f8fafc)!important;box-shadow:0 7px 14px rgba(15,23,42,.055),0 2px 4px rgba(15,23,42,.025),inset 0 1px 0 #fff!important}.salary-dashboard-metric:hover{transform:translateY(-1px);box-shadow:0 10px 18px rgba(15,23,42,.07),inset 0 1px 0 #fff!important}.salary-dashboard-mini{border:1px solid rgba(148,163,184,.16)!important;background:linear-gradient(145deg,#fff,#f8fafc)!important;box-shadow:0 5px 10px rgba(15,23,42,.045),inset 0 1px 0 #fff!important}.salary-dashboard-action{transition:transform .16s ease,box-shadow .16s ease,filter .16s ease}.salary-dashboard-action:hover{transform:translateY(-2px);box-shadow:0 12px 22px rgba(15,23,42,.10),inset 0 1px 0 #fff!important}.salary-dashboard-action:active{transform:translateY(1px)}.salary-dashboard-glass{border:1px solid rgba(255,255,255,.65);background:linear-gradient(145deg,rgba(255,255,255,.96),rgba(241,245,249,.9));box-shadow:inset 0 1px 0 #fff,0 8px 16px rgba(15,23,42,.05)}@media(max-width:560px){.salary-dashboard-card{border-radius:19px!important}.salary-dashboard-card:before{inset:6px 7px -7px}.salary-dashboard-card:after{left:14px;right:14px}}`}</style>
    <header style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'flex-start', marginBottom: 20, padding: 2 }}>
      <div>
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 7, padding: '7px 11px', borderRadius: 999, background: 'linear-gradient(145deg,#ecfdf5,#d1fae5)', color: '#047857', fontSize: 10, fontWeight: 950, letterSpacing: '.1em', textTransform: 'uppercase', boxShadow: '0 5px 10px rgba(16,185,129,.10),inset 0 1px 0 #fff' }}><span style={{ width: 7, height: 7, borderRadius: 99, background: '#10b981', boxShadow: '0 0 0 4px rgba(16,185,129,.10)' }} /> Salary Person</div>
        <h1 style={{ margin: '11px 0 5px', fontSize: 'clamp(29px,6vw,42px)', letterSpacing: '-.045em', fontWeight: 950, color: '#0f172a', textShadow: '0 1px 0 #fff,0 4px 10px rgba(15,23,42,.08)' }}>Your Salary Dashboard</h1>
        <p style={{ margin: 0, color: '#64748b', lineHeight: 1.5, fontSize: 13 }}>A clear view of your salary, attendance, overtime and completed salary history.</p>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', justifyContent: 'flex-end' }}><span className="salary-dashboard-action"><WorkerDashboardCustomize workerProfileId={workerProfile.id} cards={defaultDashboardCards} onLayoutChange={(order, hidden) => { setDashboardOrder(order); setHiddenDashboardCards(hidden); }} /></span><button className="salary-dashboard-action" type="button" onClick={() => navigate('/work/identity')} style={button}>Work Identity</button></div>
    </header>

    <section className="salary-dashboard-card" style={{ ...panel, ...dashboardStyle('current_salary'), marginBottom: 16, transition: 'transform .18s ease,box-shadow .18s ease' }}>
      <div style={{ padding: '23px 19px', background: 'linear-gradient(145deg,#0f172a 0%,#1e1b4b 48%,#1d4ed8 100%)', color: '#fff', position: 'relative', overflow: 'hidden' }}><div style={{ position: 'absolute', width: 180, height: 180, borderRadius: '50%', right: -70, top: -90, background: 'rgba(255,255,255,.09)', filter: 'blur(2px)' }} /><div style={{ position: 'relative', zIndex: 1 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 14, alignItems: 'center', flexWrap: 'wrap' }}><div><div style={{ fontSize: 10, fontWeight: 950, letterSpacing: '.13em', opacity: .68, textTransform: 'uppercase' }}>Current Month Salary</div><h2 style={{ margin: '7px 0 0', fontSize: 26, letterSpacing: '-.03em' }}>{title}</h2></div><div style={{ display: 'flex', gap: 7 }}><button className="salary-dashboard-action" type="button" disabled={monthOffset <= -120} onClick={() => setMonthOffset(v => v - 1)} style={{ ...button, borderColor: 'rgba(255,255,255,.18)', background: 'rgba(255,255,255,.10)', color: '#fff', boxShadow: '0 5px 10px rgba(0,0,0,.14),inset 0 1px 0 rgba(255,255,255,.18)' }}>← Previous</button>{monthOffset !== 0 && <button className="salary-dashboard-action" type="button" onClick={() => setMonthOffset(0)} style={{ ...button, borderColor: 'rgba(255,255,255,.18)', background: 'rgba(255,255,255,.10)', color: '#fff', boxShadow: '0 5px 10px rgba(0,0,0,.14),inset 0 1px 0 rgba(255,255,255,.18)' }}>This Month</button>}</div></div><div style={{ marginTop: 24, fontSize: 12, opacity: .66 }}>Final salary</div><div style={{ marginTop: 3, fontSize: 'clamp(31px,7vw,50px)', fontWeight: 950, letterSpacing: '-.055em', textShadow: '0 4px 12px rgba(0,0,0,.25)' }}>{money(summary?.final_salary ?? 0, currency)}</div></div></div>
      <div style={{ padding: 16, display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(145px,1fr))', gap: 10, background: 'linear-gradient(180deg,#fff,#f8fafc)' }}><Metric label="Base Salary" value={money(summary?.base_salary ?? 0, currency)} /><Metric label="Overtime" value={money(summary?.overtime_amount ?? 0, currency)} /><Metric label="Adjustments" value={money(summary?.adjustments ?? 0, currency)} /><Metric label="Bonus" value={money(summary?.bonus_amount ?? 0, currency)} /></div>
    </section>

    <section className="salary-dashboard-card" style={{ ...panel, ...dashboardStyle('grand_salary'), marginBottom: 16, padding: 18, transition: 'transform .18s ease,box-shadow .18s ease' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'flex-start', flexWrap: 'wrap' }}><div><div style={{ color: '#4f46e5', fontSize: 10, fontWeight: 950, letterSpacing: '.13em' }}>GRAND SALARY</div><h2 style={{ margin: '6px 0 2px', fontSize: 31, letterSpacing: '-.05em', color: '#0f172a', textShadow: '0 2px 6px rgba(15,23,42,.08)' }}>{money(grand.total, currency)}</h2><p style={{ margin: 0, color: '#64748b', fontSize: 12 }}>Finalized salary months only</p></div><div className="salary-dashboard-glass" style={{ padding: '9px 12px', borderRadius: 12, color: '#334155', fontWeight: 900, fontSize: 11 }}>{grand.months} completed {grand.months === 1 ? 'month' : 'months'}</div></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(145px,1fr))', gap: 10, marginTop: 16 }}><Metric label="Total Base" value={money(grand.base, currency)} /><Metric label="Total Overtime" value={money(grand.overtime, currency)} /><Metric label="Total Bonuses" value={money(grand.bonuses, currency)} /><Metric label="Total Adjustments" value={money(grand.adjustments, currency)} /></div></section>

    <section className="salary-dashboard-card" style={{ ...dashboardStyle('salary_overview'), display: hiddenDashboardCards.includes('salary_overview') ? 'none' : 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(250px,1fr))', gap: 14, marginBottom: 16, transition: 'transform .18s ease' }}>
      <InfoCard title="Attendance" icon="✓"><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}><Mini label="Present" value={String(summary?.present_days ?? 0)} /><Mini label="Absent" value={String(summary?.absent_days ?? 0)} /><Mini label="Leave" value={String(summary?.leave_days ?? 0)} /><Mini label="Paid Days" value={String(summary?.paid_days ?? 0)} /></div><div className="salary-dashboard-glass" style={{ marginTop: 14, padding: 11, borderRadius: 12 }}><strong>{Number(summary?.attendance_percentage ?? 0).toFixed(1)}%</strong> attendance</div></InfoCard>
      <InfoCard title="Overtime" icon="↗"><div style={{ fontSize: 29, fontWeight: 950, letterSpacing: '-.04em' }}>{Number(summary?.overtime_hours ?? 0).toFixed(2)} h</div><p style={{ margin: '4px 0 0', color: '#64748b', fontSize: 12 }}>Total overtime hours</p><div style={{ marginTop: 14, fontWeight: 950, fontSize: 16, color: '#0f766e' }}>{money(summary?.overtime_amount ?? 0, currency)}</div><p style={{ margin: '3px 0 0', color: '#64748b', fontSize: 11 }}>Calculated from your saved salary policy.</p></InfoCard>
      <InfoCard title="Allowance" icon="＋"><div>{allowances.length === 0 ? <button className="salary-dashboard-action" type="button" onClick={() => navigate('/work/finance?setup=1&focus=allowances')} style={{ width: '100%', border: 0, background: 'transparent', padding: 0, textAlign: 'left', cursor: 'pointer', font: 'inherit' }}><div style={{ padding: 13, borderRadius: 14, background: 'linear-gradient(145deg,#fffbeb,#fef3c7)', border: '1px solid #fde68a', boxShadow: '0 7px 14px rgba(245,158,11,.08),inset 0 1px 0 #fff' }}><div style={{ fontSize: 10, color: '#b45309', fontWeight: 950, letterSpacing: '.1em', textTransform: 'uppercase' }}>Not set</div><div style={{ marginTop: 5, fontSize: 22, fontWeight: 950 }}>Configure allowances</div><p style={{ margin: '7px 0 0', color: '#64748b', fontSize: 12 }}>Tap to open Salary Settings and set your allowance rules.</p><div style={{ marginTop: 9, color: '#b45309', fontWeight: 950 }}>Set →</div></div></button> : <><button className="salary-dashboard-action" type="button" onClick={() => setAllowanceOpen(open => !open)} aria-expanded={allowanceOpen} style={{ width: '100%', border: 0, background: 'transparent', padding: 0, textAlign: 'left', cursor: 'pointer', font: 'inherit' }}><div style={{ padding: 13, borderRadius: 14, background: 'linear-gradient(145deg,#ecfdf5,#d1fae5)', border: '1px solid #bbf7d0', boxShadow: '0 8px 16px rgba(16,185,129,.08),inset 0 1px 0 #fff' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}><div><div style={{ fontSize: 10, color: '#047857', fontWeight: 950, letterSpacing: '.1em', textTransform: 'uppercase' }}>Set</div><div style={{ marginTop: 5, fontSize: 23, fontWeight: 950 }}>{money(allowanceTotal, currency)}</div><p style={{ margin: '6px 0 0', color: '#64748b', fontSize: 12 }}>{allowances.length} allowance{allowances.length === 1 ? '' : 's'} configured</p></div><span aria-hidden="true" style={{ fontSize: 22, color: '#047857', fontWeight: 950 }}>{allowanceOpen ? '⌃' : '⌄'}</span></div></div></button>{allowanceOpen && <div style={{ marginTop: 10, display: 'grid', gap: 8 }}>{allowances.map(row => <div className="salary-dashboard-mini" key={row.id} style={{ padding: 11, borderRadius: 12 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, alignItems: 'flex-start' }}><div><strong style={{ fontSize: 13 }}>{row.allowance_type}</strong><div style={{ marginTop: 3, color: '#64748b', fontSize: 11 }}>{row.frequency === 'monthly' ? 'Monthly' : 'Other'} · {allowanceRuleLabel(row)}</div></div><strong style={{ fontSize: 13 }}>{money(Number(row.amount), currency)}</strong></div>{row.rule_note && row.eligibility_rule !== 'custom' && <div style={{ marginTop: 7, color: '#64748b', fontSize: 11, lineHeight: 1.4 }}>{row.rule_note}</div>}</div>)}<div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 2 }}>{allowanceSettingsButton}</div></div>}</>}</div></InfoCard>
      <InfoCard title="Bonus" icon="★"><div style={{ fontSize: 25, fontWeight: 950 }}>{money(summary?.bonus_amount ?? 0, currency)}</div><p style={{ margin: '4px 0 0', color: '#64748b', fontSize: 12 }}>Bonuses recorded this month</p><div className="salary-dashboard-glass" style={{ marginTop: 14, padding: 10, borderRadius: 12, color: '#475569', fontSize: 12 }}>{policy ? salaryTypeAction : 'Complete salary setup to configure your policy.'}</div></InfoCard>
    </section>

    <section className="salary-dashboard-card" style={{ ...panel, ...dashboardStyle('daily_work'), marginBottom: 16, padding: 18, transition: 'transform .18s ease,box-shadow .18s ease' }}><div style={{ marginBottom: 14 }}><div style={{ color: '#4f46e5', fontSize: 10, fontWeight: 950, letterSpacing: '.13em' }}>DAILY WORK RECORD</div><h2 style={{ margin: '5px 0 3px', fontSize: 21, letterSpacing: '-.025em' }}>Attendance & Overtime</h2><p style={{ margin: 0, color: '#64748b', fontSize: 12 }}>Keep today's work record accurate. Overtime is calculated using your saved policy.</p></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(230px,1fr))', gap: 14 }}>
      <div className="salary-dashboard-mini" style={{ padding: 15, borderRadius: 16 }}><button className="salary-dashboard-action" type="button" onClick={() => setAttendanceOpen(open => !open)} style={{ width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 0, border: 0, background: 'transparent', cursor: 'pointer', textAlign: 'left', font: 'inherit' }}><span><span style={{ display: 'block', fontSize: 17, fontWeight: 900 }}>Attendance</span><span style={{ display: 'block', marginTop: 3, color: '#64748b', fontSize: 11 }}>{attendance === 'present' ? 'Present' : attendance === 'absent' ? 'Absent' : 'Leave'} · {attendanceDate}</span></span><span aria-hidden="true" style={{ fontSize: 18, color: '#6366f1' }}>{attendanceOpen ? '⌃' : '⌄'}</span></button>{attendanceOpen && <div style={{ marginTop: 14 }}><label style={labelStyle}>Date<input type="date" value={attendanceDate} onChange={e => setAttendanceDate(e.target.value)} style={input} /></label><label style={labelStyle}>Status<select value={attendance} onChange={e => { const value = e.target.value as AttendanceStatus; setAttendance(value); setAttendanceOpen(value !== 'present'); }} style={input}><option value="present">Present</option><option value="absent">Absent</option><option value="leave">Leave</option></select></label><button className="salary-dashboard-action" type="button" disabled={busy} onClick={() => void saveAttendanceEntry()} style={{ ...primaryButton, width: '100%' }}>{busy ? 'Saving…' : 'Save Attendance'}</button></div>}</div>
      <div className="salary-dashboard-mini" style={{ padding: 15, borderRadius: 16 }}><button className="salary-dashboard-action" type="button" onClick={() => setOvertimeOpen(open => !open)} style={{ width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 0, border: 0, background: 'transparent', cursor: 'pointer', textAlign: 'left', font: 'inherit' }}><span><span style={{ display: 'block', fontSize: 17, fontWeight: 900 }}>Add Overtime</span><span style={{ display: 'block', marginTop: 3, color: '#64748b', fontSize: 11 }}>{overtimeHours ? `${overtimeHours} h` : 'No overtime entered'} · {overtimeDate}</span></span><span aria-hidden="true" style={{ fontSize: 18, color: '#6366f1' }}>{overtimeOpen ? '⌃' : '＋'}</span></button>{overtimeOpen && <div style={{ marginTop: 14 }}><label style={labelStyle}>Work date<input type="date" value={overtimeDate} onChange={e => setOvertimeDate(e.target.value)} style={input} /></label><label style={labelStyle}>Overtime hours<input type="number" min="0.25" step="0.25" value={overtimeHours} onChange={e => setOvertimeHours(e.target.value)} placeholder="e.g. 2.5" style={input} /></label><button className="salary-dashboard-action" type="button" disabled={busy} onClick={() => void saveOvertimeEntry()} style={{ ...primaryButton, width: '100%' }}>{busy ? 'Saving…' : 'Add Overtime'}</button></div>}</div>
    </div>{status && <div role="status" className="salary-dashboard-glass" style={{ marginTop: 12, padding: 11, borderRadius: 12, color: '#334155', fontSize: 12 }}>{status}</div>}</section>

    <section className="salary-dashboard-card" style={{ ...panel, ...dashboardStyle('monthly_detail'), padding: 18, transition: 'transform .18s ease,box-shadow .18s ease' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center', marginBottom: 12 }}><div><div style={{ color: '#4f46e5', fontSize: 10, fontWeight: 950, letterSpacing: '.13em' }}>MONTHLY DETAIL</div><h2 style={{ margin: '5px 0', fontSize: 21 }}>{title}</h2></div>{salaryTypeAction}</div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(150px,1fr))', gap: 10 }}><Metric label="Present" value={`${summary?.present_days ?? 0} days`} /><Metric label="Absent" value={`${summary?.absent_days ?? 0} days`} /><Metric label="Leave" value={`${summary?.leave_days ?? 0} days`} /><Metric label="Overtime" value={`${Number(summary?.overtime_hours ?? 0).toFixed(2)} h`} /><Metric label="Final Salary" value={money(summary?.final_salary ?? 0, currency)} strong /></div><p style={{ margin: '14px 0 0', color: '#64748b', fontSize: 11.5 }}>Previous months can be reviewed with the Previous button above. Grand Salary counts only finalized periods.</p></section>
  </main>;
}

function InfoCard({ title, icon, children }: { title: string; icon: string; children: React.ReactNode }) { return <section style={{ ...panel, padding: 17 }}><div style={{ display: 'flex', gap: 9, alignItems: 'center', marginBottom: 14 }}><span aria-hidden="true" style={{ width: 32, height: 32, display: 'grid', placeItems: 'center', borderRadius: 11, background: 'linear-gradient(145deg,#fff,#eef2ff)', color: '#4f46e5', fontWeight: 950, boxShadow: '0 6px 12px rgba(79,70,229,.08),inset 0 1px 0 #fff', textShadow: '0 1px 0 #fff' }}>{icon}</span><h2 style={{ margin: 0, fontSize: 18, letterSpacing: '-.02em', color: '#172033' }}>{title}</h2></div>{children}</section>; }
const labelStyle = { display: 'grid', gap: 6, marginBottom: 11, color: '#334155', fontSize: 13, fontWeight: 800 };
function Metric({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className="salary-dashboard-metric" style={{ padding: 12, borderRadius: 14 }}><div style={{ color: '#64748b', fontSize: 10, fontWeight: 900, textTransform: 'uppercase', letterSpacing: '.06em' }}>{label}</div><div style={{ marginTop: 5, fontSize: strong ? 20 : 15, fontWeight: strong ? 950 : 850, color: '#111827', letterSpacing: strong ? '-.035em' : undefined }}>{value}</div></div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="salary-dashboard-mini" style={{ padding: 11, borderRadius: 12 }}><div style={{ color: '#64748b', fontSize: 11 }}>{label}</div><strong style={{ display: 'block', marginTop: 3, fontSize: 18, color: '#111827' }}>{value}</strong></div>; }