import { useEffect, useMemo, useState } from 'react';
import { navigate } from '../../../app/Router';
import { useCurrentWorkerProfileId } from '../hooks/useCurrentWorkerProfileId';
import { useWorkerWorkHistory } from '../hooks/useWorkerWorkHistory';
import type { WorkHistoryPeriod, WorkHistoryPeriodBounds } from '../api/workEntries';
import { getWorkerWorkTotals } from '../api/workEntries';
import { formatWorkDecimal, getWorkerWorkDayBounds, getWorkerWorkMonthBounds, getWorkerWorkPeriodBounds, getWorkerWorkWeekBounds, getWorkerWorkWeekStart } from '../logic/workEntryCalculations';
import type { WorkerWorkTotals } from '../types/workEntry';
import { WorkerWorkEntryDetails } from '../components/WorkerWorkEntryDetails';
import { WorkerWorkEntryList } from '../components/WorkerWorkEntryList';

const EMPTY_TOTALS: WorkerWorkTotals = { daily_total: '0', weekly_total: '0', monthly_total: '0', lifetime_total: '0' };
type SelectedPeriod = Date;

function readPeriod(): WorkHistoryPeriod { const value = new URLSearchParams(window.location.search).get('period'); return value === 'day' || value === 'week' || value === 'month' ? value : 'lifetime'; }
function parseDateKey(raw: string | null): Date | null { if (!raw || !/^\d{4}-\d{2}-\d{2}$/.test(raw)) return null; const [year, month, day] = raw.split('-').map(Number); const date = new Date(year, month - 1, day); return date.getFullYear() === year && date.getMonth() === month - 1 && date.getDate() === day ? date : null; }
function readSelectedPeriod(period: WorkHistoryPeriod): SelectedPeriod { const params = new URLSearchParams(window.location.search); const raw = period === 'week' ? params.get('week') : period === 'day' ? params.get('day') : period === 'month' ? params.get('month') : null; const parsed = parseDateKey(raw); if (parsed) return period === 'week' ? getWorkerWorkWeekStart(parsed) : period === 'month' ? new Date(parsed.getFullYear(), parsed.getMonth(), 1) : parsed; return period === 'week' ? getWorkerWorkWeekStart() : period === 'month' ? new Date(new Date().getFullYear(), new Date().getMonth(), 1) : new Date(); }
function formatDate(value: Date) { return value.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }); }
function dateKey(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; }
function monthKey(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-01`; }
function shiftDay(value: Date, amount: number) { const next = new Date(value); next.setDate(next.getDate() + amount); return next; }
function shiftMonth(value: Date, amount: number) { return new Date(value.getFullYear(), value.getMonth() + amount, 1); }
function shiftWeek(value: Date, amount: number) { const next = new Date(value); next.setDate(next.getDate() + amount * 7); return getWorkerWorkWeekStart(next); }

export function WorkerWorkHistoryPage() {
  const session = useCurrentWorkerProfileId();
  const [period, setPeriod] = useState<WorkHistoryPeriod>(() => readPeriod());
  const [selectedPeriod, setSelectedPeriod] = useState<SelectedPeriod>(() => readSelectedPeriod(readPeriod()));
  const [totals, setTotals] = useState<WorkerWorkTotals>(EMPTY_TOTALS);
  const [totalsLoading, setTotalsLoading] = useState(true);
  const isDay = period === 'day'; const isWeek = period === 'week'; const isMonth = period === 'month';
  const currentDay = useMemo(() => { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), now.getDate()); }, []);
  const currentMonth = useMemo(() => { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), 1); }, []);
  const currentWeekStart = useMemo(() => getWorkerWorkWeekStart(), []);
  const selectedBounds: WorkHistoryPeriodBounds | null = useMemo(() => { if (isDay) { const bounds = getWorkerWorkDayBounds(selectedPeriod); return { start: bounds.dayStart, end: bounds.dayEnd }; } if (isWeek) { const bounds = getWorkerWorkWeekBounds(selectedPeriod); return { start: bounds.weekStart, end: bounds.weekEnd }; } if (isMonth) { const bounds = getWorkerWorkMonthBounds(selectedPeriod); return { start: bounds.monthStart, end: bounds.monthEnd }; } return null; }, [isDay, isWeek, isMonth, selectedPeriod]);
  const history = useWorkerWorkHistory(session.profileId ?? '', period, selectedBounds);

  useEffect(() => { if (!session.profileId) return; let active = true; setTotalsLoading(true); const bounds = getWorkerWorkPeriodBounds(selectedPeriod); if (isDay) { const selected = getWorkerWorkDayBounds(selectedPeriod); bounds.dayStart = selected.dayStart; bounds.dayEnd = selected.dayEnd; } if (isWeek) { const selected = getWorkerWorkWeekBounds(selectedPeriod); bounds.weekStart = selected.weekStart; bounds.weekEnd = selected.weekEnd; } if (isMonth) { const selected = getWorkerWorkMonthBounds(selectedPeriod); bounds.monthStart = selected.monthStart; bounds.monthEnd = selected.monthEnd; } void getWorkerWorkTotals(bounds).then((result) => { if (!active) return; if (!result.error) setTotals(result.data); setTotalsLoading(false); }); return () => { active = false; }; }, [session.profileId, isDay, isWeek, isMonth, selectedPeriod]);

  const changePeriod = (next: WorkHistoryPeriod) => { setPeriod(next); const nextSelected = readSelectedPeriod(next); setSelectedPeriod(nextSelected); if (next === 'week') navigate(`/work/history?period=week&week=${dateKey(nextSelected)}`); else if (next === 'day') navigate(`/work/history?period=day&day=${dateKey(nextSelected)}`); else if (next === 'month') navigate(`/work/history?period=month&month=${monthKey(nextSelected)}`); else navigate('/work/history'); };
  const changeSelectedPeriod = (amount: number) => { const next = isDay ? shiftDay(selectedPeriod, amount) : isWeek ? shiftWeek(selectedPeriod, amount) : shiftMonth(selectedPeriod, amount); setSelectedPeriod(next); if (isDay) navigate(`/work/history?period=day&day=${dateKey(next)}`); else if (isWeek) navigate(`/work/history?period=week&week=${dateKey(next)}`); else navigate(`/work/history?period=month&month=${monthKey(next)}`); };
  const isCurrentDay = selectedPeriod.getTime() === currentDay.getTime(); const isCurrentWeek = selectedPeriod.getTime() === currentWeekStart.getTime(); const isCurrentMonth = selectedPeriod.getTime() === currentMonth.getTime(); const nextDisabled = isDay ? isCurrentDay : isWeek ? isCurrentWeek : isCurrentMonth;
  const editEntry = async (...args: Parameters<typeof history.editEntry>) => history.editEntry(...args); const trashEntry = async (entryId: string) => history.trashEntry(entryId);

  if (session.loading) return <main className="worker-history"><section className="worker-history__state"><span className="worker-history__state-mark" aria-hidden="true">◌</span><p>Loading Work History…</p></section></main>;
  if (session.error || !session.profileId) return <main className="worker-history"><section className="worker-history__state worker-history__state--error"><span className="worker-history__state-mark" aria-hidden="true">!</span><p role="alert">{session.error ?? 'Authenticated profile is unavailable.'}</p></section></main>;

  let periodLabel = ''; if (isDay) periodLabel = formatDate(selectedPeriod); else if (isWeek) { const end = new Date(selectedPeriod); end.setDate(end.getDate() + 6); periodLabel = `${formatDate(selectedPeriod)} – ${formatDate(end)}`; } else if (isMonth) periodLabel = selectedPeriod.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });

  return <main className="worker-history">
    <style>{`
      .worker-history{--ink:#172033;--muted:#64748b;--blue:#2563eb;--violet:#635bdb;--teal:#0f9f95;width:100%;max-width:760px;margin:0 auto;padding:14px 10px 104px;box-sizing:border-box;color:var(--ink)}
      .worker-history:before{content:'';position:fixed;inset:0;z-index:-1;pointer-events:none;background:radial-gradient(70% 35% at 10% 0%,rgba(37,99,235,.07),transparent 70%),radial-gradient(60% 35% at 100% 42%,rgba(15,159,149,.055),transparent 70%),linear-gradient(180deg,#f8fafc,#f3f6fa 60%,#f8fafc)}
      .wh-surface{position:relative;isolation:isolate;border:1px solid rgba(71,85,105,.15);border-radius:16px;background:linear-gradient(150deg,#ffffff 0%,#f8fafc 62%,#f1f5ff 100%);box-shadow:0 1px 0 rgba(255,255,255,.98) inset,0 -1px 0 rgba(71,85,105,.08) inset,0 3px 5px rgba(15,23,42,.07),0 10px 16px rgba(15,23,42,.065),0 22px 32px rgba(15,23,42,.035)}
      .wh-surface:before{content:'';position:absolute;z-index:-1;left:7%;right:7%;bottom:-8px;height:14px;border-radius:50%;background:rgba(15,23,42,.16);filter:blur(9px);opacity:.55}.wh-surface:after{content:'';position:absolute;top:0;left:12px;right:12px;height:1px;border-radius:99px;background:linear-gradient(90deg,transparent,rgba(255,255,255,1) 18%,rgba(99,102,241,.38) 55%,transparent);box-shadow:0 1px 5px rgba(255,255,255,.9)}
      .worker-history__hero{padding:13px 14px;margin-bottom:10px}.worker-history__back,.worker-history__nav-button,.worker-history__more{appearance:none;border:1px solid rgba(71,85,105,.18);border-radius:10px;background:linear-gradient(155deg,#fff 0%,#f5f7fa 58%,#e9edf3 100%);color:#273449;font:inherit;font-size:10px;font-weight:900;letter-spacing:.01em;box-shadow:0 1px 0 #fff inset,0 -2px 0 rgba(71,85,105,.08) inset,0 3px 5px rgba(15,23,42,.09),0 7px 11px rgba(15,23,42,.055);cursor:pointer;transition:transform .14s ease,box-shadow .14s ease,border-color .14s ease}.worker-history__back{min-height:34px;padding:0 10px}.worker-history__back:hover,.worker-history__nav-button:hover:not(:disabled),.worker-history__more:hover:not(:disabled){transform:translateY(-1px);border-color:rgba(79,70,229,.3);box-shadow:0 1px 0 #fff inset,0 -2px 0 rgba(71,85,105,.07) inset,0 5px 8px rgba(15,23,42,.1),0 10px 15px rgba(79,70,229,.055)}.worker-history__back:active,.worker-history__nav-button:active:not(:disabled),.worker-history__more:active:not(:disabled){transform:translateY(1px);box-shadow:0 1px 2px rgba(15,23,42,.12) inset,0 2px 4px rgba(15,23,42,.08)}
      .worker-history__back:focus-visible,.worker-history__segment:focus-visible,.worker-history__nav-button:focus-visible,.worker-history__more:focus-visible{outline:2px solid rgba(79,70,229,.72);outline-offset:3px}.worker-history__title{margin:9px 0 0;font-size:27px;line-height:1.05;letter-spacing:-.045em;font-weight:900;text-shadow:0 1px 0 #fff,0 2px 5px rgba(15,23,42,.09)}.worker-history__description{margin:5px 0 0;color:var(--muted);font-size:10.5px;line-height:1.45}
      .worker-history__total{padding:13px 14px;margin-bottom:10px;background:linear-gradient(145deg,#f1f7ff 0%,#fff 45%,#f0fdfb 100%);border-color:rgba(37,99,235,.2);box-shadow:0 1px 0 #fff inset,0 -2px 0 rgba(37,99,235,.08) inset,0 4px 6px rgba(15,23,42,.075),0 13px 19px rgba(37,99,235,.065),0 24px 32px rgba(15,23,42,.035)}.worker-history__total:before{background:linear-gradient(90deg,rgba(37,99,235,.18),rgba(15,159,149,.12));filter:blur(11px);bottom:-7px}.worker-history__eyebrow{display:flex;align-items:center;gap:7px;color:#475569;font-size:9px;font-weight:950;letter-spacing:.1em;text-transform:uppercase}.worker-history__eyebrow:before{content:'∞';display:grid;place-items:center;width:25px;height:25px;border:1px solid rgba(37,99,235,.2);border-radius:8px;background:linear-gradient(150deg,#fff,#dbeafe 70%,#ccfbf1);color:#2563eb;box-shadow:0 2px 3px rgba(15,23,42,.08),0 5px 8px rgba(37,99,235,.08),1px 1px 0 #fff inset,-1px -1px 2px rgba(37,99,235,.08) inset}.worker-history__total-value{margin-top:5px;color:#0f172a;font-size:32px;line-height:1;letter-spacing:-.055em;font-weight:950;text-shadow:0 1px 0 #fff,0 2px 3px rgba(15,23,42,.12),0 5px 10px rgba(37,99,235,.07)}.worker-history__total-copy{margin:5px 0 0;color:#64748b;font-size:9.5px;line-height:1.35;font-weight:650}
      .worker-history__segments{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;padding:4px;margin-bottom:10px;border:1px solid rgba(71,85,105,.14);border-radius:13px;background:linear-gradient(145deg,#e9edf3,#f9fafb);box-shadow:0 1px 0 #fff inset,0 -1px 2px rgba(71,85,105,.08) inset,0 5px 10px rgba(15,23,42,.07),0 10px 15px rgba(15,23,42,.035)}.worker-history__segment{min-width:0;min-height:34px;padding:0 5px;border:1px solid transparent;border-radius:9px;background:transparent;color:#64748b;font:inherit;font-size:10px;font-weight:900;cursor:pointer;transition:transform .12s ease,box-shadow .12s ease,background .12s ease,color .12s ease}.worker-history__segment[aria-pressed=true]{color:#312e81;background:linear-gradient(155deg,#fff,#eef2ff 65%,#e0e7ff);border-color:rgba(79,70,229,.25);box-shadow:0 1px 0 #fff inset,0 -2px 0 rgba(79,70,229,.08) inset,0 3px 5px rgba(15,23,42,.1),0 6px 9px rgba(79,70,229,.07)}.worker-history__segment:hover:not([aria-pressed=true]){background:rgba(255,255,255,.6);color:#334155}.worker-history__segment:active{transform:translateY(1px);box-shadow:0 1px 3px rgba(15,23,42,.1) inset}
      .worker-history__selected{padding:13px 14px;margin-bottom:10px}.worker-history__selected-label{color:#64748b;font-size:9px;font-weight:950;letter-spacing:.1em;text-transform:uppercase}.worker-history__date{margin-top:4px;font-size:18px;line-height:1.15;font-weight:900;letter-spacing:-.03em;text-shadow:0 1px 0 #fff,0 2px 4px rgba(15,23,42,.08)}.worker-history__nav{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:10px}.worker-history__nav-button{min-height:38px;padding:0 7px}.worker-history__nav-button:disabled{opacity:.42;cursor:not-allowed;box-shadow:0 1px 0 #fff inset,0 2px 4px rgba(15,23,42,.05)}.worker-history__daily{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:9px;padding:8px 10px;border:1px solid rgba(37,99,235,.17);border-radius:10px;background:linear-gradient(150deg,#edf6ff,#fff 58%,#effdfa);box-shadow:0 1px 0 #fff inset,0 -1px 1px rgba(37,99,235,.08) inset,0 3px 5px rgba(37,99,235,.07),0 7px 12px rgba(15,23,42,.045)}.worker-history__daily span{color:#64748b;font-size:10px;font-weight:850}.worker-history__daily strong{color:#0f172a;font-size:25px;line-height:1;font-weight:950;letter-spacing:-.055em;text-shadow:0 1px 0 #fff,0 3px 6px rgba(15,23,42,.13),0 0 10px rgba(37,99,235,.08)}
      .worker-history__list-title{display:flex;align-items:center;justify-content:space-between;margin:0 2px 7px}.worker-history__list-title h2{margin:0;font-size:16px;letter-spacing:-.02em}.worker-history__list-title span{color:#94a3b8;font-size:9px;font-weight:800}.worker-history__state{position:relative;display:flex;align-items:center;gap:8px;padding:12px 13px;margin:0;border:1px solid rgba(71,85,105,.14);border-radius:13px;background:linear-gradient(145deg,#fff,#f5f7fa);box-shadow:0 1px 0 #fff inset,0 -1px 0 rgba(71,85,105,.06) inset,0 4px 7px rgba(15,23,42,.065),0 10px 14px rgba(15,23,42,.035);color:#64748b;font-size:11px;font-weight:750}.worker-history__state p{margin:0}.worker-history__state-mark{display:grid;place-items:center;flex:0 0 25px;width:25px;height:25px;border:1px solid rgba(99,102,241,.16);border-radius:8px;background:linear-gradient(145deg,#fff,#eef2ff);color:#4f46e5;box-shadow:0 3px 5px rgba(15,23,42,.07),1px 1px 0 #fff inset}.worker-history__state--error{color:#b91c1c;background:linear-gradient(145deg,#fff,#fff5f5);border-color:rgba(185,28,28,.16)}.worker-history__state--error .worker-history__state-mark{color:#b91c1c;background:#fff1f2}
      .worker-history__more{display:block;width:100%;min-height:38px;margin-top:8px;padding:0 10px}.worker-history__more:disabled{opacity:.5;cursor:not-allowed}
      @media (min-width:700px){.worker-history{padding-top:20px}.worker-history__title{font-size:29px}.worker-history__total-value{font-size:34px}.worker-history__daily strong{font-size:26px}}
      @media (max-width:430px){.worker-history{padding-left:8px;padding-right:8px}.worker-history__hero{padding:12px}.worker-history__title{font-size:25px}.worker-history__description{font-size:10px}.worker-history__total{padding:12px}.worker-history__total-value{font-size:30px}.worker-history__selected{padding:12px}.worker-history__date{font-size:17px}.worker-history__nav-button{font-size:9.5px}.worker-history__daily strong{font-size:23px}.worker-history__list-title h2{font-size:15px}}
      @media (max-width:340px){.worker-history__segment{font-size:9px}.worker-history__nav-button{font-size:9px;padding:0 4px}.worker-history__daily{padding:7px 8px}.worker-history__daily strong{font-size:22px}}
      @media (prefers-reduced-motion:reduce){.worker-history *{transition:none!important}}
    `}</style>
    <header className="worker-history__hero wh-surface"><button className="worker-history__back" type="button" onClick={() => navigate('/work')}>← Work House</button><h1 className="worker-history__title">Work History</h1><p className="worker-history__description">Real persisted Work Entries, newest first. The list loads five initially, then ten more per request.</p></header>
    <section className="worker-history__total wh-surface" aria-label="Lifetime Grand Total"><div className="worker-history__eyebrow">Lifetime / Grand Total</div><div className="worker-history__total-value" aria-live="polite">{totalsLoading ? 'Loading…' : formatWorkDecimal(totals.lifetime_total)}</div><p className="worker-history__total-copy">Authoritative persisted total; independent from the visible page size.</p></section>
    <nav className="worker-history__segments" aria-label="Work History shortcuts">{(['lifetime','day','week','month'] as const).map((item) => <button className="worker-history__segment" key={item} type="button" onClick={() => changePeriod(item)} aria-pressed={period === item}>{item === 'lifetime' ? 'All' : item[0].toUpperCase() + item.slice(1)}</button>)}</nav>
    {(isDay || isWeek || isMonth) && <section className="worker-history__selected wh-surface" aria-label={`Selected ${period}`}><div className="worker-history__selected-label">Selected {isDay ? 'Day' : isWeek ? 'Week' : 'Month'}</div><div className="worker-history__date">{periodLabel}</div><div className="worker-history__nav"><button className="worker-history__nav-button" type="button" onClick={() => changeSelectedPeriod(-1)}>{isDay ? '← Previous Day' : isWeek ? '← Previous Week' : '← Previous Month'}</button><button className="worker-history__nav-button" type="button" onClick={() => changeSelectedPeriod(1)} disabled={nextDisabled}>{isDay ? 'Next Day →' : isWeek ? 'Next Week →' : 'Next Month →'}</button></div><div className="worker-history__daily"><span>{isDay ? 'Daily Total' : isWeek ? 'Weekly Total' : 'Monthly Total'}</span><strong>{totalsLoading ? 'Loading…' : formatWorkDecimal(isDay ? totals.daily_total : isWeek ? totals.weekly_total : totals.monthly_total)}</strong></div></section>}
    <section aria-labelledby="worker-history-list-heading"><div className="worker-history__list-title"><h2 id="worker-history-list-heading">Work Entries</h2>{!history.loading && history.entries.length > 0 && <span>{history.entries.length}{history.hasMore ? '+' : ''} loaded</span>}</div>{history.actionError && <p className="worker-history__state worker-history__state--error" role="alert"><span className="worker-history__state-mark" aria-hidden="true">!</span><span>{history.actionError}</span></p>}{history.loading ? <section className="worker-history__state"><span className="worker-history__state-mark" aria-hidden="true">◌</span><p>Loading Work History…</p></section> : history.entries.length === 0 ? <section className="worker-history__state" style={{display:'block',textAlign:'center'}}><span className="worker-history__state-mark" aria-hidden="true">○</span><h3 style={{margin:'7px 0 0',fontSize:15,color:'#172033'}}>No Work Entries yet</h3><p style={{margin:'4px 0 0'}}>Persisted Work Entries will appear here when they exist.</p></section> : <><WorkerWorkEntryList entries={history.entries} onOpen={(entry) => void history.openDetails(entry)} />{history.hasMore && <button className="worker-history__more" type="button" onClick={() => void history.loadMore()} disabled={history.loadingMore}>{history.loadingMore ? 'Loading more…' : 'Load More'}</button>}</>}</section>
    <WorkerWorkEntryDetails entry={history.selectedEntry} versions={history.versions} versionsLoading={history.versionsLoading} actionError={history.actionError} onClose={history.closeDetails} onEdit={editEntry} onTrash={trashEntry} />
  </main>;
}
