import { useEffect, useRef, useState, type JSX } from 'react';
import { listPosts, type PostFeedScope } from '../api/listPosts';
import { deletePost } from '../api/deletePost';
import { updatePost } from '../api/updatePost';
import { updatePostPrivacy, type PostPrivacy } from '../api/updatePostPrivacy';
import { supabase } from '../../../lib/supabase/client';

interface PostFeedProps { refreshKey: number; profileId: string; feedProfileId?: string; scope?: PostFeedScope; }
type ReactionName = 'like' | 'love' | 'haha' | 'wow' | 'sad' | 'angry';
const privacyLabels: Record<PostPrivacy, string> = { public: '🌎 Public', friends: '👥 Friends', private: '🔒 Only me' };
const reactionOptions: { value: ReactionName; emoji: string; label: string }[] = [
  { value: 'like', emoji: '👍', label: 'Like' }, { value: 'love', emoji: '❤️', label: 'Love' }, { value: 'haha', emoji: '😂', label: 'Haha' },
  { value: 'wow', emoji: '😮', label: 'Wow' }, { value: 'sad', emoji: '😢', label: 'Sad' }, { value: 'angry', emoji: '😡', label: 'Angry' },
];
const reactionEmoji = Object.fromEntries(reactionOptions.map((item) => [item.value, item.emoji])) as Record<ReactionName, string>;

type CommentProfile = { display_name: string | null; avatar_url: string | null };
type CommentRow = {
  id: string; post_id: string; profile_id: string; parent_comment_id: string | null; content: string;
  created_at: string; updated_at: string; profiles?: CommentProfile | CommentProfile[] | null;
};
const commentProfile = (comment: CommentRow): CommentProfile | null => Array.isArray(comment.profiles) ? (comment.profiles[0] ?? null) : (comment.profiles ?? null);

type LightboxMedia = { type: 'image' | 'video'; url: string; alt?: string };
const glassCard: React.CSSProperties = { background: 'transparent', backgroundImage: 'none', border: '0', boxShadow: 'none', backdropFilter: 'none', WebkitBackdropFilter: 'none' };
const softButton: React.CSSProperties = { border: '0', borderRadius: 999, background: 'transparent', backgroundImage: 'none', boxShadow: 'none', cursor: 'pointer', fontWeight: 600 };
const hudNameStyle: React.CSSProperties = { color: 'inherit' };
const hudWritingStyle: React.CSSProperties = { color: 'inherit', background: 'transparent' };
export function PostFeed({ refreshKey, profileId, feedProfileId, scope = 'profile' }: PostFeedProps) {
  const [posts, setPosts] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editContent, setEditContent] = useState('');
  const [openMenuId, setOpenMenuId] = useState<string | null>(null);
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const [openReactionId, setOpenReactionId] = useState<string | null>(null);
  const [reactionCounts, setReactionCounts] = useState<Record<string, Record<string, number>>>({});
  const [myReactions, setMyReactions] = useState<Record<string, ReactionName | null>>({});
  const [comments, setComments] = useState<Record<string, CommentRow[]>>({});
  const [commentText, setCommentText] = useState<Record<string, string>>({});
  const [openCommentsId, setOpenCommentsId] = useState<string | null>(null);
  const [replyToCommentId, setReplyToCommentId] = useState<string | null>(null);
  const [replyText, setReplyText] = useState('');
  const [openCommentMenuId, setOpenCommentMenuId] = useState<string | null>(null);
  const [editingCommentId, setEditingCommentId] = useState<string | null>(null);
  const [editingCommentText, setEditingCommentText] = useState('');
  const [commentReactionCounts, setCommentReactionCounts] = useState<Record<string, Record<string, number>>>({});
  const [myCommentReactions, setMyCommentReactions] = useState<Record<string, ReactionName | null>>({});
  const [openCommentReactionId, setOpenCommentReactionId] = useState<string | null>(null);
  const [lightboxMedia, setLightboxMedia] = useState<LightboxMedia | null>(null);
  const reactionRefs = useRef<Record<string, HTMLDivElement | null>>({});
  const commentReactionRefs = useRef<Record<string, HTMLDivElement | null>>({});

  const loadInteractions = async (items: any[]) => {
    if (!items.length) return;
    const ids = items.map((post) => post.id);
    const [{ data: reactionRows, error: reactionError }, { data: commentRows, error: commentError }] = await Promise.all([
      supabase.from('post_reactions').select('post_id, profile_id, reaction').in('post_id', ids),
      supabase.from('post_comments').select('id, post_id, profile_id, parent_comment_id, content, created_at, updated_at, profiles(display_name, avatar_url)').in('post_id', ids).order('created_at', { ascending: true }),
    ]);
    if (reactionError) return setError(reactionError.message);
    if (commentError) return setError(commentError.message);
    const counts: Record<string, Record<string, number>> = {};
    const mine: Record<string, ReactionName | null> = {};
    const grouped: Record<string, CommentRow[]> = {};
    (reactionRows ?? []).forEach((row: any) => { counts[row.post_id] ??= {}; counts[row.post_id][row.reaction] = (counts[row.post_id][row.reaction] ?? 0) + 1; if (row.profile_id === profileId) mine[row.post_id] = row.reaction as ReactionName; });
    (commentRows ?? []).forEach((row: any) => { const normalized = row as CommentRow; grouped[normalized.post_id] ??= []; grouped[normalized.post_id].push(normalized); });
    setReactionCounts(counts); setMyReactions(mine); setComments(grouped);
    const commentIds = (commentRows ?? []).map((row: any) => row.id);
    if (!commentIds.length) { setCommentReactionCounts({}); setMyCommentReactions({}); return; }
    const { data: commentReactionRows, error: commentReactionError } = await supabase.from('comment_reactions').select('comment_id, profile_id, reaction').in('comment_id', commentIds);
    if (commentReactionError) return setError(commentReactionError.message);
    const commentCounts: Record<string, Record<string, number>> = {}; const commentMine: Record<string, ReactionName | null> = {};
    (commentReactionRows ?? []).forEach((row: any) => { commentCounts[row.comment_id] ??= {}; commentCounts[row.comment_id][row.reaction] = (commentCounts[row.comment_id][row.reaction] ?? 0) + 1; if (row.profile_id === profileId) commentMine[row.comment_id] = row.reaction as ReactionName; });
    setCommentReactionCounts(commentCounts); setMyCommentReactions(commentMine);
  };
  const loadPosts = async () => { const targetProfileId = scope === 'profile' ? (feedProfileId ?? profileId) : undefined; const { data, error: loadError } = await listPosts(targetProfileId, scope); if (loadError) setError(loadError.message); else { const items = data ?? []; setPosts(items); await loadInteractions(items); } };
  useEffect(() => { void loadPosts(); }, [refreshKey, profileId, feedProfileId, scope]);
  useEffect(() => { const close = (event: MouseEvent | TouchEvent) => { const target = event.target as Node; if (!Object.values(reactionRefs.current).some((node) => node?.contains(target))) setOpenReactionId(null); if (!Object.values(commentReactionRefs.current).some((node) => node?.contains(target))) setOpenCommentReactionId(null); }; document.addEventListener('mousedown', close); document.addEventListener('touchstart', close); return () => { document.removeEventListener('mousedown', close); document.removeEventListener('touchstart', close); }; }, []);
  useEffect(() => { if (!lightboxMedia) return; const previousOverflow = document.body.style.overflow; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') setLightboxMedia(null); }; document.body.style.overflow = 'hidden'; document.addEventListener('keydown', onKeyDown); return () => { document.body.style.overflow = previousOverflow; document.removeEventListener('keydown', onKeyDown); }; }, [lightboxMedia]);

  const startEdit = (post: any) => { setEditingId(post.id); setEditContent(post.content ?? ''); setOpenMenuId(null); };
  const saveEdit = async (postId: string) => { const { error: e } = await updatePost(postId, editContent); if (e) return setError(e.message); setEditingId(null); setEditContent(''); await loadPosts(); };
  const removePost = async (postId: string) => { const { error: e } = await deletePost(postId); if (e) return setError(e.message); setOpenMenuId(null); await loadPosts(); };
  const changePrivacy = async (postId: string, privacy: PostPrivacy) => { const { error: e } = await updatePostPrivacy(postId, privacy); if (e) return setError(e.message); setOpenMenuId(null); await loadPosts(); };
  const react = async (postId: string, reaction: ReactionName) => { const current = myReactions[postId]; const result = current === reaction ? await supabase.from('post_reactions').delete().eq('post_id', postId).eq('profile_id', profileId) : await supabase.from('post_reactions').upsert({ post_id: postId, profile_id: profileId, reaction }, { onConflict: 'post_id,profile_id' }); if (result.error) return setError(result.error.message); setOpenReactionId(null); await loadPosts(); };
  const addComment = async (postId: string, parentCommentId: string | null = null) => { const content = (parentCommentId ? replyText : commentText[postId] ?? '').trim(); if (!content) return; const { data, error: e } = await supabase.from('post_comments').insert({ post_id: postId, profile_id: profileId, parent_comment_id: parentCommentId, content }).select('id, post_id, profile_id, parent_comment_id, content, created_at, updated_at, profiles(display_name, avatar_url)').single(); if (e) return setError(e.message); if (parentCommentId) { setReplyText(''); setReplyToCommentId(null); } else setCommentText((current) => ({ ...current, [postId]: '' })); if (data) setComments((current) => ({ ...current, [postId]: [...(current[postId] ?? []), data as CommentRow] })); };
  const saveCommentEdit = async (commentId: string) => { const content = editingCommentText.trim(); if (!content) return; const { data, error: e } = await supabase.from('post_comments').update({ content }).eq('id', commentId).select('id, post_id, profile_id, parent_comment_id, content, created_at, updated_at, profiles(display_name, avatar_url)').single(); if (e) return setError(e.message); if (data) setComments((current) => Object.fromEntries(Object.entries(current).map(([postId, rows]) => [postId, rows.map((row) => row.id === commentId ? data as CommentRow : row)]))); setEditingCommentId(null); setEditingCommentText(''); setOpenCommentMenuId(null); };
  const deleteComment = async (commentId: string) => { if (!window.confirm('Delete this comment?')) return; const { error: e } = await supabase.from('post_comments').delete().eq('id', commentId); if (e) return setError(e.message); setComments((current) => Object.fromEntries(Object.entries(current).map(([postId, rows]) => [postId, rows.filter((row) => row.id !== commentId && row.parent_comment_id !== commentId)]))); setOpenCommentMenuId(null); };
  const reactToComment = async (commentId: string, reaction: ReactionName) => { const current = myCommentReactions[commentId]; const result = current === reaction ? await supabase.from('comment_reactions').delete().eq('comment_id', commentId).eq('profile_id', profileId) : await supabase.from('comment_reactions').upsert({ comment_id: commentId, profile_id: profileId, reaction }, { onConflict: 'comment_id,profile_id' }); if (result.error) return setError(result.error.message); setOpenCommentReactionId(null); await loadPosts(); };
  const openMedia = (type: 'image' | 'video', url: string, alt?: string) => { if (!url) return; setOpenMenuId(null); setLightboxMedia({ type, url, alt }); };

  const renderComment = (comment: CommentRow, allComments: CommentRow[], depth = 0): JSX.Element => {
    const children = allComments.filter((row) => row.parent_comment_id === comment.id); const profile = commentProfile(comment); const isOwner = comment.profile_id === profileId; const isEditing = editingCommentId === comment.id; const counts = commentReactionCounts[comment.id] ?? {}; const myReaction = myCommentReactions[comment.id]; const totalReactions = Object.values(counts).reduce((sum, value) => sum + value, 0);
    return <div key={comment.id} style={{ marginTop: 7, marginLeft: Math.min(depth, 4) * 14, paddingLeft: depth ? 8 : 0, borderLeft: depth ? '1px solid rgba(91,108,132,.14)' : undefined, minWidth: 0 }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 6, minWidth: 0 }}>
        {profile?.avatar_url ? <img src={profile.avatar_url} alt="" width={28} height={28} style={{ borderRadius: '50%', objectFit: 'cover', flexShrink: 0, boxShadow: '0 2px 7px rgba(20,35,60,.12)' }} /> : <div aria-hidden="true" style={{ width: 28, height: 28, borderRadius: '50%', display: 'grid', placeItems: 'center', background: 'linear-gradient(145deg,#f8fafc,#e7ecf2)', flexShrink: 0, fontSize: 12 }}>👤</div>}
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 5, minWidth: 0 }}><strong style={{ ...hudNameStyle, fontSize: 12 }}>{profile?.display_name ?? 'User'}</strong><small style={{ opacity: .5, whiteSpace: 'nowrap', fontSize: 9 }}>{new Date(comment.created_at).toLocaleString()}</small><div style={{ marginLeft: 'auto', position: 'relative', flexShrink: 0 }}><button type="button" aria-label="Comment options" onClick={() => setOpenCommentMenuId(openCommentMenuId === comment.id ? null : comment.id)} style={{ ...softButton, width: 26, height: 26, padding: 0, fontSize: 14 }}>⋯</button>{openCommentMenuId === comment.id && isOwner && <div role="menu" style={{ position: 'absolute', right: 0, top: 30, zIndex: 6, maxHeight: 'min(280px, calc(100dvh - 96px))', overflowY: 'auto', padding: 6, display: 'grid', gap: 3, background: '#fff', border: '1px solid rgba(80,100,130,.14)', borderRadius: 10, boxShadow: '0 10px 22px rgba(20,35,60,.14)' }}><button type="button" onClick={() => { setEditingCommentId(comment.id); setEditingCommentText(comment.content); setOpenCommentMenuId(null); }} style={{ ...softButton, border: 0, boxShadow: 'none', borderRadius: 7, padding: '5px 9px', fontSize: 11 }}>Edit</button><button type="button" onClick={() => void deleteComment(comment.id)} style={{ ...softButton, border: 0, boxShadow: 'none', borderRadius: 7, padding: '5px 9px', fontSize: 11 }}>Delete</button></div>}</div></div>
          {isEditing ? <div style={{ display: 'flex', gap: 6, marginTop: 4, minWidth: 0 }}><input value={editingCommentText} onChange={(event) => setEditingCommentText(event.target.value)} autoFocus style={{ ...hudWritingStyle, flex: 1, minWidth: 0, border: '1px solid rgba(80,100,130,.16)', borderRadius: 10, padding: '6px 8px', fontSize: 12, outline: 'none', boxSizing: 'border-box' }} /><button type="button" onClick={() => void saveCommentEdit(comment.id)} style={{ ...softButton, padding: '5px 9px', fontSize: 11 }}>Save</button><button type="button" onClick={() => { setEditingCommentId(null); setEditingCommentText(''); }} style={{ ...softButton, padding: '5px 9px', fontSize: 11 }}>Cancel</button></div> : <div style={{ marginTop: 2, overflowWrap: 'anywhere', lineHeight: 1.35, fontSize: 12, color: '#38bdf8', WebkitTextFillColor: '#38bdf8' }}>{comment.content}</div>}
          <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 4 }}><div ref={(node) => { commentReactionRefs.current[comment.id] = node; }} style={{ position: 'relative' }}><button type="button" aria-haspopup="true" aria-expanded={openCommentReactionId === comment.id} onClick={() => setOpenCommentReactionId(openCommentReactionId === comment.id ? null : comment.id)} style={{ ...softButton, padding: '3px 7px', fontSize: 10 }}>{myReaction ? `${reactionEmoji[myReaction]} ${counts[myReaction] ?? 0}` : `❤️${totalReactions ? ` ${totalReactions}` : ''}`}</button>{openCommentReactionId === comment.id && <div role="group" aria-label="Comment reactions" style={{ position: 'absolute', left: 0, bottom: 'calc(100% + 5px)', zIndex: 7, display: 'flex', gap: 4, padding: 6, background: '#fff', border: '1px solid rgba(80,100,130,.14)', borderRadius: 11, boxShadow: '0 10px 22px rgba(20,35,60,.14)' }}>{reactionOptions.map((item) => <button key={item.value} type="button" aria-label={item.label} title={item.label} onClick={() => void reactToComment(comment.id, item.value)} style={{ border: 0, background: 'transparent', borderRadius: 7, padding: 2, fontSize: 17, cursor: 'pointer' }}>{item.emoji}</button>)}</div>}</div><button type="button" onClick={() => { setReplyToCommentId(comment.id); setReplyText(''); }} style={{ ...softButton, padding: '3px 7px', fontSize: 10 }}>Reply</button></div>
          {replyToCommentId === comment.id && <div style={{ display: 'flex', gap: 6, marginTop: 5, minWidth: 0 }}><input value={replyText} onChange={(event) => setReplyText(event.target.value)} placeholder="Write a reply..." style={{ ...hudWritingStyle, flex: 1, minWidth: 0, border: '1px solid rgba(80,100,130,.16)', borderRadius: 10, padding: '6px 8px', fontSize: 11, boxSizing: 'border-box' }} /><button type="button" onClick={() => void addComment(comment.post_id, comment.id)} style={{ ...softButton, padding: '5px 9px', fontSize: 11 }}>Reply</button><button type="button" onClick={() => setReplyToCommentId(null)} style={{ ...softButton, padding: '5px 9px', fontSize: 11 }}>Cancel</button></div>}
          {children.map((child) => renderComment(child, allComments, depth + 1))}
        </div>
      </div>
    </div>;
  };

  return <section className="home-feed-surface-less" style={{ minWidth: 0, background: 'transparent', backgroundImage: 'none', boxShadow: 'none', border: 0, backdropFilter: 'none', WebkitBackdropFilter: 'none', filter: 'none' }}>
<div style={{ display: 'flex', alignItems: 'center', gap: 10, margin: '4px 2px 12px', padding: '8px 12px', borderRadius: 14, background: 'transparent', border: '0', boxShadow: 'none' }}><span style={{ width: 8, height: 28, borderRadius: 99, background: 'linear-gradient(180deg,#6d7cff,#b56cff)', boxShadow: '0 0 12px rgba(109,124,255,.35)' }} /><h2 style={{ margin: 0, fontSize: 17, letterSpacing: '.01em' }}>Posts</h2><span style={{ marginLeft: 'auto', fontSize: 11, opacity: .55, fontWeight: 700, letterSpacing: '.08em', textTransform: 'uppercase' }}>Community feed</span></div>{error && <p role="alert">{error}</p>}
    {posts.map((post) => { const isOwner = post.profile_id === profileId; const privacy = (post.privacy ?? 'public') as PostPrivacy; const counts = reactionCounts[post.id] ?? {}; const myReaction = myReactions[post.id]; const totalReactions = Object.values(counts).reduce((sum, value) => sum + value, 0); const postComments = comments[post.id] ?? []; const latestComment = postComments[postComments.length - 1]; const attachments = post.attachments ?? []; const imageAttachments = attachments.filter((attachment: any) => attachment.kind === 'image'); const allImages = attachments.length > 0 && imageAttachments.length === attachments.length;
      const renderImage = (attachment: any, index: number, extraCount = 0) => <button key={attachment.id} type="button" onClick={() => openMedia('image', attachment.public_url, attachment.file_name ?? 'Post image')} aria-label={`Open ${attachment.file_name ?? 'post image'}`} style={{ position: 'relative', display: 'block', width: '100%', minWidth: 0, height: '100%', maxWidth: '100%', padding: 0, margin: 0, border: 0, background: 'transparent', cursor: 'zoom-in', overflow: 'hidden', borderRadius: 13 }}><img src={attachment.public_url} alt={attachment.file_name ?? 'Post image'} style={{ display: 'block', width: '100%', height: '100%', maxWidth: '100%', objectFit: 'cover' }} />{extraCount > 0 && index === 3 && <span aria-hidden="true" style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', pointerEvents: 'none', background: 'rgba(0,0,0,.52)', color: '#fff', fontSize: 28, fontWeight: 800 }}>{`+${extraCount}`}</span>}</button>;
      const imageCollage = allImages && imageAttachments.length > 1 ? <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)', gridTemplateRows: imageAttachments.length === 2 ? 'minmax(0, 1fr)' : 'minmax(0, 1fr) minmax(0, 1fr)', gap: 4, width: '100%', minWidth: 0, maxWidth: '100%', height: imageAttachments.length === 2 ? 300 : 420, overflow: 'hidden', borderRadius: 13 }}>{imageAttachments.slice(0, 4).map((attachment: any, index: number) => <div key={attachment.id} style={{ minWidth: 0, minHeight: 0, gridColumn: imageAttachments.length === 3 && index === 2 ? '1 / -1' : undefined }}>{renderImage(attachment, index, imageAttachments.length > 4 ? imageAttachments.length - 4 : 0)}</div>)}</div> : null;
      const singleImage = allImages && imageAttachments.length === 1 ? <button key={imageAttachments[0].id} type="button" onClick={() => openMedia('image', imageAttachments[0].public_url, imageAttachments[0].file_name ?? 'Post image')} aria-label={`Open ${imageAttachments[0].file_name ?? 'post image'}`} style={{ display: 'block', width: '100%', maxWidth: '100%', padding: 0, margin: 0, border: 0, background: 'transparent', cursor: 'zoom-in', overflow: 'hidden', borderRadius: 13 }}><img src={imageAttachments[0].public_url} alt={imageAttachments[0].file_name ?? 'post image'} style={{ display: 'block', width: '100%', maxWidth: '100%', maxHeight: 520, objectFit: 'contain', borderRadius: 13, boxShadow: '0 6px 18px rgba(20,35,60,.08)' }} /></button> : null;
      const rootComments = postComments.filter((comment) => !comment.parent_comment_id); const latestProfile = latestComment ? commentProfile(latestComment) : null;
      return <article key={post.id} style={{ position: 'relative', marginBottom: 14, padding: 14, borderRadius: 0, background: 'transparent', backgroundColor: 'transparent', backgroundImage: 'none', border: '0', boxShadow: 'none', backdropFilter: 'none', WebkitBackdropFilter: 'none', filter: 'none', minWidth: 0, maxWidth: '100%', boxSizing: 'border-box', overflow: 'visible' }}>
        <header style={{ display: 'flex', alignItems: 'center', gap: 10, minWidth: 0, padding: '2px 2px 10px', borderBottom: '0' }}><div style={{ flexShrink: 0, padding: 2, borderRadius: '50%', background: 'linear-gradient(145deg,#ffffff,#dfe5ec)', boxShadow: '0 4px 12px rgba(20,35,60,.12)' }}>{post.profiles?.avatar_url ? <img src={post.profiles.avatar_url} alt="" width={42} height={42} style={{ display: 'block', borderRadius: '50%', objectFit: 'cover' }} /> : <div aria-hidden="true" style={{ width: 42, height: 42, borderRadius: '50%', display: 'grid', placeItems: 'center', background: '#eef2f6' }}>👤</div>}</div><div style={{ minWidth: 0, flex: 1 }}><strong style={{ ...hudNameStyle, display: 'block', minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 14 }}>{post.profiles?.display_name ?? 'User'}</strong><small style={{ display: 'block', marginTop: 2, opacity: .55, fontSize: 11 }}>{new Date(post.created_at).toLocaleString()}</small></div><span style={{ fontSize: 10, opacity: .55, fontWeight: 700, padding: '5px 8px', borderRadius: 999, background: 'transparent', backgroundColor: 'transparent', backgroundImage: 'none', border: '1px solid transparent', boxShadow: 'none', whiteSpace: 'nowrap' }}>{privacyLabels[privacy]}</span><button type="button" aria-label="Post options" onClick={() => setOpenMenuId(openMenuId === post.id ? null : post.id)} style={{ ...softButton, width: 34, height: 34, padding: 0, fontSize: 18 }}>⋯</button></header>
        {openMenuId === post.id && <div role="menu" style={{ position: 'absolute', right: 14, top: 66, zIndex: 20, width: 'min(190px, calc(100vw - 40px))', maxHeight: 'min(320px, calc(100dvh - 104px))', overflowY: 'auto', overflowX: 'hidden', padding: 10, display: 'grid', gap: 5, background: 'rgba(255,255,255,.99)', border: '1px solid rgba(80,100,130,.14)', borderRadius: 14, boxShadow: '0 16px 34px rgba(20,35,60,.18)', backdropFilter: 'blur(12px)', overscrollBehavior: 'contain', WebkitOverflowScrolling: 'touch' }}><strong style={{ fontSize: 11, opacity: .65, padding: '2px 6px' }}>Privacy</strong>{(['public', 'friends', 'private'] as PostPrivacy[]).map((value) => <button key={value} type="button" onClick={() => void changePrivacy(post.id, value)} style={{ ...softButton, borderRadius: 9, padding: '7px 10px', textAlign: 'left' }}>{privacyLabels[value]}{privacy === value ? ' ✓' : ''}</button>)}{isOwner && <><button type="button" onClick={() => startEdit(post)} style={{ ...softButton, borderRadius: 9, padding: '7px 10px', textAlign: 'left' }}>Edit</button><button type="button" onClick={() => { setOpenMenuId(null); setConfirmDeleteId(post.id); }} style={{ ...softButton, borderRadius: 9, padding: '7px 10px', textAlign: 'left' }}>Delete</button></>}</div>}
        {post.content && <p style={{ margin: '12px 2px 0', overflowWrap: 'anywhere', lineHeight: 1.55, fontSize: 14, color: '#38bdf8', WebkitTextFillColor: '#38bdf8' }}>{post.content}</p>}
        {attachments.length > 0 && <div style={{ display: 'grid', gap: 8, marginTop: 11, minWidth: 0, maxWidth: '100%', overflow: 'hidden' }}>{allImages ? (imageAttachments.length === 1 ? singleImage : imageCollage) : attachments.map((attachment: any) => attachment.kind === 'image' ? <button key={attachment.id} type="button" onClick={() => openMedia('image', attachment.public_url, attachment.file_name ?? 'Post image')} aria-label={`Open ${attachment.file_name ?? 'post image'}`} style={{ display: 'block', width: '100%', maxWidth: '100%', padding: 0, margin: 0, border: 0, background: 'transparent', cursor: 'zoom-in', overflow: 'hidden', borderRadius: 13 }}><img src={attachment.public_url} alt={attachment.file_name ?? 'Post image'} style={{ display: 'block', width: '100%', maxWidth: '100%', maxHeight: 520, objectFit: 'contain', borderRadius: 13, boxShadow: '0 6px 18px rgba(20,35,60,.08)' }} /></button> : attachment.kind === 'video' ? <button key={attachment.id} type="button" onClick={() => openMedia('video', attachment.public_url, attachment.file_name ?? 'Post video')} aria-label={`Open ${attachment.file_name ?? 'post video'}`} style={{ display: 'block', width: '100%', maxWidth: '100%', padding: 0, margin: 0, border: 0, background: 'transparent', cursor: 'zoom-in', overflow: 'hidden', borderRadius: 13 }}><video src={attachment.public_url} controls preload="metadata" onClick={(event) => event.stopPropagation()} style={{ display: 'block', width: '100%', maxWidth: '100%', maxHeight: 520, borderRadius: 13 }} /> </button> : <a key={attachment.id} href={attachment.public_url} target="_blank" rel="noreferrer">📎 {attachment.file_name ?? 'Attached file'}</a>)}</div>}
        {(post.location_name || post.latitude !== null) && <div style={{ marginTop: 9, display: 'inline-flex', padding: '6px 9px', borderRadius: 999, background: 'transparent', border: '0', fontSize: 11 }}>📍 {post.location_name ?? `${Number(post.latitude).toFixed(5)}, ${Number(post.longitude).toFixed(5)}`}</div>}
        <footer style={{ marginTop: 12, paddingTop: 10, borderTop: '0' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, minWidth: 0 }}><div ref={(node) => { reactionRefs.current[post.id] = node; }} style={{ position: 'relative', minWidth: 0 }}><button type="button" aria-haspopup="true" aria-expanded={openReactionId === post.id} onClick={() => setOpenReactionId(openReactionId === post.id ? null : post.id)} style={{ ...softButton, padding: '7px 12px', fontSize: 12 }}>{myReaction ? `${reactionEmoji[myReaction]} ${counts[myReaction] ?? 0}` : `❤️ Like${totalReactions ? ` (${totalReactions})` : ''}`}</button>{openReactionId === post.id && <div role="group" aria-label="Reactions" style={{ position: 'absolute', left: 0, bottom: 'calc(100% + 7px)', zIndex: 5, display: 'flex', gap: 5, padding: 8, background: 'transparent', backgroundColor: 'transparent', backgroundImage: 'none', border: '1px solid transparent', borderRadius: 14, boxShadow: 'none' }}>{reactionOptions.map((item) => <button key={item.value} type="button" aria-label={item.label} title={item.label} onClick={() => void react(post.id, item.value)} style={{ border: 0, background: 'transparent', borderRadius: 9, padding: 3, fontSize: 21, cursor: 'pointer' }}>{item.emoji}</button>)}</div>}</div><button type="button" onClick={async () => { const url = `${window.location.origin}/?post=${encodeURIComponent(post.id)}`; if (navigator.share) await navigator.share({ title: 'Work Social post', text: post.content ?? '', url }); else await navigator.clipboard.writeText(url); }} style={{ ...softButton, padding: '7px 12px', fontSize: 12 }}>↗️ Share</button></div>
          {!openCommentsId && latestComment && <div style={{ marginTop: 10, padding: 9, borderRadius: 13, background: 'transparent', border: '0', minWidth: 0 }}><div style={{ display: 'flex', gap: 8, alignItems: 'center', minWidth: 0 }}>{latestProfile?.avatar_url ? <img src={latestProfile.avatar_url} alt="" width={28} height={28} style={{ borderRadius: '50%', objectFit: 'cover', flexShrink: 0 }} /> : <div aria-hidden="true" style={{ width: 28, height: 28, borderRadius: '50%', display: 'grid', placeItems: 'center', background: '#e9edf2', flexShrink: 0 }}>👤</div>}<strong style={{ ...hudNameStyle, fontSize: 12 }}>{latestProfile?.display_name ?? 'User'}</strong><span style={{ minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 12, opacity: .72 }}>{latestComment.content}</span></div><button type="button" onClick={() => setOpenCommentsId(post.id)} style={{ ...softButton, display: 'block', marginTop: 7, padding: '5px 10px', fontSize: 11 }}>View all {postComments.length} comment{postComments.length === 1 ? '' : 's'} →</button></div>}
          {openCommentsId === post.id && <div style={{ marginTop: 10, padding: 11, borderRadius: 15, background: 'transparent', border: '0', minWidth: 0, overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingBottom: 8, borderBottom: '0' }}><strong style={{ ...hudNameStyle, fontSize: 13 }}>Comments <span style={{ opacity: .5 }}>({postComments.length})</span></strong><button type="button" onClick={() => setOpenCommentsId(null)} style={{ ...softButton, padding: '5px 10px', fontSize: 11 }}>Close</button></div>{rootComments.map((comment) => renderComment(comment, postComments))}</div>}
          <div style={{ display: 'flex', gap: 8, marginTop: 10, minWidth: 0, padding: 5, borderRadius: 15, background: 'transparent', border: '0', boxShadow: 'none' }}><input value={commentText[post.id] ?? ''} onChange={(event) => setCommentText((current) => ({ ...current, [post.id]: event.target.value }))} placeholder="Write a comment..." style={{ ...hudWritingStyle, minWidth: 0, flex: 1, border: 0, outline: 'none', background: 'transparent', padding: '7px 8px', fontSize: 13 }} /><button type="button" onClick={() => void addComment(post.id)} style={{ ...softButton, padding: '7px 12px', fontSize: 12 }}>Comment</button></div>
        </footer>
      </article>;
    })}
    {!error && posts.length === 0 && <p>No posts yet.</p>}
    {editingId && <div role="dialog" aria-modal="true" aria-labelledby="edit-post-title" onClick={(event) => { if (event.target === event.currentTarget) setEditingId(null); }} style={{ position: 'fixed', inset: 0, zIndex: 1200, display: 'grid', placeItems: 'center', padding: 18, boxSizing: 'border-box', background: 'rgba(2,8,23,.16)', backdropFilter: 'blur(3px)', WebkitBackdropFilter: 'blur(3px)' }}>
      <div style={{ position: 'relative', width: 'min(560px, calc(100vw - 32px))', maxWidth: '100%', boxSizing: 'border-box', padding: 2, borderRadius: 28, background: 'linear-gradient(135deg, rgba(86,236,255,.78), rgba(129,92,255,.62) 48%, rgba(255,91,194,.72))', boxShadow: '0 36px 100px rgba(0,0,0,.48), 0 0 70px rgba(72,211,255,.18), 0 0 90px rgba(173,82,255,.12)', transform: 'translateZ(0)' }}>
        <div style={{ position: 'relative', overflow: 'hidden', borderRadius: 26, padding: 24, background: 'linear-gradient(145deg, rgba(8,22,43,.18), rgba(12,18,43,.10))', border: '1px solid rgba(255,255,255,.18)', backdropFilter: 'blur(26px) saturate(165%)', WebkitBackdropFilter: 'blur(26px) saturate(165%)', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.24), inset 0 -1px 0 rgba(96,210,255,.12)' }}>
          <div aria-hidden="true" style={{ position: 'absolute', inset: '0 12% auto 12%', height: 1, background: 'linear-gradient(90deg, transparent, rgba(255,255,255,.75), rgba(91,220,255,.7), transparent)', boxShadow: '0 0 18px rgba(91,220,255,.55)' }} />
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 14 }}>
            <div aria-hidden="true" style={{ width: 50, height: 50, flexShrink: 0, display: 'grid', placeItems: 'center', borderRadius: 17, color: '#67e8f9', background: 'linear-gradient(145deg, rgba(73,225,255,.24), rgba(110,72,255,.14))', border: '1px solid rgba(103,232,249,.42)', boxShadow: '0 12px 28px rgba(0,198,255,.18), inset 0 1px 0 rgba(255,255,255,.25)', fontSize: 24 }}>✎</div>
            <div style={{ minWidth: 0, flex: 1 }}>
              <h2 id="edit-post-title" style={{ margin: 0, fontSize: 'clamp(20px, 5vw, 25px)', lineHeight: 1.15, letterSpacing: '.015em', fontWeight: 900, background: 'linear-gradient(90deg,#67e8f9,#a78bfa,#f0abfc)', WebkitBackgroundClip: 'text', backgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Edit Post</h2>
              <p style={{ margin: '6px 0 0', color: '#b9d8ff', fontSize: 11, letterSpacing: '.06em', textTransform: 'uppercase' }}>Update your thoughts</p>
            </div>
            <button type="button" aria-label="Close edit post" onClick={() => setEditingId(null)} style={{ width: 38, height: 38, flexShrink: 0, border: '1px solid rgba(255,255,255,.18)', borderRadius: 12, background: 'rgba(255,255,255,.055)', color: '#d9f8ff', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.16), 0 8px 20px rgba(0,0,0,.18)', cursor: 'pointer', fontSize: 23, lineHeight: 1 }}>×</button>
          </div>
          <textarea value={editContent} onChange={(event) => setEditContent(event.target.value)} rows={6} autoFocus style={{ width: '100%', minHeight: 150, marginTop: 20, boxSizing: 'border-box', resize: 'vertical', borderRadius: 18, border: '1px solid rgba(103,232,249,.42)', outline: 'none', padding: 15, color: '#ecfeff', background: 'rgba(3,12,28,.14)', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.10), 0 10px 30px rgba(0,0,0,.12)', backdropFilter: 'blur(12px)', WebkitBackdropFilter: 'blur(12px)', fontFamily: 'JetBrains Mono, monospace', fontSize: 14, lineHeight: 1.55 }} />
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10, marginTop: 14, flexWrap: 'wrap' }}>
            <button type="button" onClick={() => setEditingId(null)} style={{ minWidth: 102, padding: '10px 17px', border: '1px solid rgba(145,190,255,.38)', borderRadius: 13, background: 'rgba(255,255,255,.045)', color: '#bfe9ff', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.16), 0 8px 22px rgba(0,0,0,.18)', cursor: 'pointer', fontWeight: 800 }}>Cancel</button>
            <button type="button" onClick={() => void saveEdit(editingId)} style={{ minWidth: 118, padding: '10px 19px', border: '1px solid rgba(103,232,249,.58)', borderRadius: 13, background: 'linear-gradient(135deg, rgba(24,210,255,.78), rgba(112,77,255,.72), rgba(235,81,199,.70))', color: '#f7fdff', boxShadow: '0 10px 28px rgba(44,183,255,.22), inset 0 1px 0 rgba(255,255,255,.34)', cursor: 'pointer', fontWeight: 900 }}>Save changes</button>
          </div>
        </div>
      </div>
    </div>}
    {confirmDeleteId && <div role="dialog" aria-modal="true" aria-labelledby="delete-post-title" onClick={(event) => { if (event.target === event.currentTarget) setConfirmDeleteId(null); }} style={{ position: 'fixed', inset: 0, zIndex: 1200, display: 'grid', placeItems: 'center', padding: 18, boxSizing: 'border-box', background: 'rgba(12,3,20,.14)', backdropFilter: 'blur(3px)', WebkitBackdropFilter: 'blur(3px)' }}>
      <div style={{ position: 'relative', width: 'min(500px, calc(100vw - 32px))', maxWidth: '100%', boxSizing: 'border-box', padding: 2, borderRadius: 28, background: 'linear-gradient(135deg, rgba(255,109,163,.76), rgba(141,92,255,.54), rgba(87,220,255,.52))', boxShadow: '0 36px 100px rgba(0,0,0,.50), 0 0 72px rgba(255,78,155,.16)', transform: 'translateZ(0)' }}>
        <div style={{ position: 'relative', overflow: 'hidden', borderRadius: 26, padding: 24, background: 'linear-gradient(145deg, rgba(31,10,32,.16), rgba(10,18,40,.10))', border: '1px solid rgba(255,255,255,.18)', backdropFilter: 'blur(26px) saturate(160%)', WebkitBackdropFilter: 'blur(26px) saturate(160%)', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.24), inset 0 -1px 0 rgba(255,93,164,.14)' }}>
          <div aria-hidden="true" style={{ position: 'absolute', inset: '0 12% auto 12%', height: 1, background: 'linear-gradient(90deg, transparent, rgba(255,255,255,.72), rgba(255,93,164,.72), transparent)', boxShadow: '0 0 18px rgba(255,93,164,.45)' }} />
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 14 }}>
            <div aria-hidden="true" style={{ width: 50, height: 50, flexShrink: 0, display: 'grid', placeItems: 'center', borderRadius: 17, color: '#ff7aa8', background: 'linear-gradient(145deg, rgba(255,86,145,.22), rgba(139,74,255,.14))', border: '1px solid rgba(255,109,163,.46)', boxShadow: '0 12px 28px rgba(255,61,132,.18), inset 0 1px 0 rgba(255,255,255,.25)', fontSize: 23 }}>⌫</div>
            <div style={{ minWidth: 0, flex: 1 }}>
              <h2 id="delete-post-title" style={{ margin: 0, fontSize: 'clamp(20px, 5vw, 25px)', lineHeight: 1.15, letterSpacing: '.015em', fontWeight: 900, background: 'linear-gradient(90deg,#ff86ad,#f0abfc,#a5b4fc)', WebkitBackgroundClip: 'text', backgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Delete Post</h2>
              <p style={{ margin: '7px 0 0', color: '#ffd0df', lineHeight: 1.55, fontSize: 13 }}>Are you sure you want to delete this post? This action cannot be undone.</p>
            </div>
            <button type="button" aria-label="Close delete confirmation" onClick={() => setConfirmDeleteId(null)} style={{ width: 38, height: 38, flexShrink: 0, border: '1px solid rgba(255,255,255,.18)', borderRadius: 12, background: 'rgba(255,255,255,.055)', color: '#ffe4ef', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.16), 0 8px 20px rgba(0,0,0,.18)', cursor: 'pointer', fontSize: 23, lineHeight: 1 }}>×</button>
          </div>
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10, marginTop: 22, flexWrap: 'wrap' }}>
            <button type="button" onClick={() => setConfirmDeleteId(null)} style={{ minWidth: 102, padding: '10px 17px', border: '1px solid rgba(145,190,255,.38)', borderRadius: 13, background: 'rgba(255,255,255,.045)', color: '#c9e9ff', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.16), 0 8px 22px rgba(0,0,0,.18)', cursor: 'pointer', fontWeight: 800 }}>Cancel</button>
            <button type="button" onClick={() => { const postId = confirmDeleteId; setConfirmDeleteId(null); if (postId) void removePost(postId); }} style={{ minWidth: 112, padding: '10px 18px', border: '1px solid rgba(255,112,158,.62)', borderRadius: 13, background: 'linear-gradient(135deg, rgba(255,83,133,.84), rgba(219,61,143,.72))', color: '#fff7fb', boxShadow: '0 10px 28px rgba(255,61,132,.22), inset 0 1px 0 rgba(255,255,255,.34)', cursor: 'pointer', fontWeight: 900 }}>Delete post</button>
          </div>
        </div>
      </div>
    </div>}
    {lightboxMedia && <div role="dialog" aria-modal="true" aria-label="Media viewer" onClick={() => setLightboxMedia(null)} style={{ position: 'fixed', inset: 0, zIndex: 1000, background: 'rgba(0,0,0,.92)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16, boxSizing: 'border-box' }}><button type="button" aria-label="Close media viewer" onClick={() => setLightboxMedia(null)} style={{ position: 'absolute', top: 16, right: 16, zIndex: 1002, width: 44, height: 44, border: 0, borderRadius: '50%', background: 'rgba(0,0,0,.6)', color: '#fff', fontSize: 28, lineHeight: 1, cursor: 'pointer' }}>×</button><div onClick={(event) => event.stopPropagation()} style={{ position: 'relative', width: '100%', height: '100%', maxWidth: 1400, display: 'flex', alignItems: 'center', justifyContent: 'center', minWidth: 0, minHeight: 0 }}>{lightboxMedia.type === 'image' ? <img src={lightboxMedia.url} alt={lightboxMedia.alt ?? 'Full screen view'} style={{ display: 'block', maxWidth: '95vw', maxHeight: '90vh', width: 'auto', height: 'auto', objectFit: 'contain', borderRadius: 10 }} /> : <video src={lightboxMedia.url} controls autoPlay playsInline preload="metadata" style={{ display: 'block', maxWidth: '95vw', maxHeight: '90vh', width: 'auto', height: 'auto', borderRadius: 10 }} />}</div></div>}
  </section>;
}
